### ISSUE TITLE
Fix mod_log_chat and mod_cron compilation

### ISSUE THREAD

**Issue by vishnus90** [processone/ejabberd-contrib#103]
I am trying to install mod_log_chat module on a ejabberd-15.03 installation using the command ejabberdctl command. But it fails with following error. Can someone help me on this please?

root@04:/home# /opt/apps/jabber15.03/sbin/ejabberdctl module_install mod_log_chat
src/mod_log_chat.erl:20: redefining macro 'LAGER'
Error: {compilation_failed,"src/mod_log_chat.erl"}

Thanks
Qube

**Comment by mathiasertl** [comment]
This patch: https://github.com/jabber-at/ejabberd-modules/blob/master/debian/patches/xml-includes.patch - in our own package should fix the issue. Can I get this merged without an extra merge request?

**Comment by badlop** [comment]
I'll apply the patch in git, thanks!
