### ISSUE TITLE
mod_multicast clustering

### ISSUE THREAD

**Issue by hairyhum** [processone/ejabberd-contrib#105]
When added `mod_multicast` to cluster of 2 ejabberd servers got following errors in log:
```
 [error] <0.3299.0>@ejabberd_router_multicast:route_multicast:47 {{case_clause,[{route_multicast,<<"host">>,<11984.762.0>},{route_multicast,<<"host">>,<11983.333.0>}]},[{ejabberd_router_multicast,do_route,4,[{file,"src/ejabberd_router_multicast.erl"},{line,224}]},{ejabberd_router_multicast,route_multicast,4,[{file,"src/ejabberd_router_multicast.erl"},{line,45}]},{ejabberd_c2s,terminate,3,[{file,"src/ejabberd_c2s.erl"},{line,1864}]},{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,740}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
```
Looks like it registers multicast service for each node and `ejabberd_router_multicast` should do something about it.

**Comment by mremond** [comment]
mod_multicast is now part of ejabberd itself. Did you try with the ejabberd version ? Do you have the same issue ?

**Comment by hairyhum** [comment]
There are same errors in ejabberd 15.04 version.
Looks like it is caused by this match
https://github.com/processone/ejabberd/blob/master/src/ejabberd_router_multicast.erl#L206

I am not sure how multicast service should be chosen if there are more than one. Should it be just first of them?

**Comment by badlop** [comment]
I've committed a fix here:
https://github.com/processone/ejabberd/commit/fe10c6f6f2e28cb116f9e6f37cfb5927e49546ba
