### ISSUE TITLE
mod_mam_mnesia issue

### ISSUE THREAD

**Issue by pitbeta86** [processone/ejabberd-contrib#110]
I am using mod_mam_mnesia in ejabberd 14.12.
After adding module to .yml file and restarting the ejabberd ,errors are showing in the log files.

For example this type of error is showing-
2015-07-14 18:45:40.845 [error] <0.26774.1>@ejabberd_hooks:run1:315 {undef,[{mod_mam_mnesia,receive_stanza,[{jid,<<"536---------------------------->>}],[]}],[]},{ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,311}]},{ejabberd_c2s,handle_info,3,[{file,"src/ejabberd_c2s.erl"},{line,1706}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,581}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
running hook: {user_receive_packet,[{jid,<<"536--------<<"result">>}],[]}]}

And mam_msg table didn't create in the mnesia database and message were also not store in database.

**Comment by weiss** [comment]
The current version requires ejabberd 15.06.  For older ejabberd 14.12, you will want to check out commit e5d24089d22d5d91b40052a1f80d9f6d868d7d44 of the ejabberd-contrib repository and use that.

**Comment by sankalpmishra86** [comment]
I use the previous version but mam_msg table didn't create in the mnesia database and message were also not store in database.

Therefor when i try to send a message it is showing an error for example-

2015-07-14 20:09:08.474 [error] <0.30170.1> gen_server 'mod_mam_mnesia_....' terminated with reason: no match of right hand value {aborted,{no_exists,mam_msg}} in mod_mam_mnesia:maybe_store_message/4 line 450
2015-07-14 20:09:08.474 [error] <0.30170.1> CRASH REPORT Process 'mod_mam_mnesia_....' with 0 neighbours exited with reason: no match of right hand value {aborted,{no_exists,mam_msg}} in mod_mam_mnesia:maybe_store_message/4 line 450 in gen_server:terminate/6 line 744
2015-07-14 20:09:08.474 [error] <0.28924.1> Supervisor ejabberd_sup had child 'mod_mam_mnesia_........' started with mod_mam_mnesia:start_link(<<"...........">>, [{access_max_user_messages,max_user_mam_messages},{default_page_size,25},{max_page_size,100},{request_activates_archiving,...}]) at <0.30170.1> exit with reason no match of right hand value {aborted,{no_exists,mam_msg}} in mod_mam_mnesia:maybe_store_message/4 line 450 in context child_terminated

**Comment by weiss** [comment]
> I use the previous version but mam_msg table didn't create in the mnesia database and message were also not store in database.

That's odd, the module will usually create the table on startup.  Just to double-check, what's the output of the following command?

    ejabberdctl mnesia info | grep '^mam_'

**Comment by sankalpmishra86** [comment]
/opt/ejabberd-14.12/bin/ejabberdctl mnesia info | grep '^mam_'

mam_meta       : with 0        records occupying 299      words of mem

**Comment by weiss** [comment]
This output doesn't change even after restarting ejabberd?

**Comment by sankalpmishra86** [comment]
No the output is same
mam_meta : with 0 records occupying 299 words of mem

**Comment by sankalpmishra86** [comment]
This is process i followed to add the module.
First clone the .erl file.

Then compile it by using 
"erlc -DLAGER=true -I /opt/ejabberd-14.12/lib/ejabberd-14.12/include -pa /opt/ejabberd-14.12/lib/ejabberd-14.12/ebin/ mod_mam_mnesia.erl"

Then move the beam file to ejabberd ebin folder like
"mv mod_mam_mnesia.beam /opt/ejabberd-14.12/lib/ejabberd-14.12/ebin/"

Then edit the yml file and add these options
 mod_mam_mnesia:
         access_max_user_messages: max_user_mam_messages
         default_page_size: 25
         max_page_size: 100
          request_activates_archiving: false

Then restart the ejabberd.

Is there anything wrong in this process?

**Comment by weiss** [comment]
If you checked out commit e5d24089d22d5d91b40052a1f80d9f6d868d7d44, there should be a `./build.sh` file in the `mod_mam_mnesia` directory that you could use instead of the `erlc` command line.  But if the latter doesn't spit out any errors, that should be fine as well.

To track things down, I'd delete the `mam_meta` table in an `ejabberdctl debug` shell:

    mnesia:delete_table(mam_meta).

(Don't forget the trailing dot, and then press Ctrl+C twice to get out of the shell.) I'd then restart ejabberd and would check the

    ejabberdctl mnesia info | grep '^mam_'

output again.  Does the `mam_meta` table still show up?

Apart from that: If you grep your log files for `mod_mam`, do you find any other entries?

**Comment by sankalpmishra86** [comment]
As you said first i delete the table 

mnesia:delete_table(mam_meta).
{atomic,ok}

Then i restart the ejabberd then use this 
ejabberdctl mnesia info | grep '^mam_'

The output is 

mam_meta : with 0 records occupying 299 words of mem

And yes mam_meta table showed up.And no mam_msg table.

If you grep your log files for mod_mam, do you find any other entries?>>>

Is this mean the ejabberd log file?
I checked it it is showing the above error details 

2015-07-14 20:09:08.474 [error] <0.30170.1> gen_server 'mod_mam_mnesia_....' terminated with reason: no match of right hand value {aborted,{no_exists,mam_msg}} in mod_mam_mnesia:maybe_store_message/4 line 450......
............

**Comment by weiss** [comment]
What output do you get if you create the table manually in an `ejabberdctl debug` shell using the following calls?

    Attrs = [key, time, route, from, to, stanza].
    Props = [{n_fragments, 2}, {n_disc_only_copies, length([myself | nodes()])}].
    mnesia:create_table(mam_msg, [{frag_properties, Props}, {attributes, Attrs}]).

**Comment by pitbeta86** [comment]
These are the outputs i got-

Attrs = [key, time, route, from, to, stanza].
[key,time,route,from,to,stanza]

Props = [{n_fragments, 2}, {n_disc_only_copies, length([myself | nodes()])}].
[{n_fragments,2},{n_disc_only_copies,1}]

mnesia:create_table(mam_msg, [{frag_properties, Props}, {attributes, Attrs}]).
{aborted,{not_active,mam_msg_frag2,ejabberd@slaveDB}}

mam_msg table didn't create in the database.

Note:-I am using master/slave replication for my DB servers.

**Comment by pitbeta86** [comment]
Is this problem due to master/slave replication of my DB servers?

Is there any solution to this problem?

**Comment by weiss** [comment]
> `{aborted,{not_active,mam_msg_frag2,ejabberd@slaveDB}}`

The remote node `ejabberd@slaveDB` was added to the Mnesia schema, but it's currently not available.  Either make it available or run the following call in an `ejabberdctl debug` shell to remove the remote node from the schema:

    mnesia:del_table_copy(schema, ejabberd@slaveDB).
