### ISSUE TITLE
ejabberd_auth_http no match of right hand value - fails to load

### ISSUE THREAD

**Issue by richp10** [processone/ejabberd-contrib#111]
Ejabberd 15.07 
cp ejabberd-contrib/ejabberd_auth_http/src/* ejabberd/src
Then ejabberd compiled.  Runs fine and as usual until I try and configure ejabberd_auth_http

auth_method: http
auth_opts:
  host: "http://10.10.0.5" 

Fails to load, with

``` CRASH REPORT Process <0.6070.0> with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{undef,[{cuesport,start_link,['ejabberd_auth_http_mydomain.org',10,[fusco],{fusco,start_link,["http://10.10.0.5",[]]}],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,685}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,394}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,...}]}},...}} in ejabberd_auth_http:start/1 line 57 in application_master:init/4 line 133 ```

```Application ejabberd exited with reason: no match of right hand value {error,{{'EXIT',{undef,[{cuesport,start_link,['ejabberd_auth_http_recoveryonline.org',10,[fusco],{fusco,start_link,["http://172.17.0.28",[]]}],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,685}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,394}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,...}]}},...}} in ejabberd_auth_http:start/1 line 57```

Any thoughts? I don't know erlang so might struggle to provide further under the bonnet information unless I have very clear instructions..

**Comment by cromain** [comment]
you're missing the deps
BTW, it's way more simpler to call ejabberdctl module_install ejabberd_auth_http

**Comment by richp10** [comment]
Thanks - but sorry - still not working for me..

ejabberdctl modules_update_specs
ok
ejabberdctl module_install ejabberd_auth_http
ok
ls -a ./home/ejabberd/.ejabberd-modules/ejabberd_auth_http/ebin
Shows the fusco and other beams there 

Restart ejabberd and the same error is being shown.  

Looks like it is not loading properly but I really can't think why...

Thanks..
