### ISSUE TITLE
mod_mam_mnesia does not support filetering by  JID

### ISSUE THREAD

**Issue by ucftk** [processone/ejabberd-contrib#112]
There are some issues when you want to query for messages to/from a particular JID. the server returns all archived messages not only the ones related to the specified JID.

**Comment by weiss** [comment]
Could you show us a dump of the relevant traffic, please?

**Comment by ucftk** [comment]
The stanza is :

<iq type='set'
    id='juliet1'>
<query xmlns='urn:xmpp:mam:0'>
<x xmlns='jabber:x:data'
   type='submit'>
<field var='FORM_TYPE'
       type='hidden'>
<value>
urn:xmpp:mam:0
</value>
</field>
<field var='with'>
<value>
mlskdf@lmsdf.com
</value>
</field>
</x>
</query>
</iq>

The server's response:

<iq xmlns='jabber:client'
    from='ucf@host.com'
    to='ucf@host.com/25051288531439402705425977'
    type='result'
    id='juliet1'/>
<message xmlns='jabber:client'
         from='ucf@host.com'
         to='ucf@host.com/25051288531439402705425977'
         id='0t5BT7/gpwtd'>
<result xmlns='urn:xmpp:mam:0'
        id='1'>
<forwarded xmlns='urn:xmpp:forward:0'>
<message xmlns='jabber:client'
         from='Hamid@host.com/Miranda'
         to='ucf@host.com/MacBook-Pro-de-mac'
         xml:lang='en'
         type='chat'
         id='mir_93'>
<body>
Bonsoir
</body>
<active xmlns='http://jabber.org/protocol/chatstates'/>
</message>
<delay xmlns='urn:xmpp:delay'
       from='host.com'
       stamp='2015-08-12T17:18:32.410Z'/>
</forwarded>
</result>
<no-copy xmlns='urn:xmpp:hints'/>
</message>
......
<message xmlns='jabber:client'
         from='ucf@host.com'
         to='ucf@host.com/25051288531439402705425977'
         id='tAsdoULP8Ylk'>
<result xmlns='urn:xmpp:mam:0'
        id='10'>
<forwarded xmlns='urn:xmpp:forward:0'>
<message xmlns='jabber:client'
         from='ucf@host.com/MacBook-Pro-de-mac'
         type='chat'
         id='purple319700cb'
         to='sakina@host.com'>
<active xmlns='http://jabber.org/protocol/chatstates'/>
<body>
lkazmlaz
</body>
</message>
<delay xmlns='urn:xmpp:delay'
       from='host.com'
       stamp='2015-08-12T17:22:40.736Z'/>
</forwarded>
</result>
<no-copy xmlns='urn:xmpp:hints'/>
</message>
<message xmlns='jabber:client'
         from='ucf@host.com'
         to='ucf@host.com/25051288531439402705425977'
         id='/oTEv1nDrFpe'>
<result xmlns='urn:xmpp:mam:0'
        id='11'>
<forwarded xmlns='urn:xmpp:forward:0'>
<message xmlns='jabber:client'
         from='ucf@host.com/MacBook-Pro-de-mac'
         type='chat'
         id='purple319700ce'
         to='sakina@host.com'>
<active xmlns='http://jabber.org/protocol/chatstates'/>
<body>
mlkazdmkazd
</body>
</message>
<delay xmlns='urn:xmpp:delay'
       from='host.com'
       stamp='2015-08-12T17:22:42.192Z'/>
</forwarded>
</result>
<no-copy xmlns='urn:xmpp:hints'/>
</message>
....
<message xmlns='jabber:client'
         from='ucf@host.com'
         to='ucf@host.com/25051288531439402705425977'
         id='OM5RQco3jntq'>
<fin xmlns='urn:xmpp:mam:0'
     complete='true'>
<set xmlns='http://jabber.org/protocol/rsm'>
<first index='0'>
1
</first>
<last>
17
</last>
<count>
17
</count>
</set>
</fin>
<no-copy xmlns='urn:xmpp:hints'/>
</message>

**Comment by weiss** [comment]
JFTR, we figured it out with some additional debugging.  The code currently doesn't like the newlines/whitespace characters in:

    <value>
        juliet@example.com
    </value>

I.e., the `with` JID must be specified like this:

    <value>juliet@example.com</value>

I'll teach `mod_mam_mnesia` to ignore such whitespace.
