### ISSUE TITLE
Please remove intree libraries

### ISSUE THREAD

**Issue by darix** [processone/ejabberd-contrib#115]
after all the libraries got split out of ejabberd itself (p1_\* especially) it feels wrong to copy dependencies into ejabberd_auth_http/deps/ again. rebar can handle those deps for you no?

**Comment by badlop** [comment]
If it were possible to get dependencies automatically in contrib modules, it would be done.

Rebar of course supports it, but the code used to compile and copy contrib modules does not.

So there are two temporary solutions: only document the requirement, or also include the code. As it is only the module ejabberd_auth_http, and both its code and the depedencies change rarely, it seems acceptable for now.

**Comment by darix** [comment]
The fun starts when you ship that code and then later have to find out all copies of the code in your packages when one of those dependencies has a security issue.

**Comment by badlop** [comment]
Hi! It seems support for adding dependencies in contributions was implemented in https://github.com/processone/ejabberd/commit/9aa2d92d9048fb0fd7e1ec9d443aab8be7d33a8f

I've tested it in [ejabberd_observer_cli](https://github.com/processone/ejabberd-contrib/blob/master/ejabberd_observer_cli/rebar.config) and worked correctly.

So, now I've applied a similar solution to ejabberd_auth_http. It downloads the dependencies, compiles and installs them correctly. However, I am not able to test the actual functionality of ejabberd_auth_http itself.
