### ISSUE TITLE
mod_rest not working

### ISSUE THREAD

**Issue by timpisti** [processone/ejabberd-contrib#117]
Since the ejabberd 15.07 not installable, I set up ejabberd 15.06, I install the mod_rest with the enaberdctl module_install, and setup the config files.

After restarting ejabberd, the admin web interface running well, but the /rest endpoint seems to be not working, after I check the examples, (wget mostly), I get 404 in result.

**Comment by beherit** [comment]
I don't confirm - for me mod_rest working okey with ejabberd 15.06.

**Comment by timpisti** [comment]
Well, it's a temporary server with temporary installation - I can show you:

   - The module installed, and configured...
   - The web admin reachable and working - The config is working, the
   ejabberd is running
   - I try the PHP and WGET examples, they both result as 404

If there any suggestion about it, I really appriciated...

2015-08-23 20:55 GMT+02:00 Krzysztof Grochocki <notifications@github.com>:

> I don't confirm - for me mod_rest working okey with ejabberd 15.06.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processone/ejabberd-contrib/issues/117#issuecomment-133897512>
> .
>



-- 
┌─────────────────────profile─────────────────────────┐   ┌company┐
h t t p : / / f a c e b o o k . c o m / t i m p i s t i
<http://facebook.com/timpisti> @ <tif@4i.hu> 4 i . h u <http://4i.hu> / t i
f <http://4i.hu/tif>
 ─── + 36 20 417 3917 ─── telephone ─── └────────email────┼───────┘       │
                                                          └───────CV──────┘

**Comment by timpisti** [comment]
have a problem with mod_rest & ejabberd 15.06

My config:

  -.
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      # "/pub/archive": mod_http_fileserver
      "/rest": mod_rest
    web_admin: true
    http_poll: false
    http_bind: true
    ## register: true
    captcha: false

___

  mod_rest:
    allowed_ips:
      - "> {127,0,0,1} ."
    allowed_destinations:
      - "all"
    allowed_stanza_types:
      - "message"
      - "presence"
      - "iq"

___

wget http://127.0.0.1:5280/rest/ --server-response --post-data '<message to="admin@chat.medveklub.com" from="localhost/rest"><body>World</body></message>'

___

result:
--2015-08-24 12:20:05--  (try: 2)  http://127.0.0.1:5280/rest/
Connecting to 127.0.0.1:5280... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

I'm online with admin@chat.medveklub.com and didn't receive anything.

**Comment by beherit** [comment]
Try:
```
mod_rest:
  allowed_ips:
    - "127.0.0.1"
```

**Comment by timpisti** [comment]
I set the IP as you suggest. Still:
--2015-08-24 12:51:15--  (try: 3)  http://127.0.0.1:5280/rest/
Connecting to 127.0.0.1:5280... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

**Comment by beherit** [comment]
@timpisti I think You are not allowed to post data "World". For example add "incoming_s2s_number" to "access_commands" and then get information via mod_rest about incoming_s2s_number.

**Comment by timpisti** [comment]
Actually what I want to post a valid message stanza, only the XML part isn't rendered visibly by this page.

I try to send wget http://localhost:5280/rest/ --server-response --post-data ' < message to="admin@myserver" from="localhost/rest" > < body > World < /body > < /message >'
I copy-paste from the WGET example - without the spaces.
I only use the minimal config, I allow all stanza types, from localhost. Still no response.
