### ISSUE TITLE
mod_http_upload not reading config

### ISSUE THREAD

**Issue by kevinkk525** [processone/ejabberd-contrib#122]
I configured the mod_http_upload like this in my ejabberd.yml:
  mod_http_upload:
    docroot: "/etc/ejabberd/upload"
    put_url: "https://url:5444"
    get_url: "https://url:5444"

The mod works but it does not read the config, it uses its default settings instead. It does not upload to the docroot and not a single configuration entry is used.
Either I did something wrong (although following the readme of the mod) or this values are hardcoded. 

Maybe someone can help with this.

**Comment by weiss** [comment]
ejabberd-contrib modules are currently configured in files such as `$CONTRIB_MODULES_PATH/mod_http_upload/conf/mod_http_upload.yml` (where `$CONTRIB_MODULES_PATH` is something like `~ejabberd/.ejabberd-modules` by default).  If you'd prefer to use your `ejabberd.yml` instead, you can just delete the [existing `mod_http_upload.yml` file][1].   However, note that `ejabberdctl module_upgrade mod_http_upload` will reinstall the default file (no matter whether you removed or edited it).

This is a transitional thing that will probably change with ejabberd 15.09, so it's not documented.  Sorry about that.

[1]: https://github.com/processone/ejabberd-contrib/blob/master/mod_http_upload/conf/mod_http_upload.yml

**Comment by alexara** [comment]
> This is a transitional thing that will probably change with ejabberd 15.09, so it's not documented. Sorry about that.
That's good to know! Maby, just maby it should be documented, especially when the transitional thing takes so long.

**Comment by ismailmohammed** [comment]
Hi,

**Comment by ismailmohammed** [comment]
Hi, 
I have a requirement where i want to save the files which are shared in the chat to S3 server.
Now I am able to save them in the server where ejabbered installed.
By using service_url can we do this?
or we have write a external service for upload but what will be the Object we need to pass to that PUT url?

please help thanks in advance.

**Comment by weiss** [comment]
> By using service_url can we do this? or we have write a external service for upload but what will be the Object we need to pass to that PUT url?

You need to write an external service.  The `service_url` is just a mechanism to let your external service handle the PUT request.  When the client requests an upload slot, `mod_http_upload` will issue a GET request against your service (and hand over the file name/type/size) and your service returns the PUT URL the client should use. The details are described in [the documentation][1]:

> Whenever an upload slot request is accepted as per the access rule, a HTTP GET query with jid, name, size, and content_type fields is issued. In order to accept the request, the service must return an HTTP status code of 200 or 201 and two lines of text/plain output. The first line is forwarded to the XMPP client as the PUT URL, the second line as the GET URL. In order to reject the request, the service should return a status code of 402 (resource-constraint), 403 (not-allowed), or 413 (not-acceptable).

[1]: https://docs.ejabberd.im/admin/configuration/#mod-http-upload

**Comment by ismailmohammed** [comment]
Thanks for quick response.
Yes I have created a service, from client it's hitting to my service and I am getting JID/filename/type/size/. 
what I have to return from the service? PUT and GET URLs? and these PUT,GET URLs are from service?

before sending these URLs do I need to upload it to AWS server? but from client its HTTP GET request so not getting file/file stream to upload.

http_upload module from my ejabbered.yml file :

 mod_http_upload:
    ##docroot: "/opt/ejabberd/upload/"
    ##docroot: "C:\\ProgramData\\ejabberd\\upload"
    ##put_url: "http://@HOST@:5443/upload"
    max_size: infinity
    service_url: "http://localhost:5567/api/UserProfiles/JabberUpload"

Thanks in advance.

**Comment by ismailmohammed** [comment]
Thank you now I am able to send PUT URL for upload to S3 server and GET URL as an S3 path.
Now I am able to upload the image to S3 server. In receiver chat window we are able to see the image when I click it's redirecting to Image path instead of downloading the image. when i click the image +Ctrl then its downloading.

IS it correct to send S3 path as GET URL?

Thanks in advance

**Comment by weiss** [comment]
> what I have to return from the service? PUT and GET URLs?

Is [the documentation][1] unclear on this?  It says:

> In order to accept the request, the service must return an HTTP status code of 200 or 201 and two lines of text/plain output. The first line is forwarded to the XMPP client as the PUT URL, the second line as the GET URL. In order to reject the request, the service should return a status code of 402 (`resource-constraint`), 403 (`not-allowed`), or 413 (`not-acceptable`).

> and these PUT, GET URLs are from service?

The PUT URL would be provided by your service, the GET URL would be the AWS URL.

> before sending these URLs do I need to upload it to AWS server?

No, the service would wait until the client uploads the file using PUT URL and then forward the file to AWS.

There's [a Django project making use of this interface][2], it doesn't upload things to AWS but maybe it's useful as an example.

[1]: https://docs.ejabberd.im/admin/configuration/#mod-http-upload
[2]: https://github.com/mathiasertl/django-xmpp-http-upload

**Comment by weiss** [comment]
> In receiver chat window we are able to see the image when I click it's redirecting to Image path instead of downloading the image. when i click the image +Ctrl then its downloading.

Well this is obviously a client-side issue.

> IS it correct to send S3 path as GET URL?

Yes.

**Comment by coderRauthan** [comment]
@ismailmohammed Hi ,Can you please tell me how you accept the file in put_url service.Right Now the issue is:-
I have defined service_url in my mod_http_upload,On Uploading file the service url is getting called and I've successfully return put_url and get_url.

Then put_url is getting called but I am not able to accept file through it,I don't know the key which they will sent me,I've tried using inputStream and Multipart file,but it is constantly giving me errors,
Also I am not able to find any documentation how to accept file in put_url service.So can you help me out on this.
It would nice if you give put_url service snippet.

Thanks,
Best Regards,
Ankit

**Comment by weiss** [comment]
Note that the `service_url` interface is deprecated (recent ejabberd versions will log a warning if you use it), we're going to remove it sooner or later.  I'd recommend using the [`external_secret` mechanism][1] mechanism instead (ejabberd currently offers _Version 1_ only).

Regarding your actual question, HTTP upload clients are supposed to issue a normal [PUT request][2], so there shouldn't be anything XMPP-specific about this.

[1]: https://modules.prosody.im/mod_http_upload_external.html
[2]: https://tools.ietf.org/html/rfc7231#section-4.3.4

**Comment by ArtemisPseudo** [comment]
@ismailmohammed can you please share the repo for the s3 module/ service you have made. It is going to help a lot of people
