### ISSUE TITLE
incorrect file name while uploading with mod_http_upload and file name with russian characters

### ISSUE THREAD

**Issue by sespivak** [processone/ejabberd-contrib#124]
Incorrect file name while uploading with latest mod_http_upload and file name with russian characters.
If I upload for example file "б1.jpg", it uploads as "_1.jpg".
Tested in Gajim 0.16.4 and Conversations 1.6.10.

**Comment by weiss** [comment]
Yes, the module [replaces][1] any characters that don't match `[a-zA-Z0-9.-]` with an underscore to avoid any HTTP URL encoding issues.  The resulting file name (well, URL) is communicated back to the XMPP client (as per XEP-0363][2]), so this shouldn't be a problem.

[1]: https://github.com/processone/ejabberd-contrib/blob/a1fe316565b7543b7225f1da57bc1beb3f096c77/mod_http_upload/src/mod_http_upload.erl#L610
[2]:  http://xmpp.org/extensions/xep-0363.html
