### ISSUE TITLE
mod_http_upload: Stop serving GET requests when get_url is specified.

### ISSUE THREAD

**Issue by SafwatHalaby** [processone/ejabberd-contrib#126]
When `get_url` is specified, the internal web server should stop serving `GET` requests  because that becomes the job of an external web server.

**Comment by weiss** [comment]
No, the fact that `get_url` is specified doesn't indicate an external web server is used.

What's the actual problem you'd like to solve?

**Comment by SafwatHalaby** [comment]
The actual problem is that I'm using an external web server for serving the files, but my files are available from two different servers, which is redundant.

For instance, when I upload `x.jpg`, the image becomes available at the following URLS:
`https://example.com:5443/....etc..../x.jpg`  < Internal ejabberd webserver
`https://example.com:5444/....etc..../x.jpg`  < Nginx

>No, the fact that get_url is specified doesn't indicate an external web server is used.

Well, then maybe there should be another option, such as `disable_get_requests`.

**Comment by SafwatHalaby** [comment]
The most general solution would be changing ejabberd_http's `request_handlers` code and making it filter by request type (PUT / GET / etc) and not just by PATH.

**Comment by SafwatHalaby** [comment]
It should be noted that the receiving contact receives `https://example.com:5444/....etc..../x.jpg`, so everything is working as expected, except that I'd rather disabling the first url.

**Comment by weiss** [comment]
> For instance, when I upload `x.jpg`, the image becomes available at the following URLS:
> `https://example.com:5443/....etc..../x.jpg`  < Internal ejabberd webserver
> `https://example.com:5444/....etc..../x.jpg`  < Nginx

Hmm, I think that setup will be quite uncommon.  Most users who let Nginx serve the GET requests would probably just let ejabberd listen on localhost and have Nginx proxy the PUT requests to ejabberd.

> The most general solution would be changing ejabberd_http's request_handlers code and making it filter by request type (PUT / GET / etc) and not just by PATH.

Yes, that would be a feature request against [ejabberd][1] then.

I'll close this issue for the moment (but feel free to add comments).

[1]: https://github.com/processone/ejabberd/issues/new

**Comment by SafwatHalaby** [comment]
>Yes, that would be a feature request against ejabberd then.
> I'll close this issue for the moment (but feel free to add comments).

Fair enough. And thanks for the setup suggestion.
What about the `disable_get_requests` proposal?

**Comment by weiss** [comment]
> And thanks for the setup suggestion.

Maybe I should add example configuration snippets for Nginx and Apache to the repository ...

> What about the `disable_get_requests` proposal?

If this feature is useful, I think it should not be implemented in individual request handler modules but in `ejabberd_http`, as you suggested above.

**Comment by SafwatHalaby** [comment]
URL dupes aside, is there any utility in the proxy method in comparison to my uncommon method of two servers?

**Comment by weiss** [comment]
> URL dupes aside, is there any utility in the proxy method in comparison to my uncommon method of two servers?

I would've thought most admins will prefer running a single HTTP(S) server listening on a standard port.  And there might be some value in not exposing `ejabberd_http` listeners directly to the outside world (Nginx will be better at handling bogus/malicious requests, for example).

I've put together a small [configuration snippet for Nginx][1], FWIW.

[1]: https://userpage.fu-berlin.de/holger/archive/nginx-uload.conf

**Comment by SafwatHalaby** [comment]
Thanks! 

- At line 15, I think you meant `limit_except GET PUT {`. [SO Reference here](http://stackoverflow.com/questions/8591600/nginx-proxy-pass-based-on-whether-request-method-is-post-put-or-delete).

- Consider adding an [HPKP](https://en.m.wikipedia.org/wiki/HTTP_Public_Key_Pinning) header.

**Comment by weiss** [comment]
> At line 15, I think you meant `limit_except GET PUT {`. [SO Reference here](http://stackoverflow.com/questions/8591600/nginx-proxy-pass-based-on-whether-request-method-is-post-put-or-delete).

No, that

    limit_except GET {
        proxy_pass http://localhost:5444;
    }

block is supposed to Nginx to forward all requests except for GET (and HEAD) to ejabberd.  With `limit_except GET PUT`, Nginx would handle PUT requests itself instead of handing them over to `mod_http_upload`, and that won't work of course.

> Consider adding an [HPKP](https://en.m.wikipedia.org/wiki/HTTP_Public_Key_Pinning) header.

Hrm yes I could, though I was also unsure when adding that `Strict-Transport-Security` header because both are somewhat outside the scope of showing the specifics of using Nginx as a frontend to `mod_http_upload`.

**Comment by SafwatHalaby** [comment]
Sorry, I meant: `limit_except GET HEAD {`, are you saying `HEAD` is added implicitly if omitted?

**Comment by weiss** [comment]
> are you saying HEAD is added implicitly if omitted?

Yes, according to the [Nginx docs][1]: "Allowing the GET method makes the HEAD method also allowed."

[1]: http://nginx.org/en/docs/http/ngx_http_core_module.html#limit_except
