### ISSUE TITLE
mod_http_upload: SNI support - for multimple TLS domains on single IP and port

### ISSUE THREAD

**Issue by jkufner** [processone/ejabberd-contrib#127]
Curently only one certfile can be configured to be used. But when server is running multiple domains on single IP address, it makes configuration a bit complicated, since each domain must have its own instance of mod_http_upload on dedicated port.

It would be much more practical if mod_http_upload supports SNI and respects global `host_config`/`domain_certfile` options.

**Comment by mathiasertl** [comment]
If it's an option to you, having a dedicated upload service with https://github.com/mathiasertl/django-xmpp-http-upload would have your webserver provide SNI support (as well as OCSP stapling etc.)

**Comment by weiss** [comment]
Another alternative would be to proxy the HTTPS requests [using a proper web server such as Nginx][1] or Apache.

Anyway, `mod_http_upload` doesn't actually speak HTTP, it just handles requests that are accepted by `ejabberd_http`.  So if SNI support is really required as a built-in feature, that would have to be submitted as a feature request against ejabberd core.

[1]: https://userpage.fu-berlin.de/holger/archive/nginx-upload.conf

**Comment by jkufner** [comment]
Thank you for a quick reply. I will file a feature request in ejabberd_http. Using proper web server for upload looks nice too, when web server is running on the same host as ejabberd.

**Comment by weiss** [comment]
Well you can also proxy requests to remote hosts :-)

**Comment by jkufner** [comment]
Yes, but then a secure tunnel to the remote host is needed, so it is not as elegant solution as it could be.
