### ISSUE TITLE
mod_http_upload: original filename should be preserved

### ISSUE THREAD

**Issue by jkufner** [processone/ejabberd-contrib#128]
When sharing a photo via http upload, a link like this is created:

    https://example.com/upload/RANDOM-STUFF/ANOTHER-RANDOM-STUFF.jpg

So later, when file is downloaded, user ends up with file `ANOTHER-RANDOM-STUFF.jpg`. It would be much better if original filename is preserverd, so link would look like this:

    https://example.com/upload/RANDOM-STUFF/ANOTHER-RANDOM-STUFF/original_name.jpg

Then downloaded file would be named `original_name.jpg`, which looks much better.

**Comment by mathiasertl** [comment]
Have you tried sharing a file with Gajim? AFAIK conversations randomizes the filename, this does not happen in mod_http_upload.

**Comment by jkufner** [comment]
Good point. So it is bug in Conversations, not in server. Thank you.
