### ISSUE TITLE
mod_rest wont start on ejabberd 13

### ISSUE THREAD

**Issue by nstiac** [processone/ejabberd-contrib#13]
Hi, I've tried everything I can think of.. I've even recompiled ejabber, erlang, mod_rest, and doublechekced copied the mod_rest.beam to /lib/ejabberd/ebin to no avail:

when loaded as global module:

22:50:23.595 [critical] Problem starting the module mod_rest for host <<"localhost">>
 options: []
 error: undef
[{p1_logger,debug_msg,[mod_rest,43,"Starting: ~p ~p",[<<"localhost">>,[]]],[]},
 {mod_rest,start,2,[{file,"src/mod_rest.erl"},{line,43}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,70}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1323}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,67}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,269}]}]
22:50:23.595 [critical] ejabberd initialization was aborted because a module start failed.

I'm running erlang 16b03-1 and ejabberd & ejabberd-contrib from master git

Also, when not loaded on global modules ie. only on vhosts. same thing... wont load + crashes:

23:00:11.051 [info] Application ejabberd started on node ejabberd@localhost
23:00:19.843 [info](#Port<0.6761) Accepted connection {{ip_omitted},49516} -> {{ip_omitted},5285}
23:00:19.844 [debug] S: [{[<<"rest">>],mod_rest}]
23:00:19.845 [info] started: {gen_tcp,#Port<0.6761>}
23:00:19.845 [debug](#Port<0.6761) http query: 'POST' /rest/
23:00:19.845 [debug] client data: <<"<message to=\"fulljid_omitted\" from=\"localhost/rest\"><body>World</body></message>">>
23:00:19.845 [debug] [<<"rest">>] matches [<<"rest">>]
23:00:19.845 [debug] [{'Content-Length',<<"90">>},{'Content-Type',<<"application/x-www-form-urlencoded">>},{'Connection',<<"Keep-Alive">>},{'Host',<<"localhost:5285">>},{'Accept',<<"_/_">>},{'User-Agent',<<"Wget/1.11.4 Red Hat modified">>}]

=CRASH REPORT==== 1-Mar-2014::23:00:19 ===
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.661.0>
    registered_name: []
    exception throw: {module_must_be_started_in_vhost,mod_rest,
                         <<"localhost">>}
      in function  mod_rest:try_get_option/3 (src/mod_rest.erl, line 112)
      in call from mod_rest:check_member_option/3 (src/mod_rest.erl, line 127)
      in call from mod_rest:process/2 (src/mod_rest.erl, line 56)
      in call from ejabberd_http:process/2 (src/ejabberd_http.erl, line 356)
      in call from ejabberd_http:process_request/1 (src/ejabberd_http.erl, line 462)
      in call from ejabberd_http:process_header/2 (src/ejabberd_http.erl, line 288)
      in call from ejabberd_http:receive_headers/1 (src/ejabberd_http.erl, line 182)
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.40.0>]
    messages: []
    links: [<0.339.0>,#Port<0.6761>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 3569
  neighbours:

No idea how to fix it!

**Comment by vikash002** [comment]
getting error please tell me how to fix it {mod_rest,start,2,[{file,"src/mod_rest.erl"},{line,42}]}
