### ISSUE TITLE
mod_admin_extra get_vcard and set_vcard not working

### ISSUE THREAD

**Issue by GaneshjiD** [processone/ejabberd-contrib#130]
I have installed ejabberd15.07 (binary installer) on windows7.
When i try to call the get_vcard facing the same problem
Problem 'error {badmatch,[]}' occurred executing the command. Stacktrace: [{mod_admin_extra,set_vcard_content,4, [{file,"src/mod_admin_extra.erl"},{line,1019}]}, {ejabberd_ctl,call_command,3, [{file,"src/ejabberd_ctl.erl"},{line,294}]}, {ejabberd_ctl,try_call_command,3, [{file,"src/ejabberd_ctl.erl"},{line,270}]}, {ejabberd_ctl,process2,3, [{file,"src/ejabberd_ctl.erl"},{line,219}]}, {ejabberd_ctl,process,1, [{file,"src/ejabberd_ctl.erl"},{line,204}]}, {rpc,'handle_call_call/6-fun-0',5, [{file,"rpc.erl"},{line,203}]}]

but in my installation i am not getting the .erl file to det the patch as given above. There are only .hrl files. Please help me out with this issue

**Comment by badlop** [comment]
Are you really using 15.07? That version already includes the fixes mentioned in https://github.com/processone/ejabberd-contrib/issues/21 and I've tested that version, it works correctly for me:
```
$ ejabberdctl get_vcard user666666 localhost NICKNAME
Error: error_no_vcard_found

$ ejabberdctl get_vcard user1 localhost NICKNAMEEEEEEEEEEE
Error: error_no_value_found_in_vcard

$ ejabberdctl get_vcard user1 localhost NICKNAME
User1Rules
```

**Comment by GaneshjiD** [comment]
I have installed ejabberd15.07 on 'windows localhost'  inside the folder named 'newjab'.
I am running the using cmd the following command..

C:\xampp\htdocs\newjab\bin>ejabberdctl get_vcard admin ajm-inspiron-PC admin
Problem 'error {badmatch,[]}' occurred executing the command.
Stacktrace: [{mod_admin_extra,get_vcard_content,3,
                              [{file,"src/mod_admin_extra.erl"},{line,890}]},
             {mod_admin_extra,get_vcard,3,
                              [{file,"src/mod_admin_extra.erl"},{line,863}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,320}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,292}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,268}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,217}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,202}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,205}]}]
------------------------
THis is the version of ejabberd
C:\xampp\htdocs\newjab\bin>ejabberdctl status
The node ejabberd@localhost is started with status: started
ejabberd 15.07 is running in that node

-------------------------------
Is my way of using ejabberdctl command is wrong ot what??? Please help me out...
Rest commands like getting 'roaser' and setting 'roaster' are working fine

**Comment by GaneshjiD** [comment]
i have downloaded the binar installation of ejabberd 15.07.... and then installed it on  localhost.. Is the way of installing and running ejabberd is correct???

**Comment by GaneshjiD** [comment]
I have tried https://github.com/processone/ejabberd for installation but it has given installation for . Compile and install on *nix systems... how to use it for windows7???

**Comment by GaneshjiD** [comment]
When i installed with binary installer... the folder structure is
-backup
-bin
-doc
-lib
    -asn1-3.0.4
    -asn1-3.0.4
   -asn1-3.0.4
   -asn1-3.0.4
   -asn1-3.0.4
   -asn1-3.0.4
   -asn1-3.0.4
   -asn1-3.0.4

-logs
-uninstall

**Comment by GaneshjiD** [comment]
This is the error while creating room...
------
C:\xampp\htdocs\newjab\bin>ejabberdctl create_room new conference.ajm-inspiron-P
C ajm-inspiron-PC
Problem 'exit {noproc,
                  {gen_server,call,
                      ['ejabberd_mod_muc_sup_ajm-inspiron-PC',
                       {start_child,
                           [<<"conference.ajm-inspiron-PC">>,
                            <<"ajm-inspiron-PC">>,
                            {all,all,none,all},
                            <<"new">>,20,none,[]]},
                       infinity]}}' occurred executing the command.
Stacktrace: [{gen_server,call,3,[{file,"gen_server.erl"},{line,190}]},
             {mod_muc_admin,create_room,3,
                            [{file,"src/mod_muc_admin.erl"},{line,420}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,320}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,292}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,268}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,217}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,202}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,205}]}]
------------------------------
