### ISSUE TITLE
mod_rest: Authentication via username+password

### ISSUE THREAD

**Issue by cweiske** [processone/ejabberd-contrib#133]
I'd like to use `mod_rest` to post messages from other servers (e.g. my home server) to my XMPP server, but I do know their IPs in advance (or their IP changes).

So to not leave the whole server open to the world, I would like to be able to force some way of authentication before being able to send messages.

**Comment by beherit** [comment]
Such authentication is already added - just read mod documentation ;)

**Comment by cweiske** [comment]
Are you referring to https://github.com/processone/ejabberd-contrib/tree/master/mod_rest "EXAMPLE AUTH COMMAND WITH WGET"?

Does this mean I have to do an HTTP request for authentication *before* sending the send-message request?

If yes, is there a session created somehow? How to I transfer this information to the second request?

**Comment by beherit** [comment]
Does it mean You have to add authentication in every HTTP request - there isn't any session caching.

**Comment by cweiske** [comment]
Could you please give a configuration example to only allow messages from authenticated users? I fail to find that in the documentation.
