### ISSUE TITLE
mod_rest: HTML-IM messages get rejected

### ISSUE THREAD

**Issue by cweiske** [processone/ejabberd-contrib#134]
I'm using ejabberd 15.09 with `mod_rest`. There are no restrictions whatsoever configured for `mod_rest`.

Sending a normal message works fine:

    $ curl http://example.org:5280/rest/ --data '<message to="cweiske@example.org" from="cweiske@example.org"><body>World</body></message>'

Sending a HTML-IM message fails:

    $ curl http://example.org:5280/rest/ --data '<message type="chat" to="cweiske@example.org" from="cweiske@example.org"><body>World</body><html xmlns='http://jabber.org/protocol/xhtml-im'><body xmlns='http://www.w3.org/1999/xhtml'><p><strong>Hello</strong> World!</p></body></html></message>'
    Error: REST request is rejected by service.

**Comment by badlop** [comment]
Using 15.09 or 15.10 (compiled from git), with this config:
```
listen:
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/pub/muclogs": mod_muc_log_http
      "/rest": mod_rest

modules:
  mod_rest:
    allowed_ips:
      - "127.0.0.1"
```

Sending this request:
```
$ curl http://localhost:5280/rest/ --data '<message to="user1@localhost" from="cweiske@example.org"><body>World</body></message>'
Ok
```

This is logged by ejabberd:
```
18:26:03.743 [info] (#Port<0.7590>) Accepted connection 127.0.0.1:33829 -> 127.0.0.1:5280
18:26:03.743 [info] started: {gen_tcp,#Port<0.7590>}
18:26:03.745 [info] Got valid request from cweiske@example.org
with IP {{127,0,0,1},33829}
to user1@localhost:
{xmlel,<<"message">>,[{<<"to">>,<<"user1@localhost">>},{<<"from">>,<<"cweiske@example.org">>}],[{xmlel,<<"body">>,[],[{xmlcdata,<<"World">>}]}]}
```
and user1, which is logged, receives the stanza immediately.

Do you have any other clue what may be different from your setup and mine? If no idea, then please share your full config file.

**Comment by cweiske** [comment]
@badlop - as I said, sending normal messages (without HTML) works fine. I showed this in my example, you confirmed this in your example.

What does not work is sending HTML messages.

**Comment by badlop** [comment]
Ah, you are right: I didn't test yet sending HTML.

The problem in your second call is that you use simple quotes like ' in the HTML elements, and those get removed when they arrive to ejabberd. Try using double quotes like ", as in the other stanza attributes:
```
$ curl http://localhost:5280/rest/ --data '<message type="chat" to="user1@localhost" 
 from="cweiske@example.org"><body>World</body><html
 xmlns="http://jabber.org/protocol/xhtml-im"><body
 xmlns="http://www.w3.org/1999/xhtml"><p><strong>Hello</strong>
 World!</p></body></html></message>'
Ok
```
The client receives:
```
<message from='cweiske@example.org'
	to='user1@localhost'
	type='chat'>
  <body>World</body>
  <html xmlns='http://jabber.org/protocol/xhtml-im'>
    <body xmlns='http://www.w3.org/1999/xhtml'>
      <p>
        <strong>Hello</strong>
      </p>
    </body>
  </html>
</message>
```

**Comment by cweiske** [comment]
That was it! Thank you, I wasn't aware that single quotes also cause issue with mod_rest.

**Comment by weiss** [comment]
> I wasn't aware that single quotes also cause issue with mod_rest.

They don't, but the way you quoted your stanza, your shell removes them before handing the string over to `curl`.

**Comment by cweiske** [comment]
Oh my, I really didn't see this. Sorry :/
