### ISSUE TITLE
mod_http_upload compilation failed

### ISSUE THREAD

**Issue by Biergartenparadoxon** [processone/ejabberd-contrib#135]
Installing mod_http_upload failed for me

$ ejabberdctl module_install mod_http_upload
/usr/lib/ejabberd/include/ns.hrl:155: redefining macro 'NS_HTTP_UPLOAD'
/usr/lib/ejabberd/include/ns.hrl:156: redefining macro 'NS_HTTP_UPLOAD_OLD'
Error: {compilation_failed,"src/mod_http_upload.erl"}

Commenting those both lines in /usr/lib/ejabberd/include/ns.hrl fixed it for me.
I don't know if this is the right way and if it's a general problem or just at my machine...

Ejabberd version is 15.10-1
Greets

**Comment by weiss** [comment]
ejabberd 15.10 [ships][1] `mod_http_upload`, so there's no need to compile the module from `ejabberd-contrib` (and that's the reason for that error message).

[1]: https://blog.process-one.net/ejabberd-15-10-http-upload-metrics-and-performance/

**Comment by Biergartenparadoxon** [comment]
Hm then I must have missed somewhere something big b/c I wasn't able to activate the module beforehand... maybe I was really blind somewhere
Thanks & Greets

**Comment by SafwatHalaby** [comment]
@weiss Perhaps `mod_http_upload` should be removed from contrib to avoid further confusion. This also applies to the other mods that were previous contrib but now aren't, such as `mod_mam`.

**Comment by weiss** [comment]
> Hm then I must have missed somewhere something big b/c I wasn't able to activate the module beforehand

Just ask on the [mailing list][1] or in the [conference room][2] if you still have trouble.

> Perhaps `mod_http_upload` should be removed from contrib to avoid further confusion.

At some point, sure.  Right now we'd like to still allow users of older ejabberd releases to install `mod_http_upload`.

> This also applies to the other mods that were previously contrib but now aren't, such as `mod_mam`.

The `mod_mam_mnesia` module available in the `ejabberd-contrib` repository provides a different feature set than the MAM module shipped with ejabberd.  I'd like to merge a few of the `mod_mam_mnesia` things into ejabberd's `mod_mam` before removing `mod_mam_mnesia`.
