### ISSUE TITLE
mod_rest not persisting messages

### ISSUE THREAD

**Issue by visox** [processone/ejabberd-contrib#136]
We are using mod_rest as an external entry and it works but the messages aren't stored in history.

I can use a client to retrieve old messages but the once that have been (not) inserted by mod_rest are missing.

If i use it just for live chat i have the messages they just aren't persistent. (like if i use a second client for the same user i see which messages are missing)

I can find messages in `offline_msg.DAT` in `/var/lib/ejabberd/`, messages from mod_rest are missing.

not sure if this counts as an issue, maybe someone can suggest a workaround 

we are using ejabberd 15.09.12
and latest modules

thanks

**Comment by badlop** [comment]
I don't see the issue using ejabberd 15.10 and latest mod_rest.

I send stanzas like this with a desktop Jabber client:
```<message to="user1@localhost"><body>World</body></message>```
and also stanzas using mod_rest, this way:
```
$ lynx http://localhost:5280/rest/ -mime_header -post_data
<message to="user1@localhost" from="localhost/rest"><body>World</body></message>
---
```

In both cases the stanzas are received by user1. If user1 is disconnected, both stanzas are stored by mod_offline. I can see them using WebAdmin, in the URL: http://localhost:5280/admin/server/localhost/user/user1/queue/

**Comment by visox** [comment]
Thx for trying, i will try 15.10 and will see if the messages are stored.

**Comment by visox** [comment]
Ok now i see that i didn't understand how it was suppose to work.
