### ISSUE TITLE
mod_http_upload: Mention that its in core now, official documentation on docs.ejabberd.im

### ISSUE THREAD

**Issue by Quintus** [processone/ejabberd-contrib#137]
Hi everyone,

mod_http_upload has been [included into ejabberd core now with release 15.10](http://lists.jabber.ru/pipermail/ejabberd/2015-October/008848.html). Would be nice if this was mentioned in the mod_http_upload README here in the repository so people are made aware of this.

Also, since there is no documentation of mod_http_upload [on the official documentation page](http://docs.ejabberd.im/admin/guide/configuration/), can I assume the documentation of mod_http_upload here also applies to the module in ejabberd core?

Greetings
Marvin

**Comment by weiss** [comment]
> mod_http_upload has been [included into ejabberd core now with release 15.10](http://lists.jabber.ru/pipermail/ejabberd/2015-October/008848.html). Would be nice if this was mentioned in the mod_http_upload README here in the repository so people are made aware of this.

[Done][1].

> Also, since there is no documentation of mod_http_upload [on the official documentation page](http://docs.ejabberd.im/admin/guide/configuration/), can I assume the documentation of mod_http_upload here also applies to the module in ejabberd core?

Yes, mostly; but the module is now also documented [in the official guide][2].

[1]: https://github.com/processone/ejabberd-contrib/commit/195daf9fa114f4a30c79cd6d09183a54fa4cc7d1
[2]: http://docs.ejabberd.im/admin/guide/configuration/#modhttpupload
