### ISSUE TITLE
getting error to run ejabberd please fix it

### ISSUE THREAD

**Issue by vikash002** [processone/ejabberd-contrib#144]
```
2016-01-18 19:35:10.837 [critical] <0.1673.0>@gen_mod:start_module:106
 Problem starting the module mod_rest for host <<"localhost">> 
options: []
error: undef
[{p1_logger,debug_msg,
           [mod_rest,42,"Starting: ~p ~p",
            [<<"localhost">>,
             []]],
           []},
{mod_rest,start,2,[{file,"src/mod_rest.erl"},{line,42}]},
{gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,98}]},
{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
{ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,74}]},
{application_master,start_it_old,4,
                    [{file,"application_master.erl"},{line,273}]}]
2016-01-18 19:35:10.837 [critical] <0.1673.0>@gen_mod:start_module:111
 ejabberd initialization was aborted because a module start failed.
```

**Comment by badlop** [comment]
If I remember correctly, the problem here is related to the way mod_rest is compiled. How do you compile mod_rest?

**Comment by vikash002** [comment]
erl -pa . -pz ebin -make

Emakefile : 
{'src/mod_rest', [{outdir, "ebin"},{i,"/lib/ejabberd/include/"}]}.

**Comment by badlop** [comment]
That way, the compiler uses a logging module that later isn't available in your ejabberd installation (p1_logger).

The dirty solution is to edit the mod_rest.erl source code and remove the ?DEBUG and ?INFO_MSG lines.

The proper solution is to let ejabberd compile the module, as described in https://github.com/processone/ejabberd-contrib
