### ISSUE TITLE
mod_http_offline not compiling with LAGER

### ISSUE THREAD

**Issue by twais** [processone/ejabberd-contrib#145]
I have recently upgraded to ejabberd version 15.11. All modules are working apart from the mod_http_offline. I am able to not able to successfully compile the module as I get an error 
```
include/logger.hrl:21: redefining macro 'LAGER'
ERROR: compile failed while processing ejabberd: rebar_abort
make: *** [src] Error 1
```

Below is my logger.hrl
```
%%start
-define(PRINT(Format, Args), io:format(Format, Args)).
-define(LAGER,1).
-ifdef(LAGER).
-compile([{parse_transform, lager_transform}]).

-define(DEBUG(Format, Args),
    lager:debug(Format, Args)).

-define(INFO_MSG(Format, Args),
    lager:info(Format, Args)).

-define(WARNING_MSG(Format, Args),
    lager:warning(Format, Args)).

-define(ERROR_MSG(Format, Args),
    lager:error(Format, Args)).

-define(CRITICAL_MSG(Format, Args),
    lager:critical(Format, Args)).

-else.

-define(DEBUG(Format, Args),
    p1_logger:debug_msg(?MODULE, ?LINE, Format, Args)).

-define(INFO_MSG(Format, Args),
    p1_logger:info_msg(?MODULE, ?LINE, Format, Args)).

-define(WARNING_MSG(Format, Args),
    p1_logger:warning_msg(?MODULE, ?LINE, Format, Args)).

-define(ERROR_MSG(Format, Args),
    p1_logger:error_msg(?MODULE, ?LINE, Format, Args)).

-define(CRITICAL_MSG(Format, Args),
    p1_logger:critical_msg(?MODULE, ?LINE, Format, Args)).
-endif.
%%end
```
Please assist

**Comment by badlop** [comment]
Do you refer to this one? https://github.com/raelmax/mod_http_offline ? How did you compile it?

**Comment by twais** [comment]
Yes, I am referring to that. I copied the erl file to my src folder in ejabberd source, then did configure and make. The beam file was generated to the ebin folder

**Comment by badlop** [comment]
Looking at the code, I can't compile it because it has an undefined variable. I copied the file to an ejabberd source dir where I have already compiled ejabberd before:
```
$ make
/usr/lib/erlang/bin/escript rebar skip_deps=true compile
==> rel (compile)
==> ejabberd (compile)
src/mod_http_offline.erl:31: variable 'SubType' is unbound
ERROR: compile failed while processing /f/jabber/p1/git/ejabberd: rebar_abort
Makefile:93: recipe for target 'src' failed
make: *** [src] Error 1
```

**Comment by twais** [comment]
Hi badlop,
Try this. I have only kept the variables I need. The error I am getting is "include/logger.hrl:21: redefining macro 'LAGER'
ERROR: compile failed while processing /path/to/ejabberd: rebar_abort"

%%start
%% name of module must match file name
-module(mod_http_offline).
 
-author("Earl The Squirrel").
 
%% Every ejabberd module implements the gen_mod behavior
%% The gen_mod behavior requires two functions: start/2 and stop/1
-behaviour(gen_mod).
 
%% public methods for this module
-export([start/2, stop/1, create_message/3]).
 
%% included for writing to ejabberd log file
-include("ejabberd.hrl").
 
%% ejabberd functions for JID manipulation called jlib.
-include("jlib.hrl").

%%-include("logger.hrl").
 
start(_Host, _Opt) ->
        %%?INFO_MSG("mod_http_offline loading", []),
        inets:start(),
        %%?INFO_MSG("HTTP client started", []),
        post_offline_message("testFrom", "testTo", "testBody"),
        ejabberd_hooks:add(offline_message_hook, _Host, ?MODULE, create_message, 50).  
 
 
 
stop (_Host) ->
        %%%?INFO_MSG("stopping mod_http_offline", []),
        ejabberd_hooks:delete(offline_message_hook, _Host, ?MODULE, create_message, 50).
 
 
 
create_message(_From, _To, Packet) ->
        %%Type = xml:get_tag_attr_s("type", Packet),
        FromS = xml:get_path_s(Packet, [{elem, "FromUser"}, cdata]),
        ToS = xml:get_tag_attr_s("to", Packet),
        Body = xml:get_path_s(Packet, [{elem, "body"}, cdata]),
        post_offline_message(FromS, ToS, Body).
 
 
 
post_offline_message(From, To, Body) ->
         %%?INFO_MSG("Posting From ~p To ~p Body ~p~n",[From, To, Body]),
         httpc:request(post, {"http://172.10.3.21/chat/offline/offlinemsg.php",[],
         "application/x-www-form-urlencoded",
         lists:concat(["From=", From,"&To=", To,"&Body=", Body])}, [], []).
         %%?INFO_MSG("post request sent", []).

%%end

**Comment by badlop** [comment]
It compiles correctly for me with ejabberd 16.01. In recent versions, p1_logger was replaced by lager. If you compiled ejabberd 15.11 from source code, try to compile it with lager instead of logger, like this:
```
./configure --enable-lager
make clean
make
```

**Comment by twais** [comment]
Hi badlop, I am now getting error

@gen_mod:start_module:106 Problem starting the module mod_http_offline 
for host <<"host">>
 options: []
 error: undef
[{ejabberd_logger,info_msg,
                  [mod_http_offline,20,"mod_http_offline loading",[]],
                  []},
 {mod_http_offline,start,2,[{file,"src/mod_http_offline.erl"},
 {line,20}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,98}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,73}]},
 {application_master,start_it_old,4,
 [{file,"application_master.erl"},{line,272}]}]

Note: I am compiling from ejabberd source

**Comment by badlop** [comment]
You can try
```
./rebar get-deps
make
```

But in any case, the problem you have is related to the logging mechanism. If you don't need that, you can simply comment all the INFO_MSG lines. Someday when you update to some ejabberd 16.xx version, you can enable again those logging lines.
