### ISSUE TITLE
undefined macro 'NS_THUMBS_1' during module_install

### ISSUE THREAD

**Issue by ethoms** [processone/ejabberd-contrib#146]
This is not a bug report, just trying to save others time by posting a solution.

The problem is due to being on an older ejabberd version. I am running 15.07 as it is the latest in FreeBSD ports at this time. The macro definition for "NS_THUMBS_1 is missing in older versions.

To fix, edit mod_http_upload.erl (e.g. vi ~/.ejabberd-modules/sources/ejabberd-contrib/mod_http_upload/src/mod_http_upload.erl) and replace "?NS_THUMBS_1" with "<<"urn:xmpp:thumbs:1">>". Now it should module_install successfully.

**Comment by badlop** [comment]
In fact, other NS definitions are there, but this one is not, so it's missing. That prblem only affects a pair of old versions... but it can be fixed anyway, so let's fix it. Thanks for reporting :)
