### ISSUE TITLE
mod_http_upload: put_url not respected

### ISSUE THREAD

**Issue by ethoms** [processone/ejabberd-contrib#147]
I'm having some problems with our company server that has multiple domains that share services. ON my personal domain/server it's working fine because all hostnames resolve to the same IP.

In my ejabberd.yml I have:

    listen:
    ...
    - 
      port: 5443
      module: ejabberd_http
      tls: true
      certfile: "/usr/local/etc/ssl/wildcard_example_com.key+crt+ca-chain.pem"
      request_handlers:
        "": mod_http_upload

    ...
    modules:
    ...
    mod_http_upload:
      docroot: "/mod_http_upload-docroot"
      put_url: "https://xmpp.example.com:5443"
      get_url: "https://xmpp.example.com:5443"
    mod_http_upload_quota:
      max_days: 100
    ...

However, the URL I get it Gajim, both when sending or receiving from Converstaions is using the URL http://example.com:5444 (notice the differnt port).

From Gajim chat window:

    [06:24:01 PM] bob: hi there
    [06:24:17 PM] bill: http://example.com:5444/5284fa88f57f1e24f2c5994801dece658d3d2426/ximPseaJ8b3BcFckLSfD6s7wwCmtLNRMNgXk28Ke/ffc5d2cd-2322-4742-966d-9c827b62d47f.jpg URL: http://example.com:5444/5284fa88f57f1e24f2c5994801dece658d3d2426/ximPseaJ8b3BcFckLSfD6s7wwCmtLNRMNgXk28Ke/ffc5d2cd-2322-4742-966d-9c827b62d47f.jpg

**Comment by ethoms** [comment]
So when "example.com" resolves to a differnet IP than "xmpp.example.com", it becomes a problem.

**Comment by ethoms** [comment]
If fact, going the other way, from Gajim to Conversations, the URL of the download is http://sample.org:5444/...<random>/...<random>.jpg.

The contact in Gajim is bob@sample.org, the user in Conversations is bill@example.com.

So, it's as if mod_http_upload is not using put_url or getr_url at all. I wonder if I need to do a per-domain module config, currently I'm using the global "modules:" declarations, despite using 2 domains, each configured in a domain specific "host_config:". I'll try and report back. All my other modules are configured gloabally without issue.

**Comment by ethoms** [comment]
Nope, even using a per-domain module config via "append_host_config", it still seems to ignore put_url.

**Comment by ethoms** [comment]
Update: so I just noticed the mod_http_upload.yml in my installed modules directory. This is my first use of a module from contrib, so maybe I don't understand how it's done. I assumed I had to add the new settings to ejabberd.yml. It appears I need to add it to mod_http_upload.yml instead.

It's working now that I use the separate conf file, the URl is now http://xmpp.example.com:5444 (I decided to use port 5444 and no tls/ssl for now).

**Comment by badlop** [comment]
Hi, looking at ejabberd-contrib's README.md, it says:
```
- Run `ejabberdctl module_install <module>` to get the source code and to
  compile and install the `beam` file into ejabberd's module search path.
  This path is either `~/.ejabberd-modules` or defined by the
  `CONTRIB_MODULES_PATH` setting in `ejabberdctl.cfg`.

- Edit the configuration file provided in the `conf` directory of the
  installed module and update it to your needs. Then apply the changes to
  your main ejabberd configuration. In a future release, ejabberd will
  automatically add this file to its runtime configuration without
  changes.
```

In practice, this means that you get in ~/.ejabberd-modules/mod_http_upload/conf a basic module configuration file, where you can set the specific module options. The README explanation is obsolete, as you noticed those options nowadays overwrite whatever you put in the main ejabberd.yml right?

**Comment by ethoms** [comment]
Yes, you are correct, the module config taken effect over the global config.

I appologise for not reading the contrib README. I went straight to the mod_http_upload README.

Consider this closed as a PICNIC (problem in chair, not in computer).

**Comment by weiss** [comment]
Just for the record, with ejabberd 15.09 and newer, there's actually two places that take precedence over the global `ejabberd.yml` for an ejabberd-contrib module (`mod_foo` in this example): 

1. `$CONTRIB_MODULES_PATH/mod_foo/conf/mod_foo.yml`  
  This is the sample configuration file shipped with `mod_foo` (the one you mentioned above).  It's overwritten whener you update the module.
2. `$CONTRIB_MODULES_CONF_DIR/mod_foo.yml`  
  You can create this file yourself.  If you do, the above sample configuration file is ignored.  It won't be overwritten by module updates.

Both directory paths (`CONTRIB_MODULES_PATH` and `CONTRIB_MODULES_CONF_DIR`) can be specified [in the `ejabberdctl.cfg` file][1].

[1]: https://github.com/processone/ejabberd/blob/16.01/ejabberdctl.cfg.example#L163

**Comment by ethoms** [comment]
@wiess: Thanks for this advice. This means I won't have to remember to copy my config when upgrading contrib modules.

BTW, thanks for implementing these very useful XEP's. They make XMPP much more usable. I'm now in a really good place with the level of service. I recommend Conversations to my users and I will be deploying Gajim in replacement of Kopete on all our corporate workstations. It's all working almost perfectly. I only need to get muc conference rooms to have archive support (perhaps via mod_mam). At the moment, the history on the server is lost when I reboot the service. I couldn't get it working with the inbuilt (mod_mam), nor the contrib (mod_mam_mnesia). FreeBSD ports is still on 15.07, so I will try again once the maintainer updates the port.

Once again, I am so thrilled with my XMPP service now that I have 'Mesage Carbons', 'HTTP Upload' and  'MAM' working on desktop and mobile. :-)

**Comment by weiss** [comment]
> It's all working almost perfectly. I only need to get muc conference rooms to have archive support (perhaps via mod_mam). At the moment, the history on the server is lost when I reboot the service. I couldn't get it working with the inbuilt (mod_mam), nor the contrib (mod_mam_mnesia). FreeBSD ports is still on 15.07, so I will try again once the maintainer updates the port.

`mod_mam` supports MUC MAM since ejabberd 15.09, but you need ejabberd 16.01 or newer to make it work with Conversations.  And unfortunately, Gajim doesn't support MUC MAM at all, so far.

Thanks a lot for the positive feedback!
