### ISSUE TITLE
mp3 files not  included

### ISSUE THREAD

**Issue by kevinkk525** [processone/ejabberd-contrib#148]
mp3 files are not included in the list of supported file types, only as mpeg. but if I send a real .mp3 file the other person only gets a link to download the file from the server.
i know how to fix that if i compile the mod from source but in ejabberd > 15.10 the mod is included in ejabberd and I don't know how to modify it.

**Comment by badlop** [comment]
If you show me here the change in the module code you propose, I'll review and include the change in git.

**Comment by kevinkk525** [comment]
created a pull request: https://github.com/processone/ejabberd-contrib/commit/d7941fd379f9977172aa10783cb74bd51f570821

**Comment by zinid** [comment]
Guys, why are you fixing this? `mod_http_upload` is a part of ejabberd since 15.10 (IIRC).
@kevinkk525 what exact problems do you have with 15.10?

**Comment by kevinkk525** [comment]
I'm using Conversations on Android. If i send a file to someone else (using Conversations) and it is a supported filetype then the file will be shown as picture/video/audio. If it is not supported then it will just show a link to the file.
I remember that i changed the mp3 filetype in earlier versions to kind of fix that. Could be different now.. I just checked the other filetypes in http_upload and Conversations does not seem to support those..
I wanted to test if something changes if i change the filetype. I just can't find a way to do that since the mod is integrated into ejabberd.

**Comment by weiss** [comment]
If this change is correct, please just file a PR that fixes the module shipped with ejabberd.  However, [the standard][1] says that `audio/mpeg` is the correct MIME type for MP3 files, as far as I can tell ...

Either way, we _could_ of course just make this configurable (like it is in `[mod_http_fileserver][2]`).  Not sure whether it's worth it ...

[1]: http://tools.ietf.org/html/rfc3003
[2]: http://docs.ejabberd.im/admin/guide/configuration/#modhttpfileserver

**Comment by kevinkk525** [comment]
You are probably right. I just changed the source and re-compiled ejabber and it did not change anything. So it's a problem in Conversations.. No idea why I did change that earlier..
Sorry for causing a discussion that was not important.

**Comment by weiss** [comment]
Okay, thank you for double-checking.
