### ISSUE TITLE
ejabberd_auth_http crash " no match of right hand value"

### ISSUE THREAD

**Issue by richp10** [processone/ejabberd-contrib#151]
Am running latest master (at Feb 20) build.  Succesfully installing auth_http with /sbin/ejabberdctl module_install ejabberd_auth_http. Configured as follows: 

```
auth_method: http
auth_opts:
  host: "http://192.168.0.2"
  path_prefix: "/auth/"
  connection_pool_size: 10
```

Using curl I have checked the API for /auth/check_password and /auth/user_exists are reachable and working - returning 200 'true' or 400 'false' per the spec. The web-admin console fails to load and user login fails.  Following errors in ejabberd logs. 

```
	   CRASH REPORT Process <0.1494.0> with 0 neighbours crashed with reason: no match of right hand value {error,status_line} in ejabberd_auth_http:make_req/5 line 254
	   
	   =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.1496.0>
    registered_name: []
    exception exit: {{{badmatch,{error,status_line}},[{ejabberd_auth_http,make_req,5,[{file,"src/ejabberd_auth_http.erl"},{line,254}]},{ejabberd_auth_http,check_password,3,[{file,"src/ejabberd_auth_http.erl"},{line,76}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,750}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [<0.1301.0>,ejabberd_listeners,ejabberd_sup,<0.815.0>]
    messages: []
    links: [#Port<0.28238>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 9952
  neighbours:
```

Any thoughts?

**Comment by mbukosky** [comment]
Any update on this? I am having the same issue

` CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: call to undefined function ejabberd_auth_http:check_password( ...`

**Comment by badlop** [comment]
> call to undefined function ejabberd_auth_http:check_password( ...

Maybe ejabberd_auth_http.beam is not found by erlang: installed in the wrong place, or erlang not looking where it was installed.

Or maybe there's a bug in the code and calls the function with wrong number of arguments. Show the full error message.
