### ISSUE TITLE
Update calls to dependencies after ejabberd 16.02

### ISSUE THREAD

**Issue by zyfmix** [processone/ejabberd-contrib#152]
the mod_logxml file only log like below:
~~~
<?xml version="1.0"?>
<?xml-stylesheet href="xmpp.xsl" type="text/xsl"?>
<log>
~~~

**Comment by EugeneNews** [comment]
is it because of migration to new dependency? xml->fxml ...

**Comment by zyfmix** [comment]
@EugeneNews Thank you very much.after i change [mod_logxml Line#202](https://github.com/processone/ejabberd-contrib/blob/master/mod_logxml/src/mod_logxml.erl#L202) like below:
~~~
%% TimestampISO, binary_to_list(xml:element_to_binary(Packet))]).
TimestampISO, binary_to_list(fxml:element_to_binary(Packet))]).
~~~
it solve the the problem,you are right!

**Comment by badlop** [comment]
Ok, when ejabberd 16.02 gets released, all those library calls must be updated in ejabberd-contrib Git.

**Comment by badlop** [comment]
Holger Weiss already updated in March most modules to work with 16.02. The only remaining modules are three that anyway are not able to work with recent ejabberd versions: atom_pubsub, ircd, mod_archive.
