### ISSUE TITLE
mod_rest - unicode characters not working in ejabberd 16.02

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd-contrib#153]
Problem affects the changes in https://github.com/processone/ejabberd/issues/878 Now it's impossible to send unicode characters (e.g. polish characters) via mod_rest for example in send_message command.

**Comment by prefiks** [comment]
Looks like sending raw stanzas (POSTing <message...>) is working as long as you are using utf-8 encoding, but indeed execution of commands do have some problems with encoding

**Comment by beherit** [comment]
@prefiks could You write some fix? I really need this woriking, now I can't update from ejabberd 16.01 to 16.02...

**Comment by prefiks** [comment]
Yeah it's not that simple. But if all you want to do is send <message/> to someone, you should be able to do it with this module. You can just POST request with body like this: <message to="someone"><body>Wiadomość testowa</body></message> and as long as you encode that in utf8 it should be delivered with correct content.

**Comment by beherit** [comment]
Oh I found solution! mod_rest.erl, line 90:
```
Args = split_line(binary_to_list(Data)),
```
Need to change into:
```
Args = split_line(unicode:characters_to_list(Data, utf8)),
```

**Comment by prefiks** [comment]
You may check mod_http_api that is part of ejabberd main repo, it allows to execute commands and as i checked don't have problem with encoding

just add request_handler with ``"/api": mod_http_api`` in http listener and add two new top level commands:
```
commands_admin_access: configure
commands:
  add_commands:
    - send_message
    - status
```

To execute those you need to use http basic auth and add header X-Admin: true in your requests. This module accept arguments as json so you may for example send:
```
{"type": "chat", "from": "me@server.com", "to":"you@server.com", "subject": "", "body":"Cześć"}
```
to http://server:5280/api/send_message
(using curl this could look like this:
```
curl -H "X-Admin: true" -X POST -u me@server.com:password -d '{"type": "chat", "from": "me@server.com", "to":"you@server.com", "subject": "", "body":"Cześć"}' http://127.0.0.1:5280/api/send_message
```

**Comment by beherit** [comment]
@prefiks See my solution, could You commit this? :) P.S. mod_http_api use RestAPI? I will try it later.

**Comment by prefiks** [comment]
I commited this change as 7f75aa0372042b1878652e4dbf8b2ddd77362bb2

**Comment by beherit** [comment]
Thank You! :)

P.S. This Rest API doesn't work for me - I always have error "400 Bad Request".

**Comment by monkeyfdude** [comment]
@beherit Same for me. I always have error "400 Bad Request".

ejabberd-16.03 / Ubuntu 16.04
