### ISSUE TITLE
mod_rest configuration being ignored in v16.02

### ISSUE THREAD

**Issue by abes-dabir** [processone/ejabberd-contrib#159]
Hi,

I've previously setup a working ejabberd v15.07 with mod_rest and I'm familiar with how to configure it.  I'm trying to do the same with v16.02 and I'm running into a problem.  Basically it seems that the configuration under the modules section of the .yml file is being ignored, and also that mod_rest is being initialized with defaults other than what your README suggests.  This is my config:

modules:
  mod_rest: 
    access_commands:
      configure:
        - registered_users
        - connected_users
        - register
        - unregister

This is what I see in the logs:

2016-03-18 15:52:51.109 [warning] <0.2335.0>@gen_mod:validate_opts:255 module 'mod_rest' doesn't export mod_opt_type/1
2016-03-18 15:52:51.109 [debug] <0.2335.0>@mod_rest:start:42 Starting: <<"...censored hostname...">> [{allowed_ips,[{127,0,0,1}]}]

Notice that it is restricted to 127.0.0.1.  The README says that:
allowed_ips: IP addresses that can use the rest service.
Allowed values: 'all' or a list of Erlang tuples.
**Default value: all**

I tried specifying allowed_ips with various values (all, list of IPs, the specific IP of the remote machine I have that is launching the REST requests), but nothing seemed to make any difference, and the logs always showed that only the localhost was accepted.  The only time I had success was when I used the web admin portal and went to VirtualHosts -> nodes -> modules -> mod_rest and modified the value it had for allowed_ips, but this gets wiped out on server restart.  Even then, I confirmed that the "access_commands" was being ignored and I could reach commands other than the ones in my list, and also that the admin credentials weren't being checked.

HELP!
Thanks

**Comment by badlop** [comment]
As there seems there are several problems (unexpected behaviours) in your tests, let's focus in one at a time only. The first one:

> Basically it seems that the configuration under the modules section of the .yml file is being ignored

Right. That may happen if you installed mod_rest using "ejabberdctl module_install mod_rest". That command creates a default module configuration in $HOME/.ejabberd-modules/mod_rest, which overwrites anything you may put in your main ejabberd.yml. Is that the problem you were facing?

**Comment by abes-dabir** [comment]
Thanks, that solves the mod_rest configuration being ignored problem. I'm now running into a problem where the list of access commands I have specified can be accessed **without ** providing authentication information.  Providing the correct authentication information results in "Error: account_unprivileged".  This is the opposite of what I would expect.  What works is that no commands outside the list can be accessed.

This is my config:
in the mod_rest config file:

modules:
  mod_rest:
    access_commands:
      configure:
        - registered_users
        - connected_users
        - register
        - unregister
        - status

In the main config file:

I've put "/rest": mod_rest under listen in the right place.

acl:
  admin:
    user:
      - "admin": "myhost"

access:
  configure:
    admin: allow

I have created a user called "admin" in "myhost".  This is the body of the POST request I'm sending:

--auth admin myhost password status

**Comment by abes-dabir** [comment]
I basically need a simple REST interface to remotely manage my ejabberd instance (register, unregister, registered_users).  Is it possible to use mod_http_api without OAuth?  I've been able to successfully use it with Basic Authentication to access ejabberd core commands like connected_users, but I can't use it with ejabberdctrl commands.  When I try:

http://localhost:5280/api/status
I get a "400 Bad Request" response.  I've got correct headers: admin, basic auth, json, and a body of "{}" as per the documentation: https://docs.ejabberd.im/admin/api/

The logs are unhelpful:

2016-03-22 16:50:14.747 [debug] <0.2817.0>@ejabberd_http:process:353 [<<"api">>,<<"status">>] matches [<<"api">>]
2016-03-22 16:50:14.747 [info] <0.2817.0>@mod_http_api:log:388 Admin call status [] from 127.0.0.1:37595

My config:

commands_admin_access: configure
commands:
  - add_commands: status
oauth_expire: 9600
oauth_access: all

What am I doing wrong?

**Comment by badlop** [comment]
Ok, after some testing, I think the documentation is lacking, or the code has problems, or they don't match, or all of the above. Anyway, I got it working with two changes:

> the list of access commands I have specified can be accessed *without * providing authentication information.

To solve this, a patch must be applied.

> Providing the correct authentication information results in "Error: account_unprivileged". 

To solve this, the option commands_admin_access must also be provided.

In summary, I describe how I got it working correctly:
* Apply this patch:
```
--- a/src/ejabberd_ctl.erl
+++ b/src/ejabberd_ctl.erl
@@ -214,7 +214,7 @@ process(Args) ->
 process2(["--auth", User, Server, Pass | Args], AccessCommands) ->
     process2(Args, {list_to_binary(User), list_to_binary(Server), list_to_binary(Pass), true}, AccessCommands);
 process2(Args, AccessCommands) ->
-    process2(Args, admin, AccessCommands).
+    process2(Args, noauth, AccessCommands).
 
 process2(Args, Auth, AccessCommands) ->
     case try_run_ctp(Args, Auth, AccessCommands) of
```
* Configure like this:
```
listen:
  -
    port: 5281
    module: ejabberd_http
    request_handlers:
      "/rest": mod_rest

acl:
  admin:
    user:
      - "user1": "localhost"

access:
  configure:
    admin: allow

commands_admin_access: configure

modules:
  mod_rest:
    access_commands:
      configure:
        - registered_users
        - connected_users
```
* Register account user1@localhost with password mypass11.

This works:
> wget http://localhost:5281/rest/ --server-response --post-data "--auth user1 localhost mypass11 registered_users localhost"

Providing wrong password, or other account, or no account, fails as expected:
> wget http://localhost:5281/rest/ --server-response --post-data "registered_users localhost"

**Comment by beherit** [comment]
> `I basically need a simple REST interface to remotely manage my ejabberd instance (register, unregister, registered_users). Is it possible to use mod_http_api without OAuth?

Good question. It's possible to use mod_http_api without OAuth? In this issue https://github.com/processone/ejabberd-contrib/issues/153#issuecomment-195083275 @prefiks says that it works but for me it not work.

**Comment by abes-dabir** [comment]
Awesome, thanks badlop.  I'll give it a shot and let you know, although I'm sure it will work given your detailed instructions.  I take it we can expect that patch to go into 16.03?

In the mean time, I've figured out how to get what I need using mod_http_api with just basic authentication.  I've found a **minor bug** in it where it returns "400 Bad Request" when I try to access unauthorized commands.  A 403 Forbidden would probably make more sense.  The 400 made me think there was a problem with the request body and I spent quite a bit of time wrestling with my it.

beherit, thanks for posting that link.  It helped me solve my problem, which was me not putting in the correct YAML syntax when adding commands.  I've got mod_http_api working with just basic authentication, no OAuth, with this configuration:

`
- 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      # ReST API:
      "/api": mod_http_api
    ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    ## register: true
    captcha: false

#all the way at the bottom of the conf file, I have this:

commands_admin_access: configure
commands:
  add_commands:
    - status
    - registered_users
    - register
    - unregister

`

If you remove "status" from the above list and try making a request to it, you'll see the "400 Bad Request" issue.
