### ISSUE TITLE
System uptime

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd-contrib#162]
I looking for some module that add simple command to ejabberdctl which will return system uptime in seconds (just like it is for command _stats uptimeseconds_). I need such module to getting system uptime information via mod_rest / mod_http_api. Can some one write this? :)

**Comment by mathiasertl** [comment]
Oh yeah, while we're at it, I'd love to have an API for disk-usage and cpu-usage. That way I could use ejabberd as a system monitoring daemon!

**Comment by beherit** [comment]
It is an irony? I created plugin for WordPress that provides ejabberd statistics (works like e.g. Munin) via mod_http_api and only system uptime I fetch in strange way, so such module will solve the problem. On I my VPS I have installed only ejabberd and I don't want to install Munin or other system monitoring daemon, so please calm down - not all have super machines and have a lot of resources to install a lot of softwares.

**Comment by badlop** [comment]
There is a very old module that allowed to run shell commands in the WebAdmin. Maybe you can reuse some code to write an ejabberd command:
https://www.ejabberd.im/mod_shcommands
https://github.com/processone/ejabberd-contrib/tree/master/mod_shcommands

**Comment by beherit** [comment]
Is only one problem - I don't know erlang language :)

**Comment by badlop** [comment]
Try something like this:
```
--- a/mod_shcommands/src/mod_shcommands.erl
+++ b/mod_shcommands/src/mod_shcommands.erl
@@ -12,10 +12,12 @@
 -behaviour(gen_mod).
 
 -export([web_menu_node/3, web_page_node/5,
+	 execute/1,
 	 start/2, stop/1]).
 
 -include("ejabberd.hrl").
 -include("jlib.hrl").
+-include("ejabberd_commands.hrl").
 -include("ejabberd_http.hrl").
 -include("ejabberd_web_admin.hrl").
 
@@ -26,6 +28,7 @@
 start(_Host, _Opts) ->
     ejabberd_hooks:add(webadmin_menu_node, ?MODULE, web_menu_node, 50),
     ejabberd_hooks:add(webadmin_page_node, ?MODULE, web_page_node, 50),
+    ejabberd_commands:register_commands(commands()),
     ok.
 
 stop(_Host) ->
@@ -34,6 +37,21 @@ stop(_Host) ->
     ok.
 
 %%-------------------
+%% Commands
+%%-------------------
+
+commands() ->
+    [#ejabberd_commands{name = execute, tags = [system],
+			desc = "Execute a shell command.",
+			policy = admin,
+			module = ?MODULE, function = execute,
+			args = [{command, string}],
+			result = {res, string}} ].
+
+execute(Command) ->
+    lists:flatten(parse1_command(<<"executeshe">>, {none, none, Command}, node())).
+
+%%-------------------
 %% Web Admin Menu
 %%-------------------
 
```

Then you can do things like this:
```
$ ejabberdctl execute "uname -a"
badlop@ate://var/lib/ejabberd$ uname -a
Linux ate 4.3.0-0.bpo.1-amd64 #1 SMP Debian 4.3.3-5~bpo8+1 (2016-01-07) x86_64 GNU/Linux
```

**Comment by beherit** [comment]
In that way it's possible to execute all commands via ejabberdctl. As I say I don't know erlang but I will take a look at Your example. But maybe I can write module that simple return system uptime?

**Comment by badlop** [comment]
I guess in the call to parse1_command, instead of Command you can pass as argument: <<"uptime">>

**Comment by beherit** [comment]
Sorry but I'm not good in erlang, I have much problems with write such module :(

**Comment by badlop** [comment]
Apply the patch that I mentioned, then modify the line
>    lists:flatten(parse1_command(<<"executeshe">>, {none, none, Command}, node()))

with
>    lists:flatten(parse1_command(<<"executeshe">>, {none, none, <<"uptime">>}, node()))

**Comment by beherit** [comment]
@badlop And then to get uptime I need to execute ``ejabberdctl executeshe uptime``? How can I add another bash command to execute? Could You write this module for me? I could pay You.

**Comment by badlop** [comment]
> @badlop And then to get uptime I need to execute ejabberdctl executeshe uptime?

With: ejabberdctl execute whatever

> How can I add another bash command to execute?

Copy the code that we just added, replacing all the words execute with execute2, put in the code the command you want, and call: ejabberdctl execute2 whatever

> Could You write this module for me? I could pay You.

Try it a little more yourself, you are almost there, and then you will know to add your own commands.
