### ISSUE TITLE
mod_rest module not working on 16.04

### ISSUE THREAD

**Issue by adisos** [processone/ejabberd-contrib#163]
I installed latest 16.04 for mac os.

Run these commands:
1. `ejabberdctl modules_update_specs`
2. `ejabberdctl module_install mod_rest`
3. `ejabberdctl restart`

And it shows error on log:
```
2016-05-03 15:03:17.558 [error] <0.567.0> CRASH REPORT Process <0.567.0> with 0 neighbours exited with reason: call to undefined function mod_rest:mod_opt_type(db_type) in application_master:init/4 line 134
2016-05-03 15:03:17.558 [info] <0.537.0> Application ejabberd exited with reason: call to undefined function mod_rest:mod_opt_type(db_type)
```

Is there any fast solution to get it working?
I think the problem is missing of function `mod_opt_type(db_type)`, so I tried to modify `mod_rest` directory with adding latter function. But stuck when I tried to compile. Here is my command:
```
cd ~/.ejabberd-modules/mod_rest && erlc -o ebin -I include -I /Applications/ejabberd-16.04/lib/ejabberd-16.04/include -DLAGER -DNO_EXT_LIB ~/.ejabberd-modules/sources/ejabberd-contrib/mod_rest/src/mod_rest.erl
```

It shows: `/Users/adis/.ejabberd-modules/sources/ejabberd-contrib/mod_rest/src/mod_rest.erl: undefined parse transform 'lager_transform'`

Thank you in advance

**Comment by zinid** [comment]
You can fetch the latest ejabberd revision, there is a workaround for such modules.

**Comment by zinid** [comment]
This commit, to be exact: b46ed7044a6d57670b2e7f5b6278254ecd869b78

**Comment by adisos** [comment]
I leave as is, I decided to go back 16.03

**Comment by lxnx0** [comment]
In version 16.06 the error now become warning

```src/mod_rest.erl:27: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
ok```

**Comment by badlop** [comment]
@lxnx0 I've applied a fix, try the module compiles without complaining, and that the options are read correctly. If it fails, please reopen the ticket.
