### ISSUE TITLE
mod_statsdx counters always in zero

### ISSUE THREAD

**Issue by leunamnauj** [processone/ejabberd-contrib#167]
Hello Team!
I need to count all messages send/received, for this propose I'm trying to use mod_statsdx.
I tried all configs I founded but the result is always the same:
```
sendiqin| 0  
sendiqout| 0  
sendmessagein| 0  
sendmessageout| 0  
sendpresencein| 0  
sendpresenceout| 0  
recviqin| 0  
recviqout| 0  
recvmessagein| 0  
recvmessageout| 0  
recvpresencein| 0  
recvpresenceout| 0  
```
I'm not sure what I'm doing wrong, any help is very welcome.
Thanks in advance

**Comment by badlop** [comment]
Instead of
```
modules:
  mod_statsdx:
    hooks: true
```
you must put:
```
modules:
  mod_statsdx:
    hooks: traffic
```

**Comment by leunamnauj** [comment]
It worked! Within all the tests I've missed this setup.
Thank you very much

**Comment by leunamnauj** [comment]
One last question.
Is documented somewhere the meaning of each mod_statsdx value? I'm not quite sure about the relationship between   sendmessagein+sendmessageout and recvmessagein+recvmessageout

Thanks again

**Comment by badlop** [comment]
Those items count calls to the hooks user_send_packet and user_receive_packet. They are not documented. In case of doubt, you can install ejabberd in a test machine, and play with those values.
