### ISSUE TITLE
Tag versions like ejabberd server

### ISSUE THREAD

**Issue by vguardiola** [processone/ejabberd-contrib#168]
Hi, I've problems with the update code in ejabberd-contrib and my ejabber server version, I use Gentoo linux and the last ejabberd version is 16.01 and when I update the modules which don't have versions tag break my server.

I suppose that the code of modules_update_specs must be changed to download the same version of contrib modules than the ejabber server.

Thanks

**Comment by cromain** [comment]
problem is that we can not maintain these modules to work with any ejabberd version. this makes tag pointless as some modules supports 17.12, some only supports 15.x... We won't tag this repo.
It's best code owners to upgrade there modules to 17.12, as API stabilised last months, so all modules should support the current ejabberd version.
