### ISSUE TITLE
undefined parse transform 'lager_transform'

### ISSUE THREAD

**Issue by bhavikdesai94** [processone/ejabberd-contrib#169]
I am trying to install zero_push module for ejabberd 16.03 but when i run build.sh file at that time its give me error undefined parse transform 'lager_transform' so how can i solve my problem i am using mac os??

**Comment by badlop** [comment]
What is zero_push and where did you find it?

**Comment by bhavikdesai94** [comment]
https://github.com/ZeroPush/mod_zeropush here is the link of zero_push module it ti an ejabberd module to send push notification.
I don't know much about it please visit link to morre info.

**Comment by badlop** [comment]
I also have problems compiling that module as it is in the git repository. This is what I did:
I downloaded ejabberd git repo
Copy mod_zeropush.erl to ejabberd/src
Compile ejabberd
Install ejabberd
Configure the module in ejabberd
Start it. No problems, but I didn't try to use the module

**Comment by vijayaa** [comment]
I am also facing the same issue when i am compiling mod_rest module. i am using ejabberd 16.02

**Comment by badlop** [comment]
How do you compile and install mod_rest ?

**Comment by bhavikdesai94** [comment]
@badlop i haven't use zeropush but i found another module which is [mod_intrect](https://github.com/adamvduke/mod_interact) which can be user to send push notification.

**Comment by badlop** [comment]
https://github.com/processone/ejabberd-contrib/tree/master/mod_rest

**Comment by palmertime** [comment]
I'm also having a similar issue when trying to compile ejabberd_auth_http.

`# erlc -I /usr/lib/erlang/lib/ejabberd-16.04/include src/ejabberd_auth_http.erl
src/ejabberd_auth_http.erl: undefined parse transform 'lager_transform'`

ejabberd-16.04

**Comment by bhavikdesai94** [comment]
Write this code in build.sh file and run that file it will works for sure.
`#!/bin/bash

# change with the erlc path of your current ejabberd installation
EJBR_PATH='/Applications/ejabberd'
EJBR_VERSION="16.03"

$EJBR_PATH/bin/erlc -DNO_EXT_LIB -DLAGER -I $EJBR_PATH/lib/ejabberd-$EJBR_VERSION/include/ -o ebin/ src/*`

**Comment by palmertime** [comment]
Thanks for the help but that did not work for me either.

I compiled ejabberd and dependancies from source.  erlc is here /bin/erlc but the path to ejabberd is /usr/lib/erlang/lib/ejabberd-16.04/

Here is the build.sh script i used without success.

`#!/bin/bash`
`ERLANG_PATH='/usr/lib/erlang/'`
`EJBR_VERSION="16.04"`
`/bin/erlc -DNO_EXT_LIB -DLAGER -I $ERLANG_PATH/lib/ejabberd-$EJBR_VERSION/include/ -o ebin/ src/*`

Same error ....

`# ./build.sh`
`src/ejabberd_auth_http.erl: undefined parse transform 'lager_transform'`

**Comment by badlop** [comment]
If you compile ejabberd from source code, simply copy any other modules *.erl files to ejabberd's src/ dir, compile and install.

**Comment by palmertime** [comment]
That seems to work for the .erl files.   Do i also have to put the dependency .erl files in there?

For instance ejabberd_auth_http has a deps directory with cuesport and fusco.  Do i need to do anything with these?

Thanks for the help.

**Comment by badlop** [comment]
Those dependencies are indepedent erlang applications, so they have their own Makefile so you can compile them independently. Once compiled, copy their beam files to where ejabberd copies its beam files.

Or maybe those applications can compile correctly if you simple copy their *.erl as you did with ejabberd_auth_http.erl

**Comment by wei18810109052** [comment]
@bhavikdesai94 
I am also trying to install zero_push module for ejabberd 16.09. ^-^
But I still get error using your method. Where I went wrong? 

```
EJBR_PATH='/Applications/ejabberd-16.09'
EJBR_VERSION="16.09"

$EJBR_PATH/bin/erlc -DNO_EXT_LIB -DLAGER -I $EJBR_PATH/lib/ejabberd-$EJBR_VERSION/include/ -o ebin/ src/*

```

```
/Applications/ejabberd-16.09/lib/ejabberd-16.09/include/jlib.hrl:23: can't find include file "fxml.hrl"
/Applications/ejabberd-16.09/lib/ejabberd-16.09/include/jlib.hrl:430: record xmlel undefined
/Applications/ejabberd-16.09/lib/ejabberd-16.09/include/jlib.hrl:470: type xmlel() undefined
src/mod_zeropush.erl:31: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
src/mod_zeropush.erl:31: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
```

**Comment by cromain** [comment]
provided script helper works, when controlling compilation is needed. else, using module_install command will do all necessary stuff for compilation. just put sources in ~/.ejabberd-modules/sources/xxx and run 'module_install xxx' command.

**Comment by relbraun** [comment]
@cromain , the module_install xxx command doesn't work and returns: ERROR: not_available. The error log is empty and the ejabberd.log is:
```
2019-07-14 13:15:29.707 [debug] <0.22162.1>@ejabberd_access_permissions:handle_call:108 Command 'module_install' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
2019-07-14 13:15:29.707 [debug] <0.22657.1>@ejabberd_commands:do_execute_command:445 Executing command ext_mod:install with Args=[<<"mod_hello">>]
```

**Comment by badlop** [comment]
@relbraun First: this ticket is closed, and your problem is unrelated to this ticket. You better create a new ticket describing in detail your problem.
Second: you tell ejabberd to install mod_hello, but that module is not included in the repository, so it says not_available. What did you expect to happen?
