### ISSUE TITLE
I cannot get modules

### ISSUE THREAD

**Issue by BesatZardosht** [processone/ejabberd-contrib#171]
I have installed ejabberd 16.03 from binary source (ejabberd-16.03-osx-installer.app.zip)
my os is OS X Yosemite
After Installation completed I started ejabberd:
`cd ejabberd_directory/bin`
`./ejabberdctl start`
I even chacked the status to make sure it is started.
then I tried to retrieve the list of available modules:
`./ejabberdctl modules_update_specs`
and it says ok!
but I get nothing by running this:
`./ejabberdctl modules_available`

I would appreciate any help..

**Comment by badlop** [comment]
Right, this was fixed in processone/ejabberd#1157

Until you can get a ejabberd with modules_update_specs fixed, you can make that step manually, see the explanations in
https://github.com/processone/ejabberd-contrib/tree/master/mod_pottymouth
