### ISSUE TITLE
mod_rest allowing ip range

### ISSUE THREAD

**Issue by tolgatanriverdi** [processone/ejabberd-contrib#175]
Hi
I would like to allow several ip blocks to send commands to mod_rest (Because we are using google app engine as our backend server and appengine doesnt have a static ip address)
I've tried this

allowed_ips:
  - "127.0.0.1"
  - "66.102.0.0/20"

But it didnt work.
So does anyone know is there any way to allow ip block to send mod_rest command

Thanks
Tolga

**Comment by badlop** [comment]
Not possible, right now, because mod_rest does a simple comparison.

Now that acl.erl supports IP verification, with mask support, maybe mod_rest could call acl:acl_rule_matches to support that.

**Comment by badlop** [comment]
Support added to mod_rest, requires ejabberd git master or 16.08 (when released).

**Comment by tolgatanriverdi** [comment]
Thanks for the information:

So what should we write to configuration file(ejabberd.yml) in allowed_ips section:
Is it something like that:  "66.102.0.0/20"
And for updating the mod_rest do we need another version of ejabberd?

**Comment by badlop** [comment]
I used this:
```
modules:
  mod_rest:
    allowed_ips:
      - "127.0.0.0/8"
```
Yes, this feature requires ejabberd from git, or 16.08 once it gets released.

**Comment by tolgatanriverdi** [comment]
Now I've downloaded and installed the ejabberd 16.08 , and installed mod_rest with module_install command
Can I use the ip range in mod_rest configuration now?

**Comment by badlop** [comment]
Yes, the config example I showed should work for you now.
