### ISSUE TITLE
can not connect to mod_rest remotly

### ISSUE THREAD

**Issue by bobnino** [processone/ejabberd-contrib#177]
mod_rest works ok when connecting to it from localhost however if i connect remotely to it from another instance i get the following

/# wget http://52.11.3.241:5285/rest/ --server-response --post-data ' registered_users localhost'
--2016-07-18 13:54:01-- http://52.11.3.241:5285/rest/
Connecting to 52.11.3.241:5285... connected.
HTTP request sent, awaiting response...
HTTP/1.1 406 Not Acceptable
Content-Type: text/html; charset=utf-8
Content-Length: 43
2016-07-18 13:54:01 ERROR 406: Not Acceptable.

any thoughts why this is happening ??

**Comment by badlop** [comment]
Comes from processone/ejabberd#1200

You said this doesn't work:
> wget http://52.11.3.240:5285/rest/ --header='Host: http://52.11.3.240' --server-response --post-data ' registered_users localhost'

Better try:
> wget http://52.11.3.240:5285/rest/ --header='Host: 52.11.3.240' --server-response --post-data ' registered_users localhost'

Or:
> wget http://52.11.3.240:5285/rest/ --header='Host: localhost' --server-response --post-data ' registered_users localhost'

**Comment by bobnino** [comment]
no luck badlop  still the same problem tried all you mentioned

**Comment by bobnino** [comment]
think it might be yml config issue

**Comment by bobnino** [comment]
also think ejabberd needs a bridge between its command line and a php class

**Comment by badlop** [comment]
In ejabberd configuration file set loglevel te debug, then make those requests, and see if the ejabberd log files show any lines that mention "REST" or similar.

**Comment by bobnino** [comment]
i tried your suggestion badlop this is what i get in the log file 

2016-07-22 15:29:45.508 [debug] <0.8578.0>@ejabberd_http:init:154 S: [{[<<"rest">>],mod_rest}]
2016-07-22 15:29:45.508 [info] <0.8578.0>@ejabberd_http:init:158 started: {gen_tcp,#Port<0.46953>}
2016-07-22 15:29:45.508 [debug] <0.8578.0>@ejabberd_http:process_header:281 (#Port<0.46953>) http query: $
2016-07-22 15:29:45.510 [debug] <0.8578.0>@ejabberd_http:extract_path_query:395 client data: <<"register $
2016-07-22 15:29:45.510 [debug] <0.8578.0>@ejabberd_http:process:353 [<<"rest">>] matches [<<"rest">>]
2016-07-22 15:29:45.510 [debug] <0.8578.0>@mod_rest:process:55 Error when processing REST request:
Data: <<"register bo2 localhost connect">>
Error: {badmatch,false}

**Comment by bobnino** [comment]
its so frustrating i even built a php script that bypass the rest module and just issue commands to the ejabberdctl using http post with php!!

**Comment by badlop** [comment]
It seems as if the allowed_ips option doesn't get satisfied. Have you configured it?

**Comment by bobnino** [comment]
hosts:
  - "localhost"
  - "52.34.108.211"
  - "all"
  - "52.11.3.240"
and 

acl:
  restuser:
    user:
      - "essa": "52.34.108.211"
      - "amar": "localhost"

  admin:
    user:
      - "amar@localhost"


 access:
    restaccess:
      restuser: allow

  local:
    user_regexp: ""
access_rules:
  ## This rule allows access only for local users:
  local:
    - allow
modules:
  mod_rest:
    allowed_ips:
      - "52.34.108.211"
      - "127.0.0.1"
      - "52.11.3.240"
      - "all"

thats all the relevant configuration i think , still doesn't work

**Comment by badlop** [comment]
The mod_rest documentation says:
```
   allowed_ips: IP addresses that can use the rest service.
  Allowed values: 'all' or a list of Erlang tuples.
  Default value: all
```

There's an error there, it means strings not tuples. I'll fix that in git, even if that's not the problem you are facing.

You have two alternatives:
```
modules:
  mod_rest:
    allowed_ips: all
```
Or:
```
modules:
  mod_rest:
    allowed_ips:
      - "52.34.108.211"
      - "127.0.0.1"
      - "52.11.3.240"
```
Another thing you must look, is that if you install mod_rest using "ejabberdctl module_install", its default configuration is created in $HOME/.ejabberd-modules..., and that is what ejabberd uses regardless of what you put in your main ejabberd.yml

**Comment by bobnino** [comment]
thanks badlop , ill try your suggestion however i have developed a php rest service that sends ejabberdctl commands to the cli to bypass the mod_rest functionality .

thanks
