### ISSUE TITLE
Issue in configuring ejabberd rest api

### ISSUE THREAD

**Issue by ankitcode** [processone/ejabberd-contrib#178]
I'm using `ejabberd 16.01`and I've installed it using `sudo apt-get install ejabberd`.
I've added following configuration in /etc/ejabberd/ejabberd.yml file : 
```
listen:
  - 
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
      "/log": mod_log_http
```
I want to use ejabberd api without oauth authentication, can someone tell me what other configurations are required.

**Comment by badlop** [comment]
There is an example configuration in the beginning of  the source code file:
https://github.com/processone/ejabberd/blob/master/src/mod_http_api.erl

Notice that support for the option admin_ip_access was added in ejabberd 16.03.
