### ISSUE TITLE
mod_logxml cause ejabberd to crash

### ISSUE THREAD

**Issue by mohammadtorfehnezhad** [processone/ejabberd-contrib#180]
Hello,

I'm using ejabbed-16.02 on Debian Jessie. I've installed mod_logxml by following steps descibed here https://www.ejabberd.im/ejabberd-modules

When I start ejabberd with mod_logxml using no configuration I get this error : 
```
17:13:38.458 [critical] Problem starting the module mod_logxml for host <<"xxx">> 
 options: []
 error: badarith
[{mod_logxml,start,2,[{file,"src/mod_logxml.erl"},{line,32}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,98}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,74}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,272}]}]
```
Does anyone have any idea how to fix it and what is my fault?

Thanks

**Comment by badlop** [comment]
I tried with ejabberd 16.06, and installed the module calling "ejabberdctl module_install mod_logxml". Then restarted ejabberd, and it worked correctly. The only problem is that it complained mod_logxml lacks some definitions (that is normal).

Did you use that method? It adds a default module configuration file in $HOME/.ejabberd-modules... Which should work correctly.

If you compiled the module yourself, installed it, and defined with minimum options in the ejabberd configuration file, it should work also.
