### ISSUE TITLE
mod_logsession doesn't work

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd-contrib#184]
After upgrading ejabberd from 16.04 to 16.08 I have problem with module mod_logsession, in error.log I see:
```
2016-08-14 10:00:33.657 [critical] <0.38.0>@gen_mod:start_module:162 Problem starting the module mod_logsession for host <<"domain.tld">> 
 options: [{sessionlog,<<"/var/log/ejabberd/session.log">>}]
 exit: {aborted,
           {bad_type,
               {ejabberd_commands,reopen_seslog,
                   [logs,server],
                   "Reopen mod_logsession log file",[],0,mod_logsession,
                   reopen_log,
                   [{host,string}],
                   restricted,
                   {res,rescode},
                   none,none,none,none}}}
[{mnesia,abort,1,[{file,"mnesia.erl"},{line,310}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {mod_logsession,start,2,[{file,"src/mod_logsession.erl"},{line,55}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,154}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,76}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,272}]}]
2016-08-14 10:00:33.657 [critical] <0.38.0>@gen_mod:maybe_halt_ejabberd:170 ejabberd initialization was aborted because a module start failed.
```

**Comment by badlop** [comment]
I tried installing the module with "ejabberdctl module_install", and also compiling the module inside ejabberd source code dir. In both cases the module is started correctly. Do you have some clue what could happen in your case? Do you have a cluster?

On the other hand, even if the module starts correctly and creates empty log files, later it doesn't log failed auth attempts. Did this work correctly for you in ejabberd 16.04?

**Comment by badlop** [comment]
Ah, I get that error when using ejabberd 16.06, but gets solved when using 16.08. Are you sure you are using 16.08

**Comment by beherit** [comment]
Yes I sure that I using 16.08 ;_; I don't have a cluster, on ejabberd 16.04 module works perfect.

**Comment by beherit** [comment]
@badlop May need to add something to config file? Or maybe problem exists because I use mod_http_api?

**Comment by beherit** [comment]
Could You help me?

**Comment by badlop** [comment]
This guy had a similar problem, but said that simply reinstalling ejabberd solved it for him: processone/ejabberd#1248

**Comment by beherit** [comment]
@badlop For me reinstallation doesn't work. Maybe I must change something in my config file but I don't know what I must change.

**Comment by badlop** [comment]
So, if you uninstall and remove the Mnesia spool files, and then install it, and start immediately, the problem is still there? Find another machine, install it there, does the problem appear too? How do you install ejabberd: binary installer, compile source code, distribution package...?

**Comment by beherit** [comment]
I can't remove Mnesia files, I have a lot of users on my server. On test server I have got this same problem and when I deleted mnesia files the error still exists. I use repo from jabber.at.

**Comment by beherit** [comment]
Previously I removed the default module config from `/var/lib/ejabberd/.ejabberd-modules/mod_logsession/conf/mod_logsession.yml` and I added it to my config file. I turned off module by removing it from my config, reinstall module and now everything works. But it's not possible to move module config to my own config.

**Comment by beherit** [comment]
@badlop any idea to fix it?

**Comment by badlop** [comment]
I can't reproduce the problem, and I don't know where the problem is, so I have no idea how to fix it.
