### ISSUE TITLE
How would I add one of these modules to an Elixir App?

### ISSUE THREAD

**Issue by johnhamelink** [processone/ejabberd-contrib#187]
Hi there,

I'm looking to add `mod_archive_odbc` to my Elixir app - I have Ejabberd as a dependency. In that scenario, how would I add `mod_archive_odbc`?

**Comment by weiss** [comment]
As `mod_archive_odbc` [won't work with ejabberd 13 or newer][1], you probably don't want to use it anyway.  These days, most people use [`mod_mam`][2] instead.

[1]: https://raw.githubusercontent.com/processone/ejabberd-contrib/master/mod_archive/README.txt
[2]: https://docs.ejabberd.im/admin/guide/configuration/#modmam

**Comment by johnhamelink** [comment]
Thanks @weiss I will look into `mod_mam` instead 👍

**Comment by eathrow** [comment]
Otherwise, how do I add erlang module(mod_push) to an elixir app with ejabberd?

**Comment by dlameri** [comment]
That's still a doubt to me. Have you reached any conclusion? Can someone clarify it? Is there a hidden way to use ejabberdctl on ejabberd as a dependency on an elixir app?

**Comment by johnhamelink** [comment]
@dlameri we're using `mom_mam` these days.
