### ISSUE TITLE
mod_archive undefined callback function mod_opt_type/1 (behaviour 'gen_mod')

### ISSUE THREAD

**Issue by ucokkarnadi** [processone/ejabberd-contrib#189]
Hi there,
i have issue about installing mod_archive ejabberd 16.06 in ubuntu 16.04. when i try to install it give me warning like this

./ejabberdctl module_install mod_archive
src/mod_archive.erl:23: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
src/mod_archive_odbc.erl:71: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
src/mod_archive_sql.erl:18: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')
src/mod_archive_sql.erl:830: Warning: variable 'Errr' is unused
src/mod_archive_sql.erl:1108: Warning: variable 'SUTC' is unused
src/mod_archive_sql.erl:1109: Warning: variable 'SJID' is unused
src/mod_archive_sql.erl:1109: Warning: variable 'SName' is unused
src/mod_archive_sql.erl:1219: Warning: variable 'HEPO' is unused
src/mod_archive_sql.erl:1247: Warning: variable 'HEPO' is unused
src/mod_archive_webview.erl:220: Warning: variable 'Jid' is unused
src/mod_archive_webview.erl:220: Warning: variable 'LServer' is unused
src/mod_archive_webview.erl:220: Warning: variable 'LUser' is unused
src/mod_archive_webview.erl:220: Warning: variable 'Lang' is unused
ok

i try to fix it with this https://github.com/processone/ejabberd-contrib/issues/163 link reference and give it patch like this https://github.com/processone/ejabberd-contrib/commit/f806442b9cd7a4c62703005e0c45f74df631bc07

i add "mod_opt_type/1" and another line from that patch. but still give me warning like this

src/mod_archive_sql.erl:830: Warning: variable 'Errr' is unused
src/mod_archive_sql.erl:1108: Warning: variable 'SUTC' is unused
src/mod_archive_sql.erl:1109: Warning: variable 'SJID' is unused
src/mod_archive_sql.erl:1109: Warning: variable 'SName' is unused
src/mod_archive_sql.erl:1219: Warning: variable 'HEPO' is unused
src/mod_archive_sql.erl:1247: Warning: variable 'HEPO' is unused
src/mod_archive_webview.erl:220: Warning: variable 'Jid' is unused
src/mod_archive_webview.erl:220: Warning: variable 'LServer' is unused
src/mod_archive_webview.erl:220: Warning: variable 'LUser' is unused
src/mod_archive_webview.erl:220: Warning: variable 'Lang' is unused

can you give me advice for this warning?

Thank's

**Comment by weiss** [comment]
> i have issue about installing mod_archive ejabberd 16.06 in ubuntu 16.04.

You can ignore the warnings, but the module won't work with ejabberd 16.06 for other reasons, as stated at the top of the [README][1] file.  You might want to look into [`mod_mam`][2] which implements [XEP-0313][3] instead.

[1]: https://github.com/processone/ejabberd-contrib/blob/master/mod_archive/README.txt
[2]: https://docs.ejabberd.im/admin/guide/configuration/#modmam
[3]: https://xmpp.org/extensions/xep-0313.html

**Comment by ucokkarnadi** [comment]
thank's for your information. i'll try to use https://docs.ejabberd.im/admin/guide/configuration/#modmam.
hope i can implement it on my server.
