### ISSUE TITLE
mod_archive (mysql) support in ejabberd v13.x

### ISSUE THREAD

**Issue by rahulgautam** [processone/ejabberd-contrib#19]
The current version of mod_archive does not successfully run with ejabberd v13.12.
when I choose mod_archive as a module in config it does not log any error but when I switch the module to support mod_archive_odbc ejabberd server won't start.
Question asked on [SO](http://stackoverflow.com/questions/22383597/module-to-support-message-archive-in-ejabberd-v13-12)

**Is mod_archive does not support v13.x as ndl's [mod_archive2](https://github.com/ndl/mod_archive2) ?**
- If it does support then please provide help how I should do it.
- If it does not then is there any other module in ur knowledge for archiving messages.

**Comment by karlmendes** [comment]
Me too.
In ejabberd 16.01 the server runs, but the module has been depreaciated and the tables has not exists.

**Comment by jkufner** [comment]
Is there a reason for not convertig to mod_mam?

**Comment by karlmendes** [comment]
I'm try archive the messages from mod_shared_roster, and no success... becaus this, i'm try search another mod to archive.
