### ISSUE TITLE
acl:parse_ip_netmask

### ISSUE THREAD

**Issue by gilangpr** [processone/ejabberd-contrib#190]
CRASH REPORT Process <0.25828.1> with 0 neighbours crashed with reason: call to undefined function acl:parse_ip_netmask({127,0,0,1})

I want to test using mod_rest plugin, but error came..
whats the problem? or am I missing something?

**Comment by prefiks** [comment]
Could you check error.log to see if you have stack trace for that error?

Looks like some part of code were called with wrong argument, but not sure what part did that, getting stack trace may help with it.

**Comment by ginuerzh** [comment]
I have the same issue for ejabberd-16.03, the crash log:

=CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.1867.0>
    registered_name: []
    exception error: {undef,[{acl,parse_ip_netmask,[{127,0,0,1}],[]},{mod_rest,'-ip_matches/2-fun-0-',2,[{file,"src/mod_rest.erl"},{line,144}]},{lists,any,2,[{file,"lists.erl"},{line,1223}]},{mod_rest,check_member_option,3,[{file,"src/mod_rest.erl"},{line,134}]},{mod_rest,process,2,[{file,"src/mod_rest.erl"},{line,55}]},{ejabberd_http,process,5,[{file,"src/ejabberd_http.erl"},{line,363}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,451}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,291}]}]}
    ancestors: [<0.549.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.16885>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 831
  neighbours:

**Comment by badlop** [comment]
The {127,0,0,1} wrong argument format that the function is receiving, mentioned by Prefiks, may come from your configuration file. Can you show the lines where you have mod_rest configured? They may be in the main ejabberd config file, or they may be in mod_rest.yml...

**Comment by cobrowserAlex** [comment]
Running into this as well. My Config:
```
  mod_rest:
    access_commands:
      configure:
        - connected_users
        - user_resources
```
and the crash report:
```
2016-11-08 11:17:40 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.1068.0>
    registered_name: []
    exception error: {undef,[{acl,parse_ip_netmask,[{127,0,0,1}],[]},{mod_rest,'-ip_matches/2-fun-0-',2,[{file,"src/mod_rest.erl"},{line,144}]},{lists,any,2,[{file,"lists.erl"},{line,1223}]},{mod_rest,check_member_option,3,[{file,"src/mod_rest.erl"},{line,134}]},{mod_rest,process,2,[{file,"src/mod_rest.erl"},{line,55}]},{ejabberd_http,process,5,[{file,"src/ejabberd_http.erl"},{line,363}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,451}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,291}]}]}
    ancestors: [<0.978.0>,ejabberd_listeners,ejabberd_sup,<0.558.0>]
    messages: []
    links: [#Port<0.32580>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 2531
  neighbours:
```

**Comment by cobrowserAlex** [comment]
Solved it! a default mod_rest.yml was installed in ```<ejabberd_install_dir>.ejabberd-modules/mod_rest/conf/mod_rest.yml``` moving that to  mod_rest.yml.dist made everything work again.

the content of this file:
```
modules:
  mod_rest:
    allowed_ips:
      - "> {127,0,0,1} ."
listen:
  -
    port: 5285
    module: ejabberd_http
    request_handlers:
       "/rest": mod_rest
```
maybe that helps in fixing this for the next one...

**Comment by badlop** [comment]
Right, the format in the example configuration file was using a very old syntax, no longer accepted. Thanks for reporting!
