### ISSUE TITLE
module pottymouth not working

### ISSUE THREAD

**Issue by navjeetc** [processone/ejabberd-contrib#191]
I am trying to use module mod_pottymouth from contrib modules (https://github.com/processone/ejabberd-contrib/tree/master/mod_pottymouth)
but it is not working.

To use the module I copied the erlang source files from src folder in git repo into src folder in my ejabberd and then ran configure, make and make install and got no errors. I alos updated ejabber.yml with config suggested by module. When I start ejabberd I get no errors in log file but when I stop it, I get these errors:

`2016-09-23 02:13:49.092 [error] <0.39.0>@gen_mod:stop_module_keep_config:136 {undef,[{bloom_gen_server,stop,[],[]},{mod_pottymouth,stop,1,[{file,"src/mod_pottymouth.erl"},{line,48}]},{gen_mod,stop_module_keep_config,2,[{file,"src/gen_mod.erl"},{line,135}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{ejabberd_app,prep_stop,1,[{file,"src/ejabberd_app.erl"},{line,86}]},{application_master,prep_stop,2,[{file,"application_master.erl"},{line,377}]},{application_master,loop_it,4,[{file,"application_master.erl"},{line,353}]}]}`

`2016-09-23 02:13:49.107 [error] <0.39.0>@gen_mod:stop_module_keep_config:136 {undef,[{bloom_gen_server,stop,[],[]},{mod_pottymouth,stop,1,[{file,"src/mod_pottymouth.erl"},{line,48}]},{gen_mod,stop_module_keep_config,2,[{file,"src/gen_mod.erl"},{line,135}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{ejabberd_app,prep_stop,1,[{file,"src/ejabberd_app.erl"},{line,86}]},{application_master,prep_stop,2,[{file,"application_master.erl"},{line,377}]},{application_master,loop_it,4,[{file,"application_master.erl"},{line,353}]}]}`

and messages sent in group chat are not filtering words that are specified in blacklist.

I am using version 16.02.79 of ejabberd.
I do not know erlang, so I am not sure how to debug this issue.

**Comment by badlop** [comment]
Replied here: https://www.ejabberd.im/forum/25595/module-pottymouth-not-working

**Comment by tquackenbush** [comment]
This should be fixed in https://github.com/processone/ejabberd-contrib/pull/223
