### ISSUE TITLE
mod_s2s_log breaks s2s access restrictions

### ISSUE THREAD

**Issue by kittey** [processone/ejabberd-contrib#193]
When mod_s2s_log is enabled, ejabberd connects to other servers that should be denied by the s2s access restrictions.

I had mod_s2s_log enabled like this:
```
  mod_s2s_log:
    filename: "/var/log/ejabberd/s2s.log"
```
It was logging s2s connections to that file, as expected.

And I have these access restrictions:
```
s2s_access: s2s

access_rules:
  s2s:
    ## Unusable file transfer proxies
    - deny:
      - server: "proxy.eu.jabber.org"
    - deny:
      - server: "proxy.jabber.ru"
    - allow
```

When mod_s2s_log is enabled, ejabberd happily connects to the two proxy servers (or tries to), even though they should be denied.
When I disable mod_s2s_log, connections to the two proxy servers are denied as expected.

I'm using ejabberd 16.09 and mod_s2s_log 2016.09.12, the most recent versions available from the Debian stable backports repository.

mod_s2s_log also causes these errors and warnings, which may or may not be relevant:
```
# Starting daemon
2017-01-16 01:45:59.763 [warning] <0.38.0>@gen_mod:validate_opts:339
 module 'mod_s2s_log' doesn't export mod_opt_type/1
2017-01-16 01:45:59.830 [warning] <0.38.0>@gen_mod:validate_opts:339
 module 'mod_s2s_log' doesn't export mod_opt_type/1
# Stopping daemon
2017-01-18 02:08:39.586 [error] <0.38.0>@gen_mod:stop_module_keep_config:213
 {badarg,[{mod_s2s_log,stop,1,[{file,"src/mod_s2s_log.erl"},{line,88}]},
 {gen_mod,stop_module_keep_config,2,[{file,"src/gen_mod.erl"},{line,212}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,prep_stop,1,[{file,"src/ejabberd_app.erl"},{line,93}]},
 {application_master,prep_stop,2,[{file,"application_master.erl"},{line,376}]},
 {application_master,loop_it,4,[{file,"application_master.erl"},{line,352}]}]}
2017-01-18 02:08:39.908 [error] <0.8455.0>@ejabberd_hooks:run1:332
 {badarg,[{mod_s2s_log,s2s_connect,2,[{file,"src/mod_s2s_log.erl"},{line,92}]},
 {ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},
 {ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},
 {ejabberd_s2s_out,wait_for_features,2,[{file,"src/ejabberd_s2s_out.erl"},{line,567}]},
 {p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
2017-01-18 02:08:39.911 [error] <0.8453.0>@ejabberd_hooks:run1:332
 {badarg,[{mod_s2s_log,s2s_connect,2,[{file,"src/mod_s2s_log.erl"},{line,92}]},
 {ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},
 {ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},
 {ejabberd_s2s_out,wait_for_features,2,[{file,"src/ejabberd_s2s_out.erl"},{line,567}]},
 {p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
2017-01-18 02:08:39.911 [error] <0.8452.0>@ejabberd_hooks:run1:332
 {badarg,[{mod_s2s_log,s2s_connect,2,[{file,"src/mod_s2s_log.erl"},{line,92}]},
 {ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},
 {ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},
 {ejabberd_s2s_out,wait_for_features,2,[{file,"src/ejabberd_s2s_out.erl"},{line,567}]},
 {p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
2017-01-18 02:08:39.954 [error] <0.8454.0>@ejabberd_hooks:run1:332
 {badarg,[{mod_s2s_log,s2s_connect,2,[{file,"src/mod_s2s_log.erl"},{line,92}]},
 {ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},
 {ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},
 {ejabberd_s2s_out,wait_for_features,2,[{file,"src/ejabberd_s2s_out.erl"},{line,567}]},
 {p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
```

**Comment by badlop** [comment]
The warnings are harmless, the errors indicate you have several vhosts. I get all that too, no relevant I think.

I tried 16.09 from git + module from git (no changes in that module code since a year ago), and your config, and it works correctly for me: denied servers return error without even attempting to connect, and other ones are at least attempted. Enabling or disabling the module does not affect that behavior.

So, make more tests to maybe find more clues about the problem:
* when the module is enabled, login to the server with a powerful Jabber client (Psi, Gajim, Tkabber...), open its Service Discovery and try to discover proxy.jabber.ru. Does it return error immediately?
* Then try to discover proxy.jabber111.ru which doesn't even exist,
* and upload.jabber.ru which exists.
* In your config, deny also upload.jabber.ru, and try again to discover it.

**Comment by kittey** [comment]
Well, what can I say: I can’t reproduce it anymore. I went back to the previous configuration file with mod_s2s_log enabled but now the problem doesn’t appear anymore. s2s connections are denied as expected. :-?

I guess I didn’t test it enough because I didn’t want to bother the few dozens of users on the server too much. Sorry for needlessly kicking up dust.

Thanks for the info about the errors. And yes, I have several vhosts.
