### ISSUE TITLE
ejabberd 17.01 mod_post_log.erl compilation error

### ISSUE THREAD

**Issue by ForGuru** [processone/ejabberd-contrib#195]
I am unable to compile mod_post_log.erl on ejabberd 17.01 
Any idea to get it working ?

/opt/ejabberd-17.01/lib/ejabberd-17.01/include/jlib.hrl:21: can't find include file "ns.hrl"
/opt/ejabberd-17.01/lib/ejabberd-17.01/include/jlib.hrl:22: can't find include file "fxml.hrl"
/opt/ejabberd-17.01/lib/ejabberd-17.01/include/jlib.hrl:426: record xmlel undefined
/opt/ejabberd-17.01/lib/ejabberd-17.01/include/jlib.hrl:466: type xmlel() undefined
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:43: record xmlel undefined
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:49: record xmlel undefined
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:50: variable 'Attrs' is unbound
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:60: record xmlel undefined
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:61: variable 'Els' is unbound
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:113: record xmlel undefined
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:114: record xmlel undefined
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:117: record xmlel undefined
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:118: variable 'InnerEls' is unbound
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:13: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
ejabberd-contrib/mod_post_log/src/mod_post_log.erl:13: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')

**Comment by zinid** [comment]
Well, it gets compiled if put inside ejabberd's `src` directory, but doesn't work because it should be updated to support new ejabberd code.

**Comment by zinid** [comment]
Support for ejabberd 16.12+ is added in 3dc4494ee184f033b21a992676f1935c174b2577
