### ISSUE TITLE
Modules don't working on ejabberd 16.12+

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd-contrib#197]
I'm trying to upgrade ejabberd 16.09 to 17.01 but I have problem with mod_logsession, mod_statsdx and mod_webpresence - the first two when are enabled blocks start of ejabberd, all of them gives error when installing / upgrading:
```
root@virtualbox:/var/log/ejabberd# ejabberdctl module_upgrade mod_logsession
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{filename,join,
                       [{error,bad_name},"include"],
                       [{file,"filename.erl"},{line,406}]},
             {ext_mod,'-compile_options/0-lc$^0/1-0-',1,
                      [{file,"src/ext_mod.erl"},{line,520}]},
             {ext_mod,compile_options,0,[{file,"src/ext_mod.erl"},{line,520}]},
             {ext_mod,compile,1,[{file,"src/ext_mod.erl"},{line,500}]},
             {ext_mod,compile_and_install,2,
                      [{file,"src/ext_mod.erl"},{line,471}]},
             {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,171}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,329}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]}]
root@virtualbox:/var/log/ejabberd# ejabberdctl module_upgrade mod_statsdx                                       
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{filename,join,
                       [{error,bad_name},"include"],
                       [{file,"filename.erl"},{line,406}]},
             {ext_mod,'-compile_options/0-lc$^0/1-0-',1,
                      [{file,"src/ext_mod.erl"},{line,520}]},
             {ext_mod,compile_options,0,[{file,"src/ext_mod.erl"},{line,520}]},
             {ext_mod,compile,1,[{file,"src/ext_mod.erl"},{line,500}]},
             {ext_mod,compile_and_install,2,
                      [{file,"src/ext_mod.erl"},{line,471}]},
             {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,171}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,329}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]}]
root@virtualbox:/var/log/ejabberd# ejabberdctl module_upgrade mod_webpresence                                   
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{filename,join,
                       [{error,bad_name},"include"],
                       [{file,"filename.erl"},{line,406}]},
             {ext_mod,'-compile_options/0-lc$^0/1-0-',1,
                      [{file,"src/ext_mod.erl"},{line,520}]},
             {ext_mod,compile_options,0,[{file,"src/ext_mod.erl"},{line,520}]},
             {ext_mod,compile,1,[{file,"src/ext_mod.erl"},{line,500}]},
             {ext_mod,compile_and_install,2,
                      [{file,"src/ext_mod.erl"},{line,471}]},
             {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,171}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,329}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,298}]}]
```

**Comment by zinid** [comment]
Yes, all those modules should be ported to use new API

**Comment by safwank** [comment]
Any update on this? 

Also @zinid can you please elaborate on what you mean by the "new API"? Thanks.

**Comment by zinid** [comment]
The new API means new internal structures and hooks: ejabberd doesn't use XML structures anymore, and arguments of most hooks have changed.

**Comment by ffringel** [comment]
Hello @zinid @mremond, I'm interested in participating in this year GSOC. As a start/getting used to the Ejabberd codebase, I'm looking at porting those modules to use the new API. Besides [this tutorials ](https://blog.process-one.net/ejabberd-16-12/), I haven't seen much to get me going.

**Comment by zinid** [comment]
@ffringel ejabberd has never had documented internal code (aka internal API), like 99% of any other software. So you basically need to read the code to understand what's going on. And this is especially true if you're a GSoC student: when you're hired, nobody will nurse with you providing code documentation or teaching you how to (re)write particular piece of code of a project.

**Comment by badlop** [comment]
> {error,bad_name}

This is returned by code:lib_dir(App) when App is an erlang library badly installed. ext_mod.erl calls that function asking for fast_xml, xmpp and ejabberd. I suspect there's some problem in your installation. For example, in an erlang shell in my ejabberd node, this works for me, but I guess it will fail for you:

> (ejabberd@localhost)1> code:lib_dir(fast_xml).
"//lib/fast_xml-1.1.21"
(ejabberd@localhost)2> code:lib_dir(xmpp).    
"//lib/xmpp-1.1.8"
(ejabberd@localhost)3> code:lib_dir(ejabberd).
"//lib/ejabberd-17.01"

Can you try those calls youself, to know which library is problematic? And how did you install ejabberd 17.01? some installer, or package, or source code, or git...

**Comment by beherit** [comment]
@badlop I installed ejabberd via Debian repo from jabber.at. I have this problem on 3 servers :(

**Comment by zinid** [comment]
@ffringel I have spent some time and wrote a brief [development guide](https://github.com/processone/ejabberd/blob/api-guide/API.md).
Hope this will help.

**Comment by badlop** [comment]
Umm, the URL https://github.com/processone/ejabberd/blob/api-guide/API.md returns 404

**Comment by cromain** [comment]
this has been moved to official ejabberd documentation and will be available soon on docs.ejabberd.im

**Comment by zinid** [comment]
For the record, new [XMPP library](https://github.com/processone/xmpp) is now also documented:
- [README](https://github.com/processone/xmpp/blob/master/README.md)
- [API](https://github.com/processone/xmpp/blob/master/doc/API.md)

There are still minor issues in it, but I will fix them by 17.03 release.

**Comment by ffringel** [comment]
@zinid thanks a lot. The XMPP library documentation was very helpful.

**Comment by zinid** [comment]
> Umm, the URL https://github.com/processone/ejabberd/blob/api-guide/API.md returns 404

Here is a somewhat old draft, but it's better to have something until the doc is published officially: https://gist.github.com/zinid/410507ca8b2e32738a388800a8412e9e

**Comment by badlop** [comment]
With ejabberd 17.03 compiled from source I can install mod_statsdx, upgrade, and tested it basically works. It only throws a warning about undefined callback. Same with 17.01 installed from official installers.

**Comment by cromain** [comment]
Updated guide included in official documentation
https://docs.ejabberd.im/developer/guide/

**Comment by mathiasertl** [comment]
As far as I can tell, this issue is basically solved. @beherit uses my packages, my packages currently miss a patch for compiling modules, because the old one from @weiss ([this one](https://github.com/jabber-at/ejabberd/blob/master/debian/patches/src.ext_mod.erl.patch) does not apply anymore. I'm working with @weiss on a fix. I think this ticket here can be closed.
