### ISSUE TITLE
undefined function hipe_bifs:bitarray  when running mod_pottymouth

### ISSUE THREAD

**Issue by brian-w-smith** [processone/ejabberd-contrib#198]
Using ejabberd 17.01,  mod_pottymouth was installed via ejabberdctl and after a restart the following appear in ejabberd.log:
```
2017-03-08 19:25:13.423 [info] <0.2405.0>@bloom_gen_server:init:27
 Building bloom '/etc/ejabberd/modules/mod_pottymouth/blacklist_en.txt'
2017-03-08 19:25:13.429 [error] <0.2405.0> CRASH REPORT Process <0.2405.0>
 with 0 neighbours exited with reason:
 call to undefined function hipe_bifs:bitarray(16777216, false) in gen_server:init_it/6 line 330
```
The blacklist file exists and a reference was added to conf/ejabberd.yml
 Below is the crash report:
```
2017-03-08 19:25:13 =CRASH REPORT====
  crasher:
    initial call: bloom_gen_server:init/1
    pid: <0.2467.0>
    registered_name: []
    exception exit:
 {{undef,[{hipe_bifs,bitarray,[16777216,false],[]},{etbloom,'-bloom/3-lc$^0/1-0-',2,
[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_pottymouth/src/etbloom.erl"},{line,77}]},
{etbloom,bloom,3,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_pottymouth/src/etbloom.erl"},{line,77}]},
{etbloom,sbf,4,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_pottymouth/src/etbloom.erl"},{line,98}]},
{bloom_gen_server,init,1,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_pottymouth/src/bloom_gen_server.erl"},{line,28}]},
{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},
[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,330}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [<0.1958.0>]
    messages: []
    links: [<0.1958.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 631
  neighbours:
```

**Comment by brian-w-smith** [comment]
The issue occurred on Debian 8.  hipe-3.11.1 is installed in /usr/lib/erlang/lib

**Comment by brian-w-smith** [comment]
Was able to work around the issue by using a different bitarray module than hipe_bif.  the one i used was:  https://github.com/ferd/bitarray

**Comment by tquackenbush** [comment]
@badlop question for you... I've made changes to mod_pottymouth to switch etbloom to use bitarray, but if I were to commit these changes upstream, I was wondering what is the best way for an ejabberd-contrib modules to define and install dependencies? like if I have my modified etbloom as a dep, with bitarray as a dep of etbloom, is modules_install clever enough to install all the deps? In my local testing I've been able to get it to install the etbloom dep, but not the bitarray dep defined in etbloom...

**Comment by tquackenbush** [comment]
I tired putting the bitarray repo in the top level deps directory, so it seems to be installed along with etbloom. but...

It seems to be hung up on this NIF library that bitarray requires that doesn't seem to be copied during modules_install...

```
ejabberd_1  | 00:04:01.441 [error] The on_load function for module bitarray returned {error,{load_failed,"Failed to load NIF library: '/opt/ejabberd/.ejabberd-modules/mod_pottymouth/ebin/../priv/bitarray.so: cannot open shared object file: No such file or directory'"}}
ejabberd_1  | 00:04:01.442 [error] CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: call to undefined function bitarray:new(16777216, false) in gen_server:init_it/6 line 330
```

**Comment by badlop** [comment]
When a module in ejabberd-contrib requires a library, the only solution I found so far is to copy all the library repo inside deps/, see ejabberd_auth_http.

**Comment by tquackenbush** [comment]
This should be fixed in https://github.com/processone/ejabberd-contrib/pull/223
