### ISSUE TITLE
mod_restful error

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd-contrib#199]
[mod-restful-register-error.txt](https://github.com/processone/ejabberd-contrib/files/830001/mod-restful-register-error.txt)

[mod-restful-error.txt](https://github.com/processone/ejabberd-contrib/files/830002/mod-restful-error.txt)

[mod-restful-admin-error.txt](https://github.com/processone/ejabberd-contrib/files/830009/mod-restful-admin-error.txt)

[gen-restful-api-error.txt](https://github.com/processone/ejabberd-contrib/files/830010/gen-restful-api-error.txt)

I get all these 4 errors when i try to compile "mod_restful".

I understand it is a 3rd party work from other source, but funny thing i get the beam file produce for the 2nd compile under "ebin" folder for the "mod_restful.erl".  As for others it does not produce any beam file.

Any suggestion or comments?

**Comment by badlop** [comment]
Edit those files, replacing the lines
> -include("include/mod_restful.hrl").

with
> -include("mod_restful.hrl").

**Comment by molochmike** [comment]
Hi badlop,

thanks for the recommendation.  I have done as mention and the only thing i get is at the end is a text mentioned "conflict" when i use the ejabberdctl command to install this mod_restful.  But after i issue command "ejabberdctl modules_update_specs" no errors has been displayed except just to show me that mod_rest and mod_restful module has been installed.  Previously when i do this the error for the gen_mod_restful and others will appear.

Does this mean it is ok for me now to be able to use the mod_restful command?  Appreciate the comment.  Thanks.

**Comment by molochmike** [comment]
Hi badlop,

The error is still same although i have manage to install the "mod_restful".  Please see the attached below for the error after install the mod_restful.

<img width="955" alt="conflict-error-170316" src="https://cloud.githubusercontent.com/assets/15246261/23984267/a1cbad3a-0a53-11e7-9551-ea6bc8931c8c.png">

<img width="1280" alt="gen-restful-api-error-170316" src="https://cloud.githubusercontent.com/assets/15246261/23984283/bf1abc3c-0a53-11e7-9ca9-3a7e53342a73.png">

<img width="1278" alt="mod-restful-admin-erl-error-170316" src="https://cloud.githubusercontent.com/assets/15246261/23984297/d10ca52c-0a53-11e7-859b-4f1ddaac527e.png">

<img width="1279" alt="mod-restful-erl-error-170316" src="https://cloud.githubusercontent.com/assets/15246261/23984311/e618d40e-0a53-11e7-96c4-714f3374581d.png">

<img width="1280" alt="mod-restful-register-erl-error-170316" src="https://cloud.githubusercontent.com/assets/15246261/23984329/fc9de318-0a53-11e7-955a-20e2973e5dbf.png">

**Comment by badlop** [comment]
I think the warnings are harmless. The error regarding *.hrl files, maybe you can solve by providing also -I with the ejabberd/include/ dir.

**Comment by molochmike** [comment]
Hi badlop,

Thanks for the feedback.  When you say to include the "-I" with the ejabberd/include/ dir do you mean by the syntax below?

./erlc -I ~/.ejabberd-modules/sources/mod_restful/include -o ~/.ejabberd-modules/sources/mod_restful/ebin -I ~/.ejabberd-modules/sources/mod_restful/src/mod_restful_register.erl

**Comment by badlop** [comment]
> When you say to include the "-I" with the ejabberd/include/ dir do you mean by the syntax below? 

I mean to provide it in whatever good place you can find, so that the compiler uses it to compile and doesn't complain :)

> I have specify the option "-I" after the syntax ebin and when i enter, no error appear, is that what you mean?

If it doesn't throw any error, and produces the *.beam file, then you should be happy, install that beam file, enable the module, restart ejabberd and try it.

**Comment by molochmike** [comment]
Hi badlop,

Thanks for the feedback.  Truly appreciate it.  Will try and test it out.

**Comment by molochmike** [comment]
Hi badlop,

Just 2 question to get your comments.

1)  What's the different between implementing mod_rest & mod_restful?
2)  What would happen when both are installed and enable?  Will it cause any issue?

Thanks.

**Comment by badlop** [comment]
> What's the different between implementing mod_rest & mod_restful?

I don't know, but looking at their pages, they are quite different.

> What would happen when both are installed and enable? Will it cause any issue?

Apparently they are quite different, there probably is not any problem.

**Comment by molochmike** [comment]
Hi badlop,

I have move away the 17.03.beta version.  Will be setting up 17.03 stable shortwhile.  Yes, looking at it pages are different on mod_rest vs mod_restful.  I think what i will do is setup mod_http_api and mod_rest just to see how it works in this current 17.03 stable version.

I guess mod_restful don't work out for me as it has the error log generated "opt/1" some error from the ejabberd log file.  I do not know and have try to get it fix but not working.

**Comment by molochmike** [comment]
Hi @badlop 

Still not working.  I have move away now to use the version 17.03 stable.  However I got problem with OAUTH token.  Are you able to help me?  I have posted on github.  Below is the issue reference link.

https://github.com/processone/ejabberd/issues/1661

Appreciate the help.
