### ISSUE TITLE
Mod_archive ejabberd 17

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd-contrib#204]
I installed ejabberd 17 (with a deb package)

But the archive stays empty.
In the the ejabberd.yml i added:   mod_archive: {}
and in the dashboard:   mod_archive    []

I also tried with
mod_archive:
    save_default: true

mod_archive  [{save_default, true}]

But the archive stays empty.
How can I enable it?

_The error.log shows:
2017-03-14 10:31:51.377 [error] <0.39.0>@gen_mod:stop_module_keep_config:213 {noproc,{gen_server,call,['ejabberd_mod_archive_----my-vhost---',stop]}}_

Besides 1on1 chats archiving is there also an option to archive a groups chat?

**Comment by weiss** [comment]
The [README file][1] says:

> Those modules do NOT work with ejabberd 13 or newer.

You might want to look into [`mod_mam`][2] (which implements [XEP-0313][3]) instead.

> Besides 1on1 chats archiving is there also an option to archive a groups chat?'

`mod_mam` supports group chat.

[1]: https://raw.githubusercontent.com/processone/ejabberd-contrib/master/mod_archive/README.txt
[2]: https://docs.ejabberd.im/admin/configuration/#modmam
[3]: https://xmpp.org/extensions/xep-0313.html

**Comment by PH-F** [comment]
Thank you this works!

But was a bit confused, because ./ejabberdctl modules_available shows mod_archive
As it is not possible to use this module, it makes no sense that this module is available right?

// issue can be closed

**Comment by zinid** [comment]
The command only lists all available modules in `ejabberd-contrib` repo, it doesn't check compatibility as it's hard to do programmatically.
