### ISSUE TITLE
mod_post_log on ejabberd 17

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd-contrib#205]
I Installed mod_post_log in ejabberd 17, added it to the yml file and rebooted ejabberd
```
modules:
  mod_post_log:
    url: http://..<url>../log.php
```

But nothing is logged, what do need to do to enable this?

**Comment by badlop** [comment]
It should surely log some error:: I tried with ejabberd git, and the module throws error when a user sends a message stanza:
```
15:42:58.575 [error] Hook user_send_packet crashed when running mod_post_log:log_user_send/1:
** Reason = {error,badarg,[{re,run,[],['http://loaclhost/log.php',":",[{capture,first}]]},...
** Arguments = [{{message,<<"52:849784">>,chat,...
```
Set loglevel to 5 in ejabberd configuration file, it should log something like this at start:
```
15:52:52.637 [debug] loading mod_post_log at localhost
```

**Comment by cC-Xx** [comment]
hi 
same here 
ejabberd 21.01 
latest mod_proc_log crashing 
how to resolve? 
thanks
