### ISSUE TITLE
web admin user link  not showing data after switch the mysql database

### ISSUE THREAD

**Issue by kaalees** [processone/ejabberd-contrib#213]
I got below the message in crash.log
crasher:
    initial call: ejabberd_http:init/2
    pid: <0.4014.0>
    registered_name: []
    exception error: {function_clause,[{sql_queries,list_users,[<<"localhost">>,[]],[{file,"src/sql_queries.erl"},{line,212}]},{ejabberd_auth_sql,get_users,2,[{file,"src/ejabbe$
    ancestors: [<0.3729.0>,ejabberd_listener,ejabberd_sup,<0.3470.0>]
    messages: []
    links: [#Port<0.114446>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 1620

**Comment by zinid** [comment]
If you don't want to describe the problem, at least, don't truncate the crash reports.

**Comment by kaalees** [comment]
The same error is repeating my crash.log. Actually my problem is after enabled mysql i changed auth_method: internal to auth_method: sql as followed by this link https://docs.ejabberd.im/admin/guide/databases/mysql/#configure-desired-authentication-backend
i got the above the crash error

**Comment by zinid** [comment]
I have already fixed this, this was the problem in ejabberd, not in contrib modules.

**Comment by kaalees** [comment]
okay, can you post link here?

**Comment by zinid** [comment]
Link to what? Do you see the notification above?

**Comment by kaalees** [comment]
i got it thanks very much
