### ISSUE TITLE
mod_logxml fails to start in ejabberd 17

### ISSUE THREAD

**Issue by jploski** [processone/ejabberd-contrib#216]
Using the exact configuration from mod_logxml module's README.txt and ejabberd Docker image rroemhild/ejabberd:17.01 or rroemhild/ejabberd:17.03, here's what I get:
```
2017-06-12 13:23:58.176 [critical] <0.38.0>@gen_mod:start_module:162 Problem starting the module mod_logxml for host <<"xxxxxxxx.com">>
 options: [{stanza,[iq,other]},
           {direction,[external]},
           {orientation,[send,recv]},
           {logdir,<<"/tmp/logs/">>},
           {timezone,universal},
           {show_ip,false},
           {rotate_days,1},
           {rotate_megs,100},
           {rotate_kpackets,no},
           {check_rotate_kpackets,1}]
 error: undef
[{mod_logxml,start,
             [<<"xxxxxxxx.com">>,
              [{stanza,[iq,other]},
               {direction,[external]},
               {orientation,[send,recv]},
               {logdir,<<"/tmp/logs/">>},
               {timezone,universal},
               {show_ip,false},
               {rotate_days,1},
               {rotate_megs,100},
               {rotate_kpackets,no},
               {check_rotate_kpackets,1}]],
             []},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,154}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,77}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,272}]}]
2017-06-12 13:23:58.176 [critical] <0.38.0>@gen_mod:maybe_halt_ejabberd:170 ejabberd initialization was aborted because a module start failed.
```
I checked that mod_logxml.erl in the container matches commit 5359c2a0dd916dd7a4efcb3eb8089b30ed738acb
I didn't manage to find a workaround for the above start error.

**Comment by badlop** [comment]
The error message says that the function mod_logxml:start with two arguments is undefined. This surely means erlang couldn't find the file mod_logxml.beam 

What's the practical problem, and how to solve it, depends on how you installed that contributed module.

**Comment by tungd** [comment]
I think he uses uses `modules_update_specs`/`module_install`. These commands work on CentOS, but not Debian. On both system I installed Ejabberd from the packaged `.deb`/`.rpm`.

My quick workaround is to copy the module `.beam` file from `.ejabberd-modules/<mod_name>/ebin/<mod_name>.beam` to `lib/ejabberd-<version>/ebin`.

**Comment by badlop** [comment]
I installed ejabberd-17.07-linux-x86_64-installer.run in my debian machine, then run
```
$ ./ejabberdctl modules_update_specs
$ ./ejabberdctl module_install mod_logxml
```
The module was compiled, installed, started with its default config, and it started logging already.

**Comment by jploski** [comment]
Sorry for the late reply. This ticket did not concern the manual *installation* of the module. Rather, it concerns that the pre-installed version from the Docker image provided by https://hub.docker.com/r/rroemhild/ejabberd/ does not work. The .beam file was already contained in the image, so I assumed that the module was installed - yet it did not start (as reported).

**Comment by badlop** [comment]
Then you better contact the author of the corresponding package.

**Comment by andrescueva** [comment]
I tried to install mod_logxml, but is I got an error. Do you know how to solve it.

user@ejabberd:~/ejabberd-18.12/bin$ ./ejabberdctl module_install mod_logxml

/home/dcuioit/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl:12: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
/home/dcuioit/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl:12: Warning: undefined callback function mod_options/1 (behaviour 'gen_mod')
=ERROR REPORT==== 5-Feb-2019::16:36:34.691847 ===
Error in process <7529.3629.0> on node ejabberd@localhost with exit value:
{undef,[{jlib,timestamp_to_legacy,[{{2019,2,5},{21,36,34}}],[]},
        {mod_logxml,get_now_iso,1,
                    [{file,"/home/dcuioit/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl"},
                     {line,272}]},
        {mod_logxml,open_file,3,
                    [{file,"/home/dcuioit/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl"},
                     {line,215}]},
        {mod_logxml,init,7,
                    [{file,"/home/dcuioit/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl"},
                     {line,66}]}]}
