### ISSUE TITLE
mod_logxml compilation failed ejabberd 17

### ISSUE THREAD

**Issue by interda** [processone/ejabberd-contrib#218]
```
ejabberdctl module_install mod_logxml
/var/spool/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/
mod_logxml.erl:174: syntax error before: '}'

/var/spool/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/
mod_logxml.erl:14: function receive_packet/1 undefined

/var/spool/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/
mod_logxml.erl:12: Warning: undefined callback function depends/2 (behaviour 'gen_mod')

/var/spool/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/
mod_logxml.erl:12: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')

Error: {compilation_failed,"/var/spool/ejabberd/.ejabberd-modules/sources/
ejabberd-contrib/mod_logxml/src/mod_logxml.erl"}
```

**Comment by badlop** [comment]
Thanks for reporting! Please update git, and check if now everything works correctly.

**Comment by interda** [comment]
After update also faild. 
 `/var/spool/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl:12: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
/var/spool/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl:12: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')`

**Comment by badlop** [comment]
Those are only warnings, not errors, and I think they do not affect the module . It should work correctly.
