### ISSUE TITLE
Even on disabling the SCRAM , the server uses get_password in ejabberd_auth_http

### ISSUE THREAD

**Issue by satish-olx** [processone/ejabberd-contrib#222]
Hi,
Using 17.07 somehow has broken the ejabberd_auth_http. The function get_password/2 is called, even when SCRAM has been disabled. Any way out of this ?

**Comment by badlop** [comment]
So, now that module doesn't work when disabling SCRAM? What was the previous ejabberd version that worked correctly?

**Comment by hiteshsondhi88** [comment]
I guess this is the same issue I am facing #228

**Comment by cromain** [comment]
closing this issue, may be fixed by patch provided on #228.
full module upgrade tracked on #230
