### ISSUE TITLE
How to make sure ejabberd_auth_http module use custom auth token strategy rather then  plaintext passwords

### ISSUE THREAD

**Issue by hiteshsondhi88** [processone/ejabberd-contrib#228]
I am trying to authenticate ejabberd with custom backend which uses auth token. However whenever I am trying to authenticate a user it looks like it is using plain text password strategy rather then auth token.

Request I am sending to server:
```xml
<auth
 xmlns='urn:ietf:params:xml:ns:xmpp-sasl'
 mechanism='PLAIN'>Some long string here</auth>
```
After this request server is sending get_password request to api which shouldn't be required for authentication token strategy.

How to make sure module is forced to use auth token strategy ?

Thanks.

**Comment by hiteshsondhi88** [comment]
Tried the same config on 17.04 and it works fine.

I think this [commit](https://github.com/processone/ejabberd/commit/633b68db1130c81551b063f3aa15d599b0d355e5#diff-edd5be73a8be16780786318f0f983ce0) which is changing ejabberd_auth file causes the trouble

db_check_password -> calls db_get_password everytime which is the root of trouble

**Comment by hiteshsondhi88** [comment]
Able to sort this issue even on latest ejabberd by changing few lines of code in ejabberd_auth_http.erl. Still keeping a note here incase if anyone stumble across the same -
> Modify
```
-spec store_type(binary()) -> plain | scram.
store_type(Server) ->
    ejabberd_auth:password_format(Server).`
```
> to
```
-spec store_type(binary()) -> external.
    store_type(_) -> external.
```
> Modify
```
-spec get_password(ejabberd:luser(), ejabberd:lserver()) -> false | binary() |
                                          {binary(), binary(), binary(), integer()}.
get_password(LUser, LServer) ->
    case make_req(get, <<"get_password">>, LUser, LServer, <<"">>) of
        {error, _} ->
            false;
        {ok, Password} ->
            case scram2:enabled(LServer) of
                true ->
                    case scram2:deserialize(Password) of
                        {ok, #scram{} = Scram} ->
                            scram2:scram_to_tuple(Scram);
                        _ ->
                            false
                    end;
                false ->
                    Password
            end
    end.
```
> to
```
-spec get_password(ejabberd:luser(), ejabberd:lserver()) -> error.
    get_password(_, _) -> error.
```

Closing the issue.

**Comment by cromain** [comment]
can you please provide a clean PR for this ?

**Comment by hiteshsondhi88** [comment]
Hi @cromain I would have but I am real bad with erlang to create a clean patch

**Comment by cromain** [comment]
@badlop can you create a clean PR from patch proposed here ?

**Comment by badlop** [comment]
I've committed the proposed change.

**Comment by tsaqova** [comment]
@badlop @hiteshsondhi88 @cromain 
change the store_type to `external` make SCRAM-SHA-1 disappear SASL feature list:
https://github.com/processone/ejabberd/blob/master/src/cyrsasl.erl#L164
is it intended? I use ejabberd_auth_http & auth_password_format: scram in my config.

**Comment by tsaqova** [comment]
Can anyone answer my question above?
Currently, I created a workaround for my apps because of this patch.
I would gladly contribute if needed.
