### ISSUE TITLE
mod_grafite does not support recent ejabberd changes

### ISSUE THREAD

**Issue by EmMerry** [processone/ejabberd-contrib#234]
-- What version of ejabberd are you using?
17.12

-- What operating system (version) are you using?
Centos 7.4

-- How did you install ejabberd (source, package, distribution)?
sources

Actually i am looking for Ejabberd monitoring tool. I found Grapherl but could not integrate it with ejabberd to run. Also the official Ejabberd's site says that the server is configurable with nagios monitoring, i also could not find any nagios plugin for ejabberd monitoring. I am also not able to run the mod_grafite module with ejabberd Have anyone done this, please share.

**Comment by BhattiMarry** [comment]
Here is the log info when i install mod_grafite.
`2018-01-04 01:25:15.524 [info] <0.370.0>@ejabberd_listener:init_tcp:140 Start accepting TCP connections at [::]:5280 for ejabberd_http`

`2018-01-04 01:25:15.524 [info] <0.369.0>@ejabberd_listener:init_tcp:140 Start accepting TCP connections at [::]:5269 for ejabberd_s2s_in`

`2018-01-04 01:25:15.524 [info] <0.368.0>@ejabberd_listener:init_tcp:140 Start accepting TCP connections at [::]:5222 for ejabberd_c2s`

`2018-01-04 01:26:03.344 [info] <0.529.0>@ext_mod:update:157 Update packages from repo git@github.com:jadahl/mod_restful.git: ok`

`2018-01-04 01:26:06.844 [info] <0.529.0>@ext_mod:update:157 Update packages from repo git@github.com:kongo2002/ejabberd-mod-mam.git: ok`

`2018-01-04 01:26:12.472 [info] <0.529.0>@ext_mod:update:157 Update packages from repo git@github.com:lavrin/ejabberd-trace.git: ok`

`2018-01-04 01:26:24.490 [info] <0.529.0>@ext_mod:update:157 Update packages from repo git@github.com:processone/ejabberd-contrib.git: ok`

`2018-01-04 01:26:27.627 [info] <0.529.0>@ext_mod:update:157 Update packages from repo git@github.com:raelmax/mod_http_offline.git: ok`

`2018-01-04 01:26:45.287 [info] <0.529.0>@ext_mod:update:157 Update packages from repo https://github.com/processone/ejabberd-contrib: ok`

`2018-01-04 01:27:26.001 [critical] <0.572.0>@gen_mod:start_module:212 Problem starting the module mod_grafite for host 192.168.122.200
 options: [{statsdhost,<<"192.168.122.201">>},{statsdport,8125}]
 error: true
[{gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,203}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {gen_mod,reload_modules,1,[{file,"src/gen_mod.erl"},{line,235}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {ejabberd_hooks,safe_apply,4,[{file,"src/ejabberd_hooks.erl"},{line,380}]},
 {ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},
 {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,220}]},
 {ejabberd_ctl,call_command,4,[{file,"src/ejabberd_ctl.erl"},{line,352}]}]`

`2018-01-04 01:27:26.001 [error] <0.572.0>@ejabberd_hooks:safe_apply:383 Hook config_reloaded crashed when running gen_mod:config_reloaded/0:
** Reason = {error,true,[{gen_mod,start_module,[{file,"src/gen_mod.erl"},{line,203}],4},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{gen_mod,reload_modules,[{file,"src/gen_mod.erl"},{line,235}],1},{lists,foreach,[{file,"lists.erl"},{line,1338}],2},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run1,[{file,"src/ejabberd_hooks.erl"},{line,329}],3},{ext_mod,install,[{file,"src/ext_mod.erl"},{line,220}],1},{ejabberd_ctl,call_command,[{file,"src/ejabberd_ctl.erl"},{line,352}],4}]}
** Arguments = []`

`2018-01-04 01:27:26.005 [info] <0.646.0>@mod_grafite:udp_loop_start:145 UDP Stats Socket Open: [44444]`

I just updated the modules from repo and installed it.

**Comment by badlop** [comment]
I've updated the module. It now should start correctly. As I didn't test its usage, it may have other problems. Please open a new ticket if it's a different error message, or reopen this one if it still fails like it did before for you.
