### ISSUE TITLE
Error in log while processing Server statistics (mod_statsdx)

### ISSUE THREAD

**Issue by EmMerry** [processone/ejabberd-contrib#235]
I have enabled the mod_statsdx module for my ejabberd server. The modules is not collecting actual stats and showing the following error in ejabberd log.

`2018-01-04 05:48:36.436 [error] <0.2368.0>@ejabberd_hooks:safe_apply:383 Hook user_receive_packet crashed when running mod_statsdx:user_receive_packet_traffic/1:
** Reason = {error,undef,[{mod_statsdx,user_receive_packet_traffic,[],[{{iq,<<"purple865a2dfa">>,result,<<"en">>,{jid,<<"test">>,<<"test-vm.whizpool">>,<<>>,<<"test">>,<<"test-vm.whizpool">>,<<>>},{jid,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>},[],#{ip => {0,0,0,0,0,65535,49320,31233}}},#{shaper => c2s_shaper,stream_timeout => infinity,csi_state => active,zlib => false,mod => ejabberd_c2s,mgmt_stanzas_out => 0,stream_compressed => false,jid => {jid,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>},resource => <<"75639659004047247312084">>,socket_monitor => #Ref<0.2320379203.2545156098.211400>,mgmt_ack_timeout => 60000,pres_timestamp => {1515,62857,280922},server => <<"test-vm.whizpool">>,pres_a => {0,nil},sid => {{1515,62855,9},<0.2368.0>},ip => {{0,0,0,0,0,65535,49320,31233},56434},stream_state => established,socket => {socket_state,gen_tcp,#Port<0.63868>,65536,#Ref<0.2320379203.2545287170.211402>,{maxrate,1000,500.55567824835975,1515062916425045},undefined},conn => c2s,csi_queue => {0,#{}},caps_resources => {1,{{<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>},{caps,<<"http://pidgin.im/">>,<<"AcN1/PEN8nq7AHD+9jpxMV4U6YM=">>,<<"sha-1">>,[<<"voice-v1">>,<<"camera-v1">>,<<"video-v1">>]},nil,nil}},tls_options => [compression_none],stream_authenticated => true,lang => <<"en">>,stream_direction => in,mgmt_stanzas_in => 0,stream_restarted => true,user => <<"test">>,mgmt_timeout => 300,lserver => <<"test-vm.whizpool">>,tls_enabled => false,owner => <0.2368.0>,mgmt_resend => false,tls_required => false,tls_verify => false,stream_header_sent => true,mgmt_state => inactive,stream_version => {1,0},access => c2s,mgmt_stanzas_req => 0,stream_encrypted => false,stream_id => <<"15081401935412123974">>,mgmt_max_timeout => 300,mgmt_queue_type => ram,pres_last => {presence,...},...}}]},...]}
** Arguments = [{{iq,<<"purple865a2dfa">>,result,<<"en">>,{jid,<<"test">>,<<"test-vm.whizpool">>,<<>>,<<"test">>,<<"test-vm.whizpool">>,<<>>},{jid,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>},[],#{ip => {0,0,0,0,0,65535,49320,31233}}},#{shaper => c2s_shaper,stream_timeout => infinity,csi_state => active,zlib => false,mod => ejabberd_c2s,mgmt_stanzas_out => 0,stream_compressed => false,jid => {jid,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>,<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>},resource => <<"75639659004047247312084">>,socket_monitor => #Ref<0.2320379203.2545156098.211400>,mgmt_ack_timeout => 60000,pres_timestamp => {1515,62857,280922},server => <<"test-vm.whizpool">>,pres_a => {0,nil},sid => {{1515,62855,9},<0.2368.0>},ip => {{0,0,0,0,0,65535,49320,31233},56434},stream_state => established,socket => {socket_state,gen_tcp,#Port<0.63868>,65536,#Ref<0.2320379203.2545287170.211402>,{maxrate,1000,500.55567824835975,1515062916425045},undefined},conn => c2s,csi_queue => {0,#{}},caps_resources => {1,{{<<"test">>,<<"test-vm.whizpool">>,<<"75639659004047247312084">>},{caps,<<"http://pidgin.im/">>,<<"AcN1/PEN8nq7AHD+9jpxMV4U6YM=">>,<<"sha-1">>,[<<"voice-v1">>,<<"camera-v1">>,<<"video-v1">>]},nil,nil}},tls_options => [compression_none],stream_authenticated => true,lang => <<"en">>,stream_direction => in,mgmt_stanzas_in => 0,stream_restarted => true,user => <<"test">>,mgmt_timeout => 300,lserver => <<"test-vm.whizpool">>,tls_enabled => false,owner => <0.2368.0>,mgmt_resend => false,tls_required => false,tls_verify => false,stream_header_sent => true,mgmt_state => inactive,stream_version => {1,0},access => c2s,mgmt_stanzas_req => 0,stream_encrypted => false,stream_id => <<"15081401935412123974">>,mgmt_max_timeout => 300,mgmt_queue_type => ram,pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"test">>,<<"t...">>,...},...},...}}]`

This is the one log entry. Its showing the same error on each interval of stats collections.

**Comment by EmMerry** [comment]
Well i am still getting errors in log for this particular module. Let me try it with the updated module. However i am getting some of the stats on Ejabberd portal.

Anyways, here is my server's log snippet.

`2018-01-12 06:16:41.391 [error] <0.551.0>@ejabberd_hooks:safe_apply:383 Hook user_send_packet crashed when running mod_metrics_test:user_send_packet/1:
** Reason = {error,undef,[{mod_metrics_test,user_send_packet,[],[{{iq,<<"purpleace39c71">>,get,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"urn:xmpp:ping">>}],[]}],#{ip => {0,0,0,0,0,65535,49320,25850}}},#{mgmt_max_timeout => 300,sid => {{1515,736210,2},<0.551.0>},pres_timestamp => {1515,755143,400495},mgmt_stanzas_in => 0,zlib => false,mgmt_timeout => 300,mgmt_resend => false,mod => ejabberd_c2s,stream_id => <<"5053099780104229788">>,pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},undefined,[{text,<<>>,<<"looking...">>}],1,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://pidgin.im/">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"AcN1/PEN8nq7AHD+9jpxMV4U6YM=">>},{<<"ext">>,<<"voice-v1 camera-v1 video-v1">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,49320,25850}}},stream_version => {1,0},jid => {jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},mgmt_queue_type => ram,server => <<"test-vm.whizpool">>,mgmt_ack_timeout => 60000,csi_state => active,mgmt_max_queue => 5000,stream_timeout => infinity,ip => {{0,0,0,0,0,65535,49320,25850},42032},socket => {socket_state,gen_tcp,#Port<0.15960>,65536,#Ref<0.2800214629.820903940.155802>,{maxrate,1000,1.6371438238072962,1515755801390713},undefined},mgmt_stanzas_out => 0,socket_monitor => #Ref<0.2800214629.820772865.158698>,csi_queue => {0,#{}},stream_direction => in,stream_compressed => false,tls_options => [compression_none],...}}]},...]}
** Arguments = [{{iq,<<"purpleace39c71">>,get,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"urn:xmpp:ping">>}],[]}],#{ip => {0,0,0,0,0,65535,49320,25850}}},#{mgmt_max_timeout => 300,sid => {{1515,736210,2},<0.551.0>},pres_timestamp => {1515,755143,400495},mgmt_stanzas_in => 0,zlib => false,mgmt_timeout => 300,mgmt_resend => false,mod => ejabberd_c2s,stream_id => <<"5053099780104229788">>,pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},undefined,[{text,<<>>,<<"looking...">>}],1,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://pidgin.im/">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"AcN1/PEN8nq7AHD+9jpxMV4U6YM=">>},{<<"ext">>,<<"voice-v1 camera-v1 video-v1">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,49320,25850}}},stream_version => {1,0},jid => {jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},mgmt_queue_type => ram,server => <<"test-vm.whizpool">>,mgmt_ack_timeout => 60000,csi_state => active,mgmt_max_queue => 5000,stream_timeout => infinity,ip => {{0,0,0,0,0,65535,49320,25850},42032},socket => {socket_state,gen_tcp,#Port<0.15960>,65536,#Ref<0.2800214629.820903940.155802>,{maxrate,1000,1.6371438238072962,1515755801390713},undefined},mgmt_stanzas_out => 0,socket_monitor => #Ref<0.2800214629.820772865.158698>,csi_queue => {0,#{}},stream_direction => in,stream_compressed => false,tls_options => [compression_none],pres_a => {0,nil},stream_header_sent => true,mgmt_state => ...,...}}]`



`2018-01-12 06:16:41.392 [error] <0.551.0>@ejabberd_hooks:safe_apply:383 Hook user_send_packet crashed when running mod_statsdx:user_send_packet/1:
** Reason = {error,undef,[{mod_statsdx,user_send_packet,[],[{{iq,<<"purpleace39c71">>,get,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"urn:xmpp:ping">>}],[]}],#{ip => {0,0,0,0,0,65535,49320,25850}}},#{mgmt_max_timeout => 300,sid => {{1515,736210,2},<0.551.0>},pres_timestamp => {1515,755143,400495},mgmt_stanzas_in => 0,zlib => false,mgmt_timeout => 300,mgmt_resend => false,mod => ejabberd_c2s,stream_id => <<"5053099780104229788">>,pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},undefined,[{text,<<>>,<<"looking...">>}],1,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://pidgin.im/">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"AcN1/PEN8nq7AHD+9jpxMV4U6YM=">>},{<<"ext">>,<<"voice-v1 camera-v1 video-v1">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,49320,25850}}},stream_version => {1,0},jid => {jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},mgmt_queue_type => ram,server => <<"test-vm.whizpool">>,mgmt_ack_timeout => 60000,csi_state => active,mgmt_max_queue => 5000,stream_timeout => infinity,ip => {{0,0,0,0,0,65535,49320,25850},42032},socket => {socket_state,gen_tcp,#Port<0.15960>,65536,#Ref<0.2800214629.820903940.155802>,{maxrate,1000,1.6371438238072962,1515755801390713},undefined},mgmt_stanzas_out => 0,socket_monitor => #Ref<0.2800214629.820772865.158698>,csi_queue => {0,#{}},stream_direction => in,stream_compressed => false,tls_options => [compression_none],pres_a => {...},...}}]},...]}
** Arguments = [{{iq,<<"purpleace39c71">>,get,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},[{xmlel,<<"ping">>,[{<<"xmlns">>,<<"urn:xmpp:ping">>}],[]}],#{ip => {0,0,0,0,0,65535,49320,25850}}},#{mgmt_max_timeout => 300,sid => {{1515,736210,2},<0.551.0>},pres_timestamp => {1515,755143,400495},mgmt_stanzas_in => 0,zlib => false,mgmt_timeout => 300,mgmt_resend => false,mod => ejabberd_c2s,stream_id => <<"5053099780104229788">>,pres_last => {presence,<<>>,available,<<"en">>,{jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},{jid,<<"marry">>,<<"test-vm.whizpool">>,<<>>,<<"marry">>,<<"test-vm.whizpool">>,<<>>},undefined,[{text,<<>>,<<"looking...">>}],1,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"node">>,<<"http://pidgin.im/">>},{<<"hash">>,<<"sha-1">>},{<<"ver">>,<<"AcN1/PEN8nq7AHD+9jpxMV4U6YM=">>},{<<"ext">>,<<"voice-v1 camera-v1 video-v1">>}],[]},{vcard_xupdate,{<<>>,<<>>},undefined}],#{ip => {0,0,0,0,0,65535,49320,25850}}},stream_version => {1,0},jid => {jid,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>,<<"marry">>,<<"test-vm.whizpool">>,<<"1065557419153304783437">>},mgmt_queue_type => ram,server => <<"test-vm.whizpool">>,mgmt_ack_timeout => 60000,csi_state => active,mgmt_max_queue => 5000,stream_timeout => infinity,ip => {{0,0,0,0,0,65535,49320,25850},42032},socket => {socket_state,gen_tcp,#Port<0.15960>,65536,#Ref<0.2800214629.820903940.155802>,{maxrate,1000,1.6371438238072962,1515755801390713},undefined},mgmt_stanzas_out => 0,socket_monitor => #Ref<0.2800214629.820772865.158698>,csi_queue => {0,#{}},stream_direction => in,stream_compressed => false,tls_options => [compression_none],pres_a => {0,nil},stream_header_sent => true,...}}]
`

**Comment by EmMerry** [comment]
I updated the modules specs, installed the latest mod_statsdx and got this error/message in log.

`2018-01-12 06:41:54.414 [warning] <0.998.0>@gen_mod:get_validators:495 module 'mod_stats2file' doesn't export mod_opt_type/1`


`2018-01-12 06:41:54.416 [error] emulator Error in process <0.1138.0> on node 'admin@test-vm.whizpool' with exit value:
{{badmatch,{error,enoent}},[{mod_stats2file,write_statsfile,5,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_statsdx/src/mod_stats2file.erl"},{line,100}]},{mod_stats2file,write_statsfiles,5,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_statsdx/src/mod_stats2file.erl"},{line,89}]},{mod_stats2file,loop,5,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_statsdx/src/mod_stats2file.erl"},{line,50}]}]}`


`2018-01-12 06:41:54.463 [warning] <0.998.0>@gen_mod:get_validators:495 module 'mod_stats2file' doesn't export mod_opt_type/1`


`2018-01-12 06:41:54.464 [error] emulator Error in process <0.1141.0> on node 'admin@test-vm.whizpool' with exit value:
{{badmatch,{error,enoent}},[{mod_stats2file,write_statsfile,5,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_statsdx/src/mod_stats2file.erl"},{line,100}]},{mod_stats2file,write_statsfiles,5,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_statsdx/src/mod_stats2file.erl"},{line,89}]},{mod_stats2file,loop,5,[{file,"/root/.ejabberd-modules/sources/ejabberd-contrib/mod_statsdx/src/mod_stats2file.erl"},{line,50}]}]}
`

**Comment by badlop** [comment]
> 2018-01-12 06:16:41.392 [error] <0.551.0>@ejabberd_hooks:safe_apply:383 Hook user_send_packet crashed when running mod_statsdx:user_send_packet/1: ** Reason = {error,undef,[{mod_statsdx,user_send_packet,[],[{{iq,<<"purpleace39c71">>,get,<<"en">>,{jid

I guess you don't get that error after you updated correctly the module.

> 2018-01-12 06:41:54.414 [warning] <0.998.0>@gen_mod:get_validators:495 module 'mod_stats2file' doesn't export mod_opt_type/1

That's expected, only a warning, don't worry.

> 2018-01-12 06:41:54.416 [error] emulator Error in process <0.1138.0> on node 'admin@test-vm.whizpool' with exit value: {{badmatch,{error,enoent}},[{mod_stats2file,write_statsfile,5

In the option basefilename, you must specify path to a dir that exist, for example /tmp must exist, and the files will be called stats-something:
>    basefilename: "/tmp/stats"

By the way, I added more commits recently, as there were more errors.
