### ISSUE TITLE
Alternative of mod_rest module for doing pre-authentication steps 

### ISSUE THREAD

**Issue by shubham1164** [processone/ejabberd-contrib#236]
I want to perform some registration verification steps like whatsapp does - phone number verification with OTP. Which ejabberd module should be modified and how? I came to know about mod_rest module through which I can send ejabberdctl commands to the server but with a drawback that with anyone can send the message to anyone if that IP is not blocked. I might use this mod_rest module to server my purpose if this module do not have this property of sending message to any other user. Please help

**Comment by badlop** [comment]
ejabberd also includes ejabberd_xmlrpc. This allows you to send XML-RPC queries to execute ejabberd commands. Once you get that working, you can restrict what commands can be executed, and require the XML-RPC client to provide a Jabber account with granted access to execute it.
