### ISSUE TITLE
ejabberd_auth_http store type external disable SCRAM SASL

### ISSUE THREAD

**Issue by tsaqova** [processone/ejabberd-contrib#239]
I use ejabberd_auth_http & auth_password_format: scram in my config.
As I stated here https://github.com/processone/ejabberd-contrib/issues/228#issuecomment-364402826
change the store_type to external make SCRAM-SHA-1 disappear from SASL feature list:
https://github.com/processone/ejabberd/blob/master/src/cyrsasl.erl#L164
is it intended? 
currently, I created a workaround for my apps because of this patch:
https://github.com/processone/ejabberd-contrib/issues/228#issuecomment-329067760

Thanks.

**Comment by badlop** [comment]
Yes, it is clearly intended, there is code in ejabberd_auth.erl that differentiates between scram store_type and external. They exclude each other: https://github.com/processone/ejabberd/blob/master/src/ejabberd_auth.erl#L196
