### ISSUE TITLE
mod_admin_extra: add_rosteritem ignores "subs" parameter

### ISSUE THREAD

**Issue by germanSancho** [processone/ejabberd-contrib#24]
After the fix of #22, in **add_rosteritem**, the last parameter (subs) seems to be ignored. E.g, if I execute **ejabberdctl add_rosteritem user35 localhost user36 localhost user36 friends both**, the roster item is created, but the subscription is set to "none" instead of "both":

```
$ ejabberdctl add_rosteritem user35 localhost user36 localhost user36 friends both
$ ejabberdctl get_roster user35 localhost
user36@localhost    user36  none    none    friends
```

**Comment by abhinav2215** [comment]
I am unable to find the patch for subs. Can you post please

**Comment by badlop** [comment]
Here is the corresponding commit: f7c243ab4fc4d415043f2c79d07ac0450751ee83
