### ISSUE TITLE
mod_webpresence still uses deprecated jlib.hrl

### ISSUE THREAD

**Issue by asevans48** [processone/ejabberd-contrib#241]
> What version of ejabberd are you using? 

18.03

> What operating system (version) are you using?

Ubuntu latest

> How did you install ejabberd (source, package, distribution)?

Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I installed the package from the website. The program works well. When I try to install modules, as some in previous issues noticed, I received the following error:

********/lib/ejabberd-18.03/include/jlib.hrl:21: can't find include file "ns.hrl"
*******/lib/ejabberd-18.03/include/jlib.hrl:22: can't find include file "fxml.hrl"

The module I am trying to compile specifically is mod_webpresence. I am following the instructions at erlang-contrib and opened a ticket there as well. The error was presented here in the past. Thanks

**Comment by badlop** [comment]
I've updated the module in this commit: https://github.com/processone/ejabberd-contrib/commit/721ca125ea0b8f5d16c2855b114eb6715cfad9d4 There are still features that do not work:
- Registration does not support enabling/disabling different features
- Avatar does not work at all
- Check all he configurable options are really used

And probably there are bugs, so, if you try it, please report here any bugs that you find, or features that worked previously and now do not work.

**Comment by Neustradamus** [comment]
@asevans48 Have you tested since @badlop changes?
