### ISSUE TITLE
Installation of ejabberd_auth_http throws warning "call to crypto:rand_bytes"

### ISSUE THREAD

**Issue by m-byte** [processone/ejabberd-contrib#243]
When running `docker exec -it ejabberd bin/ejabberdctl module_install ejabberd_auth_http` on ejabberd/ecs, the following warning gets thrown:
```
/home/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/ejabberd_auth_http/src/scram2.erl:135:
Warning: call to crypto:rand_bytes/1 will fail, since it was removed in 20.0; use crypto:strong_rand_bytes/1
```

The line causing this:
https://github.com/processone/ejabberd-contrib/blob/721ca125ea0b8f5d16c2855b114eb6715cfad9d4/ejabberd_auth_http/src/scram2.erl#L135

**Comment by badlop** [comment]
I've applied the fix, updated to the current prefered function.
