### ISSUE TITLE
mod_statsdx disco query not counted by mod_stream_mgmt

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd-contrib#245]
After upgrading ejabberd from 18.01 to 18.04 Gajim would constantly be disconnected because of a mismatch in confirmed stanza count (off by 1).

After disabling mod_statsdx the problem was gone.

**Comment by weiss** [comment]
I can no longer(?) reproduce this.

**Comment by debalance** [comment]
Neither can I :)
