### ISSUE TITLE
Is it possible to get WAN IP through HTTP authentication module

### ISSUE THREAD

**Issue by Adiii717** [processone/ejabberd-contrib#247]
I am trying to get WAN IP in my auth server but when I tried to get IP from request its return localhost IP or IP of the machine where ejabberd is running.
Is there any way to pass original IP to HTTP auth server to get IP of the original request or can we pass **X-Forwarded-For** to auth server?

The documentation mentions something like

> connection_opts (optional, default: []) - extra options for hackers: http://erlang.org/doc/man/gen_tcp.html#type-connect_option

But not further explanation `connection_opts`.

[ejabberd_auth_http](https://github.com/processone/ejabberd-contrib/tree/master/ejabberd_auth_http)
Thanks.

**Comment by badlop** [comment]
Apparently nobody could answer this question.
