### ISSUE TITLE
mod_rest warning: undefined callback function mod_options

### ISSUE THREAD

**Issue by arsenichev** [processone/ejabberd-contrib#250]
While compile **mod_rest** module i have error:
**src/mod_rest.erl:27: Warning: undefined callback function mod_options/1 (behaviour 'gen_mod')**

User this compile command:
`/opt/ejabberd-18.04/bin/erlc -I ../../ejabberd-18.04/include/ -I ../../xmpp/include/ -I ../../fast_xml/include/ -o ./ebin/ ./src/mod_rest.erl`

How resolve this problem?

**Comment by badlop** [comment]
It is not an error message, it is a warning message. And in this case, it is a warning for the module developer, that didn't yet implement that function. It would be nice to implement that function, but anyway the module probably works correctly.
