### ISSUE TITLE
ip_macth/2 always returns false

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/ejabberd-contrib#255]
CentOS 6
Ejabberd 18.03

I have installed mod_rest and in ejabberd.yml configured it like these:

```
  mod_rest:
    allowed_ips:
      - "127.0.0.1"
```

but any time i'm posting stanzas it says that "Error: REST request is rejected by service"

i put some logs in mod_rest.erl and after some tests found out that:

ip_matches(ClientIp, AllowedValues) always returns false

```
check_member_option(Host, ClientIp, allowed_ips) ->
    true = case try_get_option(Host, allowed_ips, all) of
               all -> true;
               AllowedValues -> ip_matches(ClientIp, AllowedValues)
           end;
```

**Comment by prefiks** [comment]
Hello,

Are you sure your connections are incoming from 127.0.0.1, sometimes ipv6 addresses are used like FFFF::127.0.0.1 and those will not match.

If you set ejabberd loglevel to 5 you should get ejabberd_http log entry with ip address of incoming connection, could you see what ip is really used?

**Comment by ltAldoRaine** [comment]
Hello 

These is my log:

![capture](https://user-images.githubusercontent.com/17614392/44788898-4b3fd800-abac-11e8-8fb9-f78a1130a81e.PNG)

**Comment by ltAldoRaine** [comment]
Hello

These is my log:

![capture](https://user-images.githubusercontent.com/17614392/44789082-c73a2000-abac-11e8-94f3-d076378850ea.PNG)

**Comment by prefiks** [comment]
So that ip addrees is "::FFFF:172.17.0.70", as you may guess that doesn't match 127.0.0.1

**Comment by ltAldoRaine** [comment]
so, i have to change configuration like this?  
mod_rest:
    allowed_ips:
      - "::FFFF:172.17.0.70"

**Comment by prefiks** [comment]
Yes it should work if your ip don't change.

**Comment by ltAldoRaine** [comment]
now it's working for all ips.. am i doing something wrong?

![capture](https://user-images.githubusercontent.com/17614392/44789927-f356a080-abae-11e8-9825-eff2c9348fa0.PNG)

**Comment by prefiks** [comment]
Your mask is wrong, ipv6 addresses are 128 bits long, so using 32 will only match only small part of addresses which are same in both cases, use 128 to just match single ip or 120 to all but last last byte, etc.
