### ISSUE TITLE
MongoDB is missing here

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd-contrib#267]
MongoDB is missing here :/
- https://github.com/deolan/ejabberd-mongodb-driver
- https://github.com/kongo2002/ejabberd-mod-mam
- https://github.com/comtihon/mongodb-erlang

Linked to:
- https://github.com/processone/ejabberd/issues/419
- https://github.com/processone/ejabberd/issues/305
- ...

**Comment by panpansh** [comment]
+1 vote

**Comment by mremond** [comment]
ejabberd does not support MongoDB (and I do not think there is any plan to support MongoDB at the moment).
