### ISSUE TITLE
Wrong encoding of filenames in mod_log_chat

### ISSUE THREAD

**Issue by Victorinovich** [processone/ejabberd-contrib#275]
mod_log_chat creates a file but breaks the encoding of the file name, for example: 
2019-05-31 Ð³Ð¾ÑÐ¸Ð½Ð¾Ð²_Ð¾Ð»ÐµÐ³@aqsjabber2 - Ð»ÐµÐ±ÐµÐ´ÐµÐ²_Ð¸Ð»ÑÑ@aqsjabber2.log
but the contents of the file does not suffer.

**Comment by badlop** [comment]
Try with that simple fix, and please comment here if it's fixed for you too.

**Comment by Victorinovich** [comment]
it is not clear how to compile, I do not have a folder ejabberd-dev

**Comment by Victorinovich** [comment]
found in Google how to compile, try later

**Comment by Victorinovich** [comment]
I can not figure out the compilation. You can put the finished module for Ejabberd 19.02? File mod_log_chat.beam.

**Comment by badlop** [comment]
How did you install the module the first time you used it?

**Comment by Victorinovich** [comment]
downloaded the latest version (file deb) from here https://apt.jabber.at/pool/ejabberd/e/ejabberd-contrib/, extracted file beam and put it to the rest of the modules, writing in ejabberd.yml

**Comment by badlop** [comment]
Ahh, I didn't know that there were debian packages for contrib. I propose you to download and install the module as recommended, but only to obtain the updated beam file and copy that file to your place:

Download the contrib git repos and compile the module:
```
$ ejabberdctl modules_update_specs 
$ ejabberdctl module_install mod_log_chat
```

Now copy the updated beam file from $HOME/.ejabberd-modules/mod_log_chat/ebin/mod_log_chat.beam to the place where your debian package installed the old one.

Finally, uninstall that module so you have only one installed:
`$ ejabberdctl module_uninstall mod_log_chat`

**Comment by Victorinovich** [comment]
I already tried all this:
ejabberdctl modules_update_specs
Failed RPC connection to the node ejabberd@localhost: timeout

**Comment by licaon-kter** [comment]
@Victorinovich `sudo -u ejabberd ejabberdctl modules_update_specs` ?

**Comment by Victorinovich** [comment]
Made, no change

**Comment by Victorinovich** [comment]
ejabberdctl module_install mod_log_chat
/var/lib/ejabberd/.ejabberd-modules/sources/mod_log_chat/ebin/mod_log_chat.bea#: error writing file: no such file or directory
/var/lib/ejabberd/.ejabberd-modules/sources/mod_log_chat/src/mod_log_chat.erl:11: Warning: undefined callback function mod_options/1 (behaviour 'gen_mod')
Error: {compilation_failed,"/var/lib/ejabberd/.ejabberd-modules/sources/mod_log_chat/src/mod_log_chat.erl"}

**Comment by Victorinovich** [comment]
undefined parse transform 'lager_transform'  
everything, then where?

**Comment by badlop** [comment]
Ok, send me an email to badlop@process-one.net indicating your Erlang/OTP version and I'll try to compile and send you the beam file.

**Comment by Victorinovich** [comment]
send
Thank you!

**Comment by badlop** [comment]
Ok, that fixes the encoding problem.
