### ISSUE TITLE
modules not compatible with ejabberd 19.08

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd-contrib#277]
Hi,
several - if not all - contrib modules appear to be incompatible with ejabberd 19.08.
They can't be compiled. No issues with ejabberd 19.05.

**Comment by badlop** [comment]
I've updated most modules. I think the remaining modules are either already up-to-date, or too obsolete to even consider updating them.

**Comment by debalance** [comment]
Thx, I can now build the same modules as before!
