### ISSUE TITLE
mod_spam_filter: 19.08.23 crash report

### ISSUE THREAD

**Issue by stefansieg** [processone/ejabberd-contrib#280]
Hi,

after upgrading from 19.05 to 19.08.23

>ejabberdctl module_install mod_spam_filter

greets me with this message:

@proplists:get_value:215 CRASH REPORT Process <0.29103.0> with 0 neighbours crashed with reason: no function clause matching proplists:get_value(spam_dump_file, #{access_spam => none,cache_size => 10000,spam_dump_file => <<"/var/log/ejabberd/spammer.log">>,...}, undefined) li
ne 215                                                                                                                                                         
2019-09-10 18:19:04.923 [critical] <0.29098.0>@gen_mod:start_module:163 Failed to start module mod_spam_filter:                                                
{error,                                                                                                                                                        
    {{function_clause,                                                                                                                                         
         [{proplists,get_value,                                                                                                                                
              [spam_dump_file,                                                                                                                                 
               #{access_spam => none,cache_size => 10000,                                                                                                      
                 spam_dump_file => <<"/var/log/ejabberd/spammer.log">>,                                                                                        
                 spam_jids_file => <<"/etc/ejabberd/spam-filter/jids.txt">>,                                                                                   
                 spam_urls_file => <<"/etc/ejabberd/spam-filter/urls.txt">>},
               undefined],
              [{file,"proplists.erl"},{line,215}]},
          {mod_spam_filter,init,1,
              [{file,
                   "/var/db/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_spam_filter/src/mod_spam_filter.erl"},
               {line,147}]},
          {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},
          {gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},
          {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},
     {child,undefined,'mod_spam_filter_dismail.de',
         {gen_server,start_link,
             [{local,'mod_spam_filter_dismail.de'},
              mod_spam_filter,
              [<<"dismail.de">>,
               #{access_spam => none,cache_size => 10000,
                 spam_dump_file => <<"/var/log/ejabberd/spammer.log">>,
                 spam_jids_file => <<"/etc/ejabberd/spam-filter/jids.txt">>,
                 spam_urls_file => <<"/etc/ejabberd/spam-filter/urls.txt">>}],
              []]},
         transient,60000,worker,
         [mod_spam_filter]}}}

No problems with 19.05

**Comment by zinid** [comment]
Yes, the module is not adopted for 19.08.
