### ISSUE TITLE
mod_post_log Warning: undefined callback function mod_options/1

### ISSUE THREAD

**Issue by arifr007** [processone/ejabberd-contrib#283]
command: 
`ejabberdctl module_install mod_post_log`

result:
`mod_post_log.erl:13: Warning: undefined callback function mod_options/1 (behaviour 'gen_mod')`

ejabberd version: 19.09.1

**Comment by badlop** [comment]
I've fixed that warning by implementing the corresponding function and updating a few more. It may happen that there are still other parts requiring update, please reopen this issue, or create a new one.
