### ISSUE TITLE
mod_webpresence: PNGs named as GIFs

### ISSUE THREAD

**Issue by debalance** [processone/ejabberd-contrib#285]
While working on the Debian package(s) I came across these lintian hints:

> ejabberd-mod-webpresence/pixmaps/amistellar/available.gif (is PNG)
N:
N:    An image file in this package has a name that is usually associated with
N:    another image format.
N:
N:    Refer to https://bugs.debian.org/717818 for details.
N:
N:    Severity: wishlist, Certainty: certain
N:
N:    Check: images/filenames, Type: binary
N:
ejabberd-mod-webpresence/pixmaps/amistellar/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/amistellar/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/amistellar/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/amistellar/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/amistellar/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/bulb/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/bulb/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/bulb/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/bulb/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/bulb/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/bulb/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/chrome-pl/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/chrome-pl/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/chrome-pl/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/chrome-pl/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/chrome-pl/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/chrome-pl/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal2/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal2/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal2/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal2/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal2/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal2/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal3/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal3/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal3/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal3/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal3/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/crystal3/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/gg/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/gg/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/gg/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/gg/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/gg/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/gg/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/koniczynek/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/koniczynek/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/koniczynek/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/koniczynek/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/koniczynek/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/koniczynek/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/pogoda/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/pogoda/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/pogoda/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/pogoda/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/pogoda/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/pogoda/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/psi/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/psi/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/psi/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/psi/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/psi/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/psi/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/stellar2/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/stellar2/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/stellar2/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/stellar2/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/stellar2/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/stellar2/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/wpkontakt/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/wpkontakt/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/wpkontakt/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/wpkontakt/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/wpkontakt/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/wpkontakt/xa.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/yipee/available.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/yipee/away.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/yipee/chat.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/yipee/dnd.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/yipee/unavailable.gif (is PNG)
ejabberd-mod-webpresence/pixmaps/yipee/xa.gif (is PNG)

**Comment by badlop** [comment]
Thanks for reporting!
