### ISSUE TITLE
mod_pottymouth how to filter out links?

### ISSUE THREAD

**Issue by rocksystem** [processone/ejabberd-contrib#294]
Hello,
I have difficulty filtering spam links like https://myspamlink.com/sompath. 
When I add `myspamlink` or `https://myspamlink.com/sompath` into `blacklist_en.txt`  neither got replaced with ****.

**Comment by badlop** [comment]
Remember to restart ejabberd, or at least restart that module after you edit the blacklist file.

From what I see, this module compares words, not parts of words.
For example, I put in the blacklist file:
```
myspamlink
```

and this is the result:
* `Visit myspamlink` --> `Visit ****`
* `Visit https:// myspamlink .com/sompath` --> `Visit https:// **** .com/sompath`
* `Visit https://myspamlink.com/sompath` --> `Visit https://myspamlink.com/sompath`

So, it is required to add the exact word to the blacklist:
```
https://myspamlink.com/sompath
```
Then, if the spammer uses a slightly different URL, or appends some character different that a blackspace, then it isn't filtered.
