### ISSUE TITLE
mod_http_upload: specify headers for PUT request

### ISSUE THREAD

**Issue by PasqualePuzio** [processone/ejabberd-contrib#295]
Hi all,

we're using mod_http_upload with an external service.

Everything works well as expected and we're able to provide PUT and GET urls, however we can't find a way to specify headers that should be included by the client in the PUT request.

Since this is officially supported by the standard https://xmpp.org/extensions/xep-0363.html#request I'm pretty sure there's a way but we haven't been able to figure it out.

How can the external service (or ejabberd itself) tell the client what headers should be included in the PUT request?

Thanks

**Comment by licaon-kter** [comment]
This should be in the ejabbecd repo, right?

**Comment by PasqualePuzio** [comment]
> This should be in the ejabbeld repo instead, right?

I see. Sorry about that.
