### ISSUE TITLE
unable to install mod_pottymouth ejabberd contrib module

### ISSUE THREAD

**Issue by 2295ad** [processone/ejabberd-contrib#296]
Ejabberd version - 20.07
Ubuntu - 16.04
Installed ejabberd from source code

I have followed the exact steps for installation written in the pottymouth module. On `./rebar compile` I'm getting this error
 `/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
ERROR: cc c_src/bitarray_nif.o $LDFLAGS -shared  -L/usr/lib/erlang/lib/erl_interface-4.0.1/lib -lerl_interface -lei -o priv/bitarray.so failed with error: 1 and output:
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
`
Could be pls look into this issue.

Thanks

**Comment by badlop** [comment]
I've added a script that makes the third step, so the instructions are now easier to follow. Also, added a workaround for the compilation problem.

Please try it, and comment here if you find more problems compiling that module: maybe that script or the instructions needs more tweaks...

**Comment by 2295ad** [comment]
Thanks a lot @badlop  for the quick update. Got this working !!!
