### ISSUE TITLE
mod_logxml  installation error

### ISSUE THREAD

**Issue by paolodeglinnocenti** [processone/ejabberd-contrib#303]
i tried to install mod_logxml module, but i get the following error:

```
/opt/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl:12:
 Warning: undefined callback function mod_doc/0 (behaviour 'gen_mod')
/opt/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl:265:
 Warning: erlang:now/0: Deprecated BIF.
 See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
=ERROR REPORT==== 18-May-2021::15:31:35.397593 ===
Error in process <7640.964.0> on node ejabberd@localhost with exit value:
{{badmatch,{error,eacces}},
 [{mod_logxml,open_file,2,
              [{file,"/opt/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl"},
               {line,232}]},
  {mod_logxml,init,6,
              [{file,"/opt/ejabberd/.ejabberd-modules/sources/ejabberd-contrib/mod_logxml/src/mod_logxml.erl"},
               {line,67}]}]}
```

**Comment by prefiks** [comment]
It seems that's error is coming from trying to write file to location where ejabberd don't have access, i guess `logdir` option of this module points to directory like that (or that doesn't exists).

**Comment by paolodeglinnocenti** [comment]
thanks now it works fine

**Comment by badlop** [comment]
Right, when installing mod_logxml, it enables automatically logxml with a value that will not work out of the box.

I see three alternatives:
A) keep logdir as it is, and explain in README that it's important to create that path before installing the module, or set a proper existing path in the config. Problem: it doesn't work out of the box, requires setup. Another problem: people that will not pay attention to that crucial line in the documentation.
B) set logdir to "/tmp/", that surely will work, but of course is a bad idea, and surely the admin will want to change that value immediately.
C) remove the default configuration completely, as a _proper_ configuration is very dependent on the user case, and having a default configuration for mod_logxml probably doesn't make sense.
