### ISSUE TITLE
modules_update_specs error,eacces

### ISSUE THREAD

**Issue by nanitook** [processone/ejabberd-contrib#309]
When excecuting `ejabberdctl modules_update_specs` it returns
`Error: {repository,"https://github.com/processone/ejabberd-contrib",
                   {error,eacces}}`

**Comment by badlop** [comment]
`eaccess` means no access permission to read or write.

But does it mean read access to the git repository?

Or does it mean write access to the destination? By default it tries to create a directory named `.ejabberd-modules` in $HOME. If you run ejabberd using a new `ejabberd` account that doesn't have any $HOME set... then this could happen.

Solutions?
- In ejabberdctl.cfg you will see an option called CONTRIB_MODULES_PATH. Uncomment it and set to a path where ejabberd can write (for example, the same path that it already uses for log files, or for the mnesia spool files)
- Or create a home for the system user that is running ejabberd

**Comment by nanitook** [comment]
Thank you, changing the permissions of the folder solved it.
