### ISSUE TITLE
Ejabberd Message delivery while application is terminated (IOS)

### ISSUE THREAD

**Issue by djon01676** [processone/ejabberd-contrib#325]
Please tell me which module to work with APNS, becouse message does not report.

**Comment by licaon-kter** [comment]
```
 mod_push: {}
  mod_push_keepalive:            wake_on_start: true
```

**Comment by djon01676** [comment]
XMPP Server - ejabberd-23.04;
Client - Snikket;

**Comment by djon01676** [comment]
> ```
> modules:
> ```


there should be a notification that it came when the phone is locked

**Comment by djon01676** [comment]
> ```
> modules:
> ...
>   mod_push: {}
>   mod_push_keepalive:
>     wake_on_start: true
> ```
> 
> Это все, что нужно.
> 
> Вы пробовали с Моналом? Сниккет? Или Чижик?
> 
> /LE: под «всем» я имею в виду «для push», остальное вам понадобится для других функций :)


there should be a notification that it came when the phone is locked

**Comment by licaon-kter** [comment]
What if the app is not in foreground? Say you look at a webpage and you get a message?

In ejabberd.log (loglevel 4) do you see info about push servers, about Push being enabled?

**Comment by djon01676** [comment]
mod_push: 
    include_body: "New message"
  mod_push_keepalive: 
    wake_on_start: true
    
    
    


Unfortunately, notifications aren`t receive on iPhone if the application is running in the background, although everything is fine with Android.

**Comment by licaon-kter** [comment]
Did you see the .log messages about push for that account?

**Comment by djon01676** [comment]
Yes
when we just close the application we have this problem

Closing c2s connection for client9@host/Snikket.NNHM: Connection failed: connection closed; waiting 300 seconds for stream resumption

**Comment by djon01676** [comment]
2023-10-30 07:47:29.842549+00:00 [info] <0.7065.0>@ejabberd_c2s:bind/2:450 (tls|<0.7065.0>) Opened c2s session for client5@host/iPhone
2023-10-30 07:47:50.413582+00:00 [info] <0.455.0>@ejabberd_listener:accept/7:344 (<0.7069.0>) Accepted connection hidden_by_ejabberd -> 127.0.0.1:5222
2023-10-30 07:47:50.505397+00:00 [info] <0.7069.0>@ejabberd_c2s:process_auth_result/3:272 (tls|<0.7069.0>) Accepted c2s SCRAM-SHA-256 authentication for client9@host by sql backend from hidden_by_ejabberd
2023-10-30 07:47:50.543267+00:00 [info] <0.7069.0>@ejabberd_c2s:bind/2:450 (tls|<0.7069.0>) Opened c2s session for client9@host/Snikket.NNHM
2023-10-30 07:47:57.458929+00:00 [info] <0.7070.0>@ejabberd_s2s_out:init/1:289 Outbound s2s connection started: host -> push.tigase.im
2023-10-30 07:47:57.742487+00:00 [info] <0.7065.0>@ejabberd_c2s:process_terminated/2:295 (tls|<0.7065.0>) Closing c2s session for client5@host/iPhone: Stream reset by peer
2023-10-30 07:47:58.896603+00:00 [info] <0.7070.0>@ejabberd_s2s_out:handle_auth_success/2:223 (tls|<0.7070.0>) Accepted outbound s2s EXTERNAL authentication host -> push.tigase.im (hidden_by_ejabberd)
2023-10-30 07:48:02.037660+00:00 [info] <0.457.0>@ejabberd_listener:accept/7:344 (<0.7071.0>) Accepted connection hidden_by_ejabberd -> 127.0.0.1:5269
2023-10-30 07:48:02.941270+00:00 [info] <0.7071.0>@ejabberd_s2s_in:handle_auth_success/4:183 (tls|<0.7071.0>) Accepted inbound s2s EXTERNAL authentication push.tigase.im -> host (hidden_by_ejabberd)
2023-10-30 07:49:29.639126+00:00 [info] <0.455.0>@ejabberd_listener:accept/7:344 (<0.7073.0>) Accepted connection hidden_by_ejabberd -> 127.0.0.1:5222
2023-10-30 07:49:29.834573+00:00 [info] <0.7073.0>@ejabberd_c2s:process_auth_result/3:272 (tls|<0.7073.0>) Accepted c2s SCRAM-SHA-256 authentication for client5@host by sql backend from hidden_by_ejabberd
2023-10-30 07:49:29.892478+00:00 [info] <0.7073.0>@ejabberd_c2s:bind/2:450 (tls|<0.7073.0>) Opened c2s session for client5@host/iPhone
2023-10-30 07:49:37.340382+00:00 [info] <0.7069.0>@mod_stream_mgmt:transition_to_pending/2:439 (tls|<0.7069.0>) Closing c2s connection for client9@brainskill.in.ua/Snikket.NNHM: Connection failed: connection closed; waiting 300 seconds for stream resumption

**Comment by licaon-kter** [comment]
Oh, this should be in ejabberd not -contrib, btw

**Comment by djon01676** [comment]
i copied this from ejabberd.log file

**Comment by djon01676** [comment]
You may need to register apns servers for s2s ????
because I have no idea how to solve this problem

**Comment by djon01676** [comment]
or use this mod

https://github.com/mrDoctorWho/ejabberd_mod_apns

**Comment by licaon-kter** [comment]
No, I meant the issue should have been filed in https://github.com/processone/ejabberd/issues/ instead

Why is the resource named "Snikket" but the push server is tigase.im ?
 
You have more users on that server and some use Snikket and some Siskin?

Did you try Monal too?

Do you see messages like `mod_push:enable/4:336 Enabling push notifications for user@domain` in the .log ?

**Comment by licaon-kter** [comment]
> You may need to register apns servers for s2s ????
because I have no idea how to solve this problem

No, nhe client does so, eg. Siskin/Snikket/Monal from Apple Appstore or Conversations from Google Play 


> or use this mod https://github.com/mrDoctorWho/ejabberd_mod_apns

No extra module needed, no, just that module config as I said above

**Comment by djon01676** [comment]
hosts:
  - host

loglevel: info
log_rotate_size: 10485760
log_rotate_count: 1
hide_sensitive_log_data: true



default_db: sql
new_sql_schema: true
# параметры базы для домена 
host_config:
  host:
    sql_type: sqlite
    sql_database: "/opt/ejabberd/server.sdb"
    auth_method: sql



define_macro:
  'TLS_CIPHERS': "HIGH:!aNULL:!eNULL:!3DES:!CAMELLIA:@STRENGTH"
  'TLS_OPTIONS':
    - "no_sslv2"
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"
    - "cipher_server_preference"
    - "no_compression"
  'DH_FILE': "/opt/ejabberd/certs/dh2048.pem"
  'CERT_FILE': "/opt/ejabberd/certs/server.pem"

certfiles:
  - "/opt/ejabberd/certs/server.pem"


c2s_protocol_options: 'TLS_OPTIONS'
c2s_ciphers: 'TLS_CIPHERS'
c2s_dhfile: 'DH_FILE'

s2s_use_starttls: required
s2s_protocol_options: 'TLS_OPTIONS'
s2s_ciphers: 'TLS_CIPHERS'
s2s_dhfile: 'DH_FILE'
s2s_access: s2s

listen:
  -
    port: 5222
    ip: "127.0.0.1"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5223
    ip: "127.0.0.1"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    tls: true
  -
    port: 5269
    ip: "127.0.0.1"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
    shaper: s2s_shaper
  -
    port: 5443
    ip: "127.0.0.1"
    module: ejabberd_http
    tls: true
    request_handlers:
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
  -
    port: 3478
    turn_ipv4_address: "10.10.12.34"
    ip:"127.0.0.1"
    transport: udp
    module: ejabberd_stun
    use_turn: true
    turn_min_port: 49152
    turn_max_port: 65535
  -
    port: 5349
    ip: "127.0.0.1"
    turn_ipv4_address: "10.10.12.34"
    transport: tcp
    tls: true
    module: ejabberd_stun
    use_turn: true
    turn_min_port: 49152
    turn_max_port: 65535
    certfile: "/opt/ejabberd/certs/server.pem"
    
  -
    port: 1883
    ip: "127.0.0.1"
    module: mod_mqtt
    backlog: 1000

acl:
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
  bad_servers:
    - "gmail.com"
  blocked:
    user:
      - "baduser": "host"
  admin:
    user:
      - "admin@host"





access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback
  register:
    deny: all
  s2s:
    - allow:
      - server: p2.siacs.eu
    - allow:
      - server: push.tigase.im
    - allow:
      - server: pubsub.chatsecure.org
    - deny: all

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          - acl: loopback
          - acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

shaper:
  normal: 1000
  fast: 50000

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

max_fsm_queue: 10000


modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    docroot: "/opt/ejabberd/uploads"
    put_url: https://@HOST@:5443/upload
    custom_headers:
      "Access-Control-Allow-Origin": "https://@HOST@"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
      "Content-Security-Policy": "default-src 'none'; frame-ancestors 'none'; "
      "X-Content-Type-Options": "nosniff"
      "X-Frame-Options": "deny"
  mod_last: {}
  mod_http_upload_quota:
    max_days: 3
  mod_mam:
    db_type: sql
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pres_counter:
    count: 5
    interval: 60
  mod_proxy65:
    access: local
    max_connections: 5
    ip: 127.0.0.1
    port: 7777
  mod_pubsub:
    db_type: sql
    ignore_pep_from_offline: true
    last_item_cache: false
    max_items_node: 10
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      storage:bookmarks:
        access_model: whitelist
  mod_push: 
    include_body: "New message"
  mod_push_keepalive: 
    wake_on_start: true
  mod_register:
    ip_access: trusted_network
    access_from: deny
    access: register
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_stun_disco: 
    credentials_lifetime: 12h
    services:
      -
        host: 10.10.12.34
        port: 3478
        type: stun
        transport: udp
        restricted: false
      -
        host: 10.10.12.34
        port: 3478
        type: turn
        transport: udp
        restricted: true
      -
        host: host
        port: 5349
        type: stuns
        transport: tcp
        restricted: false
      -
        host: host
        port: 5349
        type: turns
        transport: tcp
        restricted: true
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false

**Comment by djon01676** [comment]
this is my config

**Comment by djon01676** [comment]
_You have more users on that server and some use Snikket and some Siskin?_

yes

**Comment by licaon-kter** [comment]
And for your test user?

**Comment by djon01676** [comment]
thank you, the problem was with the client

**Comment by licaon-kter** [comment]
@djon01676 explain the issue and the fix

**Comment by Neustradamus** [comment]
@djon01676: How have you fixed the problem?
