### ISSUE TITLE
mod_webpresence does not support default_ram_db SQL

### ISSUE THREAD

**Issue by bjacquin** [processone/ejabberd-contrib#331]
Hi,

ejabberd 23.10 configured with `default_ram_db: sql` and `sql_type: sqlite` does not appear to support mod_webpresence, where all user presence is reported as `unavailable` while after changing `default_ram_db` to `mnesia`, user presence is properly reported.

**Comment by prefiks** [comment]
Yes, indeed it scans data used by mnesia tables directly. Let me see if we can change it.

**Comment by prefiks** [comment]
Commit 7e5af663bff2cc38f679fd4671937d76ec7cb43a makes this module work with any session manager backend.
