### ISSUE TITLE
Add ejabberd_mod_apns here?

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd-contrib#336]
It is possible to add the ejabberd_mod_apns module here with the name: mod_apns?

Original place:
- https://github.com/mrDoctorWho/ejabberd_mod_apns

Please look forks, maybe good changes to add too:
- https://github.com/joanlopez/ejabberd-mod-apns
- https://github.com/kirillzh/mod_apns

**Comment by licaon-kter** [comment]
and they all leak your XMPP address and your contact? meh

**Comment by weiss** [comment]
@Neustradamus, such a module is only useful for closed setups.  I think the main target audience of the "community edition" is open servers.
