### ISSUE TITLE
How to send a basic iq stanza

### ISSUE THREAD

**Issue by aerlijman** [processone/ejabberd-contrib#40]
Hi, I am playing with this module and could be able to send register command and message stanza. However, I can't find a way to send other iq stanza like to get the roster from a user like
``` ruby
<iq from='juliet@example.com/balcony' type='get' id='roster_1'>
  <query xmlns='jabber:iq:roster'/>
</iq>
```

Ideas?

**Comment by badlop** [comment]
If you refer to mod_admin_extra's command send_stanza_c2s, it is only capable of sending stanzas, not receiving responses. So, it doesn't help to send Info-Query stanzas.
