### ISSUE TITLE
mod_muc_admin: rooms_unused_destroy yields stacktrace

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd-contrib#43]
On ejabberd-14.05 and the latest version of mod_muc_admin, the commands ```rooms_unused_destroy``` and ```rooms_unused_list``` fail and print the following stacktrace:

```
root@host: ~ $ ejabberdctl rooms_unused_destroy jabber.at 14
Problem 'error {badrecord,config}' occurred executing the command.
Stacktrace: [{mod_muc_admin,decide_room,2,
                            [{file,"src/mod_muc_admin.erl"},{line,581}]},
             {lists,'-filter/2-lc$^0/1-0-',2,[{file,"lists.erl"},{line,1220}]},
             {mod_muc_admin,muc_unused2,4,
                            [{file,"src/mod_muc_admin.erl"},{line,537}]},
             {mod_muc_admin,rooms_unused_report,3,
                            [{file,"src/mod_muc_admin.erl"},{line,524}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,293}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,269}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,218}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,203}]}]
```

Other commands I tried (get_room_affiliation, get_room_occupants, muc_online_rooms, get_room_occupants_number) seem to work fine.

**Comment by badlop** [comment]
The problem was probably that the header file ejabberd-dev/include/mod_muc_room.hrl used to compile this module had an old "config" definition, incompatible with the one used by ejabberd itself. And this was probably already fixed some time ago.

The next time this problem appears, try to copy that header file from ejabberd sources, and then compile the module again.
