### ISSUE TITLE
Fix display of Top.. statsdx pages in WebAdmin

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd-contrib#47]
1. Module doesn't work correctly in webadmin. In global stats don't work (I have set hook as true):
- Top vCard sizes
- Sessions: Client
- Sessions: Operating System
- Sessions: Client/Operating System
- Sessions: Connection Type
- Sessions: Client/Connection Type
- Sessions: Languages
This same is in each vhost.

2. When we set hook to true or traffic in /var/log/ejabberd/error.log there are a lot of issues from this module. Problem doesn't exist when hook is set to false.

**Comment by badlop** [comment]
In the current ejabberd git, the tables show correct information. However, the pages for "Top ..." provoke a crash.
