### ISSUE TITLE
message archiving support for ejabberd 14.07?

### ISSUE THREAD

**Issue by jayeshjain24** [processone/ejabberd-contrib#55]
any module that supports archiving chat history for ejabberd version 14.07?
is there any alternative to mod_archive_odbc and mod_archive2 since both are now deprecated.

Any help?

**Comment by rastkojokic** [comment]
I am curious about the same issue as @jayeshjain24 ... Any recommendations?

**Comment by weiss** [comment]
There's [mod_mam][1] which implements [XEP-0313][2],  but that module requires ejabberd 14.12 or newer.  I'm not aware of another alternative for ejabberd 14.07, sorry.

[1]: https://github.com/processone/ejabberd-contrib/tree/master/mod_mam
[2]: http://xmpp.org/extensions/xep-0313.html

**Comment by rastkojokic** [comment]
Actually I am using 15.04 so that should work!

Thanks!
