### ISSUE TITLE
set_presence from mod_admin_extra giving issue with ejabber 14

### ISSUE THREAD

**Issue by dollarhand** [processone/ejabberd-contrib#61]
Hi Guys,

I am trying to use set_presence from the ejabber-contrib and its giving me below issue

ejabberdctl set_presence userId localhost 1178385771421150488459725 subscribed dnd Im_away_25_minutes 127
Problem 'error undef' occurred executing the command.
Stacktrace: [{p1_logger,info_msg,
	 [mod_admin_extra,916,"Message : ~p~n",
	  [{route_xmlstreamelement,
		   {xmlel,<<"presence">>,
			   [{<<"from">>,
				 "userId@localhost/1178385771421150488459725"},
				{<<"to">>,
				 "userId@localhost"},
				{<<"type">>,"subscribed"}],
			   [{xm=lel,<<"show">>,[],[{xmlcdata,"dnd"}]},
				{xmlel,<<"status">>,[],
					[{xmlcdata,"Im_away_25_minutes"}]},
				{xmlel,<<"priority">>,[],[{xmlcdata,"127"}]}]}}]],
	 []},
 {mod_admin_extra,set_presence,7,
	 [{file,"src/mod_admin_extra.erl"},{line,916}]},
 {ejabberd_ctl,call_command,3,
	 [{file,"src/ejabberd_ctl.erl"},{line,293}]},
 {ejabberd_ctl,try_call_command,3,
	 [{file,"src/ejabberd_ctl.erl"},{line,269}]},
 {ejabberd_ctl,process2,3,
	 [{file,"src/ejabberd_ctl.erl"},{line,218}]},
 {ejabberd_ctl,process,1,
	 [{file,"src/ejabberd_ctl.erl"},{line,203}]},
 {rpc,'-handle_call_call/6-fun-0-',5,
	 [{file,"rpc.erl"},{line,205}]}]

**Comment by badlop** [comment]
Apparently that command needs a few lines from this old patch:
https://support.process-one.net/browse/EJAB-1184
I'll review if that's really required, or there's some alternative.

**Comment by badlop** [comment]
Should be fixed now.

**Comment by dollarhand** [comment]
Hey badlop, I have made some changes in set_presence API and getting the following error, can you please help me with it.
2015-04-05 09:20:17.203 [error] <0.9624.0>@ejabberd_c2s:handle_info:1729 Unexpected info: {route_xmlstreamelement,{xmlel,<<"presence">>,[{<<"from">>,"2069021631@host/2761505426142825036445629"},{<<"to">>,"2069021631@host"},{<<"type">>,"available"}],[{xmlel,<<"show">>,[],[{xmlcdata,"dnd"}]},{xmlel,<<"status">>,[],[{xmlcdata,"xmpp_set_presence"}]},{xmlel,<<"priority">>,[],[{xmlcdata,"127"}]}]}}

**Comment by badlop** [comment]
To start with, you are providing some strings like "127", but they should be binaries.

**Comment by dollarhand** [comment]
Hi badlop, 
I am sending the below input, on the debug console. Please let me know  is this the correct input for the set presence command.
mod_admin_extra:set_presence(<<"2069021631">>,<<"hostname">>,<<"2761505426142825036445629">>,<<"available">>,<<"dnd">>,<<"xmpp_set_presence">>,<<"127">>).

**Comment by badlop** [comment]
Right, that's correct.

**Comment by dollarhand** [comment]
Hi badlop, 
If the above input are right, its stull giving me error as mention above. Unexpected info. As of now i have not applied the patch now. Will applying the patch resolve the issue.
