### ISSUE TITLE
mor_rest compatibility with ejabberd 14.12

### ISSUE THREAD

**Issue by kamenik** [processone/ejabberd-contrib#63]
Hi,

we have experienced problems while using mod_rest against last version of ejabberd,
it always returns - Try POSTing a stanza. It seems there are some changes between versions,
where new ejabberd uses another data type than current module. 

Jaroslav

**Comment by Beherit** [comment]
You need to recompile mod_rest.

**Comment by kamenik** [comment]
I have fresh ejabbered-contrib from github, and it has this problem.

**Comment by Beherit** [comment]
You doing something wrong because for me mod_rest is working (http://jix.im/en/informations - this informations are from mod_rest).

**Comment by kamenik** [comment]
You are right, I had  "127.0.0.1/8" in allowed_ips , but it wants exact IP, not a range. 

Thanx for help:).
