### ISSUE TITLE
Report problem when mod_rest receives malformed stanza

### ISSUE THREAD

**Issue by santiagopoli** [processone/ejabberd-contrib#65]
When i deploy my ejabberd server with mod_rest listening in port 5285 and receive a stanza with characters like '<' or '&', the server crashes.

For example,

POST http://localhost:5285/rest

BODY:

    <message
        to='1@localhost'
        from='2@localhost'
        type='chat'
        xml:lang='en'>
      <body><</body>
    </message>

Throws an exception in ejabberd:

2015-01-09 15:04:34.929 [error] <0.1523.0> CRASH REPORT Process <0.1523.0> with 0 neighbours crashed with reason: no function clause matching xml:get_tag_attr_s(<<"from">>, {error,{4,<<"not well-formed (invalid token)">>}}) line 362

I guess it has to do with the fact that those characters are XML-reserved ones.

Is there a quick fix to this issue?

**Comment by zinid** [comment]
I'm not sure what should be fixed? We can fix the crash of course, but the XML you're sending is still incorrect

**Comment by santiagopoli** [comment]
No, it's not. I'm sending messages between two users, so suppose I send this stanza:

<message
    to='1@localhost'
    from='2@localhost'
    type='chat'
    xml:lang='en'>
  <body>See you in Barnes&Noble</body>
</message>

Throws this error:

16:29:30.199 [error] CRASH REPORT Process <0.547.0> with 0 neighbours crashed with reason: no function clause matching xml:get_tag_attr_s(<<"from">>, {error,{4,<<"not well-formed (invalid token)">>}}) line 362
16:29:30.199 [error] Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.547.0> exit with reason function_clause in context child_terminated
16:29:30.200 [error] CRASH REPORT Process <0.549.0> with 0 neighbours crashed with reason: no function clause matching xml:get_tag_attr_s(<<"from">>, {error,{4,<<"not well-formed (invalid token)">>}}) line 362
16:29:30.200 [error] Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.549.0> exit with reason function_clause in context child_terminated

Obviously i can avoid those characters by code, but i think ejabberd should not crash.

To add more information to this context, I'm using this mod to redirect all the chat messages in my existing Java messaging server to ejabberd (is like a proxy that i need because the clients use a mobile  app that connects to this existing Java server). We want to fully migrate our chat layer to ejabberd but for compatibility reasons, we still have to mantain the old server.

**Comment by santiagopoli** [comment]
Sending

    <message
        to='1@localhost'
        from='2@localhost'
        type='chat'
        xml:lang='en'>
      <body>\&gt;</body>
    </message>

Works as well, so escaping these characters before posting the data will fix my problem, but the crash is something different.
