### ISSUE TITLE
Long-living sessions in MUC

### ISSUE THREAD

**Issue by santiagopoli** [processone/ejabberd-contrib#70]
Hi, I want to implement a Whatsapp-like multi user chat. To do so, I need to fool ejabberd to never close the user session and therefore prevent the user from leaving the room any time he disconnects.

It would be easy to implement such functionality? My experience in Erlang is basic, but I thing I can handle it. It would be nice if someone could give me a hint on where to start. I'm looking inside mod_muc.erl and mod_muc_room.erl but I didn't find anything yet.

Sorry, I didn't knew where to post this.

Thanks in advance!

**Comment by mremond** [comment]
This is not ejabberd or Erlang issue. This use case is not handle by XMPP MUC specification at the moment. MUC is tight to presence in the current state of the XMPP protocol. Your need need a custom muc implementation.
