### ISSUE TITLE
incorrect-fsf-address in some of the copying files

### ISSUE THREAD

**Issue by darix** [processone/ejabberd-contrib#73]
found with our build checks:

* mod_admin_extra/COPYING
* mod_cron/COPYING
* mod_logxml/COPYING
* mod_statsdx/COPYING
* mod_webpresence/COPYING
* mod_muc_log_http/COPYING
* mod_muc_admin/COPYING
* mod_multicast/COPYING

**Comment by mremond** [comment]
Very good point, we will make that more homogeneous. Thanks !

**Comment by badlop** [comment]
Solved in contrib and ejabberd repos.
