### ISSUE TITLE
send_message no longer stored for offline clients

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd-contrib#83]
We have a web registration interface and send a welcome message to new users. The users are of course at the time offline, since this happens directly at registration. We used to use the `send_message_chat` to send this message, since messages sent via `send_message_headline` were not stored by mod-offline. 

We now updated to the latest ejabberd-contrib (as well as ejabberd 15.02), and the new `send_message` command introduced in #68 seems to never store messages when the user is offline. I tried the `chat`, `normal` and `headline` command, and the user never gets the message once he goes online. Is it possible to store messages as offline messages?

**Comment by weiss** [comment]
FWIW, I can't reproduce the issue ...

**Comment by mremond** [comment]
As pointed to me in chatroom by @weiss, here is the intended behaviour, from comment in code:

> Send a packet to a Jabber account. If a resource was specified in the JID, the packet is sent only to that specific resource. If no resource was specified in the JID, and the user is remote or local but offline, the packet is sent to the bare JID. If the user is local and is online in several resources, the packet is sent to all its resources.

@mathiasertl How do you call the function ? Any hints on how we can try reproduce issue ?

**Comment by mathiasertl** [comment]
Upon further inspection, I found that the issue affected my own account, but not other accounts on the same host. I checked the webinterface only to see I had a forgotten screen with a mcabber client that received the message. So the issue is resolved - sorry for you time!

**Comment by mathiasertl** [comment]
PS: Really embarrassing mistake on my side, again sorry ;-)

**Comment by mremond** [comment]
No problem :)
Always a good news to learn this is not a bug ;)
