### ISSUE TITLE
mod_admin_extra "Option {auth_method,error} has invalid (outdated?) format. This is likely a bug"

### ISSUE THREAD

**Issue by wiseoldman95** [processone/ejabberd-contrib#89]
I'm getting the following error when executing `ejabberdctl change_password`:

>2015-03-24 18:35:19.408 [warning] <0.2510.0>@ejabberd_config:get_option:645 Option {auth_method,error} has invalid (outdated?) format. This is likely a bug

**Comment by badlop** [comment]
It works correctly for me when using recent code any auth_password_format, and auth_method: internal. What auth method are you using?

**Comment by wiseoldman95** [comment]
Turns out I was accidentally using very old sources, sorry for the bother. 
This is a bit off topic but, how do I compile the sources? I have ejabberd 15.03, and it doesn't seem to have `ejabberdctl module_install`.

**Comment by cromain** [comment]
you should follow our blogpost https://blog.process-one.net/easy-installer-and-structure-for-ejabberd-contributed-modules/

for first use you must fetch the contributed modules spec
ejabberdctl modules_update_specs

then install your module
ejabberdctl module_install mod_admin_extra
