### ISSUE TITLE
[15.03] mod_admin_extra srg_get_info output changed

### ISSUE THREAD

**Issue by CyrilPeponnet** [processone/ejabberd-contrib#90]
Hi,

```
[root@central-server ejabberd]# ejabberdctl srg_get_info 'All\ Users' `hostname`
name	<<"All Users">>
displayed_groups	[<<"All Hypervisors">>,<<"All Virtual Machines">>]
description	<<"Automatic group">>
```

why those <<>>> ??

On older version:

```
[root@server ~]#  ejabberdctl srg_get_info 'All\ Users' `hostname`
name    "All Users"
displayed_groups        ["All Hypervisors","All Virtual Machines"]
description     "Automatic group"
```

**Comment by CyrilPeponnet** [comment]
and by the way when I try to get them from python, it becomes:

```
[{'displayed_groups': ['<<All Users>>'], 'description': '<<Automatic group>>', 'id': 'All Hypervisors', 'members': ['agent-01.archipel.priv@central-server.archipel.priv'], 'displayed_name': '<<All Hypervisors>>'}, {'displayed_groups': ['<<All Hypervisors>>', '<<All Virtual Machines>>'], 'description': '<<Automatic group>>', 'id': 'All Users', 'members': ['admin@central-server.archipel.priv'], 'displayed_name': '<<All Users>>'}, {'displayed_groups': ['<<All Users>>'], 'description': '<<Automatic group>>', 'id': 'All Virtual Machines', 'members': [], 'displayed_name': '<<All Virtual Machines>>'}]
```

**Comment by CyrilPeponnet** [comment]
Looks related to change of type for binary. But it's still a mess :(

**Comment by mremond** [comment]
Yes, we need to fix the output.
Note: mod_admin_extra will be included in main ejabberd in next release as it is move from contrib to main repository: https://github.com/processone/ejabberd/blob/master/src/mod_admin_extra.erl

**Comment by CyrilPeponnet** [comment]
Note that tte input should be fixed as well when creating a SRG (display group arg is not working as before). 

Any ETA for 15.04 ?

**Comment by badlop** [comment]
Preliminary patch; it isn't necessary to format the result in the command, as it will be formatted by the commands frontend:
```
--- a/src/mod_admin_extra.erl
+++ b/src/mod_admin_extra.erl
@@ -1325,7 +1325,7 @@ srg_get_info(Group, Host) ->
        error -> []
     end,
     [{io_lib:format("~p", [Title]),
-      io_lib:format("~p", [Value])} || {Title, Value} <- Opts].
+      Value} || {Title, Value} <- Opts].
 
 srg_get_members(Group, Host) ->
     Members = mod_shared_roster:get_group_explicit_users(Host,Group),
```
Regarding srg_create, it works correctly for me, maybe because I use ejabberdctl in the shell?

**Comment by prefiks** [comment]
I did change this to:

   [{jlib:atom_to_binary(Title), Value} || {Title,Value} <- Opts]

I also did check all other commands in mod_admin_extra and this was the only one which did has some problem.

**Comment by prefiks** [comment]
This problem was fixed by commit 088c5c4672206fe19f55904cf62c8ddc6a1f4593

**Comment by CyrilPeponnet** [comment]
Thanks guys, can I apply this update using `ejabberdctl module_xxx` ?

**Comment by cromain** [comment]
you need 'ejabberdctl modules_update_specs' first, then 'ejabberdctl module_upgrade mod_admin_extra' should work

**Comment by CyrilPeponnet** [comment]
Oh but as far as I understand the changes as been made to `ejabberd` repo. but not here in contrib.

**Comment by prefiks** [comment]
I also pushed updated version to ejabberd-contrib just now, so you should be able to get fixed version from it too.

**Comment by CyrilPeponnet** [comment]
Works like a charm awesome :) I love the new module management! Thanks again @badlop @prefiks @cromain and @mremond, you are the boss :p

**Comment by CyrilPeponnet** [comment]
One last thing, I seems that `srg_create` can't no longer have empty value for description, name of display group which generate this kind of errors:

```
<Fault -118: 'Error -118\nA problem \'{error_formatting_argument,undefined,binary}\' occurred executing the command srg_create with arguments\n[{host,<<"central-server.archipel.priv">>},\n {description,<<"plop">>},\n {group,<<"plop">>},\n {display,undefined},\n {name,<<"plop">>}]'
```

**Comment by CyrilPeponnet** [comment]
Forget it, just passing '\"\"' instead of nothing do the trick.

**Comment by CyrilPeponnet** [comment]
Just opened #92 this is not the same issue but still related to binary format changes
