### ISSUE TITLE
mod_multicast strange error

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd-contrib#91]
My multicast service has just stop with a strange error, I can't find how to fix it :'( please help me to point this bug out. 
The error message: gen_server 'ejabberd_mod_multicast_unityappstudio.com' terminated with reason: bad record jid in mod_multicast:'-group_dests/1-fun-0-'/2 line 519

![fda752d6-d95d-11e4-87a8-6ab15786f9b7](https://cloud.githubusercontent.com/assets/86736/6965172/c1cf4862-d94f-11e4-87f1-49ce16dbd82d.png)

This is copied from processone/ejabberd#506.

**Comment by badlop** [comment]
Hi shyaken, you can apply this patch to mod_multicast.erl If the problem appears again, it will avoid it and log an error in the log file, maybe that allows to find the problem source:
```
--- a/mod_multicast/src/ejabberd_c2s.erl
+++ b/mod_multicast/src/ejabberd_c2s.erl
@@ -2257,7 +2257,7 @@ presence_broadcast_first(From, StateData, Packet) ->
     StateData#state{pres_a = As}.
 
 format_and_check_privacy(From, StateData, Packet, JIDs, Dir) ->
-    FJIDs = [jlib:make_jid(JID) || JID <- JIDs],
+    FJIDs = make_jids(JIDs),
     lists:filter(
       fun(FJID) ->
              case ejabberd_hooks:run_fold(
@@ -2274,6 +2274,17 @@ format_and_check_privacy(From, StateData, Packet, JIDs, Dir) ->
       end,
       FJIDs).
 
+make_jids(JIDs) ->
+    lists:foldl(
+       fun(JIDS, R) ->
+           case jlib:make_jid(JIDS) of
+               error ->
+                   ?ERROR_MSG("Error processing JID ~p when routing multicast stanza.", [JIDS]),
+                   R;
+               JID -> [JID|R]
+           end
+       end, [], JIDs).
+
 send_multiple(From, Server, JIDs, Packet) ->
     ejabberd_router_multicast:route_multicast(From, Server, JIDs, Packet).
 
```

**Comment by shyaken** [comment]
Thanks badlop, I've been moved to another project for this time so I can't try your changes before, I will apply this changing and report the result if this happend again. Thanks
