### ISSUE TITLE
mod_mam does not start

### ISSUE THREAD

**Issue by ajs124** [processone/ejabberd-contrib#93]
Hey, I want to enable mod_mam on my server, but it does not start.
```
2015-04-07 17:17:12.559 [critical] <0.38.0>@gen_mod:start_module:90 Problem starting the module mod_mam for host <<"xmpp.ajs124.de">> 
 options: []
 error: undef
[{mod_mam,start,[<<"xmpp.ajs124.de">>,[]],[]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,82}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,68}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,272}]}]
2015-04-07 17:17:12.560 [critical] <0.38.0>@gen_mod:start_module:95 ejabberd initialization was aborted because a module start failed.
```
My ejabberd version is 15.03 with erlang 17.4, as shipped by Arch Linux.

@weiss, do you have any idea what might be the problem here?

**Comment by mremond** [comment]
How did you install mod_mam ?
It seems code is not found.

**Comment by beherit** [comment]
I had the same, it's ejabberd bug - already fixed:

https://github.com/processone/ejabberd/commit/8b23727cc6db571b9d1dcc6119e39a602fe37279

This patch works for me.

**Comment by ajs124** [comment]
Thanks for the fast responses, I'll try the patch asap.

**Comment by ajs124** [comment]
The patch worked for me, too. Thanks for your help.
