### ISSUE TITLE
Best way to auth with mongodb?

### ISSUE THREAD

**Issue by iliakan** [processone/ejabberd-contrib#96]
I see there are many modules, is there anything to auth using mongodb?
I also can provide an http-service or write helper scripts if needed.

Don't force me into odbc please :)

**Comment by richp10** [comment]
If you are happy to write a http service, you could use ejabberd_auth_http

ejabberdctl modules_update_specs
ejabberdctl module_install ejabberd_auth_http

Then configure like this..

auth_method: http
auth_opts:
  host: "http://<ip >"

See docs.. I confess right now it is throwing an error for me and not loading, but worth a look

**Comment by iliakan** [comment]
I'm using an external auth method which actually runs a program that does http-auth.
Works good so far.
