### ISSUE TITLE
Please document how to build packages for modules

### ISSUE THREAD

**Issue by darix** [processone/ejabberd-contrib#97]
A while ago I started an [ejabberd-contrib package][1] for opensuse. I saw the [blog post][2] explaining how to install modules with the ejabberdctl script. I would prefer to keep our ejabberd-contrib package alive though.

From what i gathered the ejabberd-dev directory was killed in ejabberd-contrib and i need to build against the ejabberd sources. though now that the build.sh files are gone it would be nice if you could document how to call ```erlc``` to build modules. calling ejabberdctl in the build env is not an option as we dont have network and dont run as root or ejabberd.

Thank you in advance

[1]: https://build.opensuse.org/package/show/devel:languages:erlang/ejabberd-contrib
[2]: https://blog.process-one.net/easy-installer-and-structure-for-ejabberd-contributed-modules/

**Comment by cromain** [comment]
indeed, i will add this documentation in the repository.

**Comment by cromain** [comment]
added in 362a896
