### ISSUE TITLE
unable to invoke api after enabled mod_rest 

### ISSUE THREAD

**Issue by seraphjiang** [processone/ejabberd-contrib#98]
see error below, what does "module_must_be_started_in_vhost" mean and how should i resolve it. 

---
23:22:26.495 [error] CRASH REPORT Process <0.470.0> with 0 neighbours crashed with reason: {module_must_be_started_in_vhost,mod_rest,<<"xjt.cloudapp.net">>} in mod_rest:try_get_option/3 line 107
23:22:26.495 [error] Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.470.0> exit with reason {module_must_be_started_in_vhost,mod_rest,<<"xjt.cloudapp.net">>} in context child_terminated
23:22:27.499 [info] (#Port<0.6311>) Accepted connection 104.40.59.217:1353 -> 100.72.126.78:5285

---

my mod config is 

  -
port: 5285
module: ejabberd_http
hosts:
    - "xjt.cloudapp.net"
request_handlers:
    "/rest": mod_rest

**Comment by mremond** [comment]
Did you add mod_rest in modules section of the configuration ?

**Comment by seraphjiang** [comment]
yes, i added to modules, it could load without problem, but when i post to /rest interface, get above error.
i'm using latest ejabberd, ejabberd-contrib code to compile.

**Comment by beherit** [comment]
most_rest should be configured in old CFG format.

**Comment by badlop** [comment]
> what does "module_must_be_started_in_vhost" mean

It means that ejabberd received an http call for the domain xjt.cloudapp.net, but ejabberd is not serving it (it isn't in its main hosts list).

**Comment by seraphjiang** [comment]
thanks for help. we changed the direction, cannot verify, close for now.
