### ISSUE TITLE
Fail to call set_room_affiliation

### ISSUE THREAD

**Issue by ccyfly** [processone/ejabberd-contrib#99]
I am using ejabberd 14.12 and installed mod_muc_admin in master branch.

And I tried to call command below, but it returns problem

./ejabberdctl set_room_affiliation room1 conference.mydomain.com admin@mydomain.com admin

return:
Problem 'error {badmatch,ok}' occurred executing the command.
Stacktrace: [{mod_muc_admin,set_room_affiliation,4,
                            [{file,"../mod_muc_admin.erl"},{line,825}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,293}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,269}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,218}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,203}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,205}]}]

**Comment by badlop** [comment]
In february there was a change in mod_muc_admin that requires a recent ejabberd, like ejabberd 15.03 or newer.

You have two solutions:
* upgrade your ejabberd to a newer version (or apply the relevant change to your source code)
* downgrade your mod_muc_admin to an older version (or retract the relevant change to your code)

In case you want to downgrade ejabberd-contrib, use this command:
> git checkout 7baf2edbc2da^

Or you can manually retract this change https://github.com/processone/ejabberd-contrib/commit/7baf2edbc2da
